/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:18 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/AVConferenceDelegate.h>

@protocol OS_dispatch_queue, _IDSSessionConnectionDelegate;
@class AVConference, NSMutableArray, NSObject;

@interface _IDSSessionConnection : NSObject <AVConferenceDelegate> {

	AVConference* _connection;
	NSMutableArray* _connectionInfos;
	NSObject*<OS_dispatch_queue> _connectionQueue;
	id<_IDSSessionConnectionDelegate> _delegate;
	long long _callID;
	long long _connType;
	long long _localCell;
	long long _remoteCell;
	char _connectionActive;
	char _connectionEnableAudio;
	char _connectionMuted;

}

@property (assign,nonatomic,__weak) id<_IDSSessionConnectionDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)dealloc;
-(id<_IDSSessionConnectionDelegate>)delegate;
-(void)setDelegate:(id<_IDSSessionConnectionDelegate>)arg1 ;
-(long long)connectionType;
-(id)initWithQueue:(id)arg1 ;
-(void)setMuted:(char)arg1 ;
-(char)muted;
-(void)sendData:(id)arg1 ;
-(void)setAudioEnabled:(char)arg1 ;
-(char)getAudioEnabled;
-(long long)callID;
-(void)conference:(id)arg1 didStartSession:(char)arg2 withUserInfo:(id)arg3 ;
-(void)conference:(id)arg1 didStopWithCallID:(long long)arg2 error:(id)arg3 ;
-(void)conference:(id)arg1 withCallID:(long long)arg2 remoteMediaStalled:(char)arg3 ;
-(void)conference:(id)arg1 receivedFirstRemoteFrameForCallID:(long long)arg2 ;
-(void)conference:(id)arg1 remoteVideoAttributesChanged:(id)arg2 callID:(long long)arg3 ;
-(void)conference:(id)arg1 remoteAudioPaused:(char)arg2 callID:(long long)arg3 ;
-(void)conference:(id)arg1 remoteVideoPaused:(char)arg2 callID:(long long)arg3 ;
-(void)conference:(id)arg1 remoteScreenAttributesChanged:(id)arg2 callID:(long long)arg3 ;
-(void)conference:(id)arg1 updateInputFrequencyLevel:(id)arg2 ;
-(void)conference:(id)arg1 updateOutputFrequencyLevel:(id)arg2 ;
-(void)conference:(id)arg1 updateInputMeterLevel:(float)arg2 ;
-(void)conference:(id)arg1 updateOutputMeterLevel:(float)arg2 ;
-(void)conference:(id)arg1 inititiateRelayRequest:(long long)arg2 requestDict:(id)arg3 ;
-(void)conference:(id)arg1 sendRelayUpdate:(long long)arg2 updateDict:(id)arg3 ;
-(void)conference:(id)arg1 cancelRelayRequest:(long long)arg2 requestDict:(id)arg3 ;
-(void)conference:(id)arg1 videoQualityNotificationForCallID:(long long)arg2 isDegraded:(char)arg3 isRemote:(char)arg4 ;
-(void)conference:(id)arg1 withCallID:(long long)arg2 networkHint:(char)arg3 ;
-(void)conference:(id)arg1 didReceiveData:(id)arg2 forCallID:(long long)arg3 ;
-(unsigned)natType;
-(void)serverDiedForConference:(id)arg1 ;
-(long long)bestCallID;
-(void)createConnectionData:(char)arg1 handler:(/*^block*/id)arg2 ;
-(void)receivedRemoteConnectionData:(id)arg1 ;
-(char)startConnectionAsInitiator:(char)arg1 peerProtocolVersion:(unsigned)arg2 errorHandler:(/*^block*/id)arg3 ;
-(char)stopConnection:(id*)arg1 ;
-(id)connectionInfoWithState:(long long)arg1 ;
-(id)connectionInfoForCallID:(long long)arg1 ;
-(long long)localCell;
-(long long)remoteCell;
-(void)conference:(id)arg1 receivedNoRemotePacketsForTime:(double)arg2 callID:(long long)arg3 ;
@end

