/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:21 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IMSystemMonitorListener.h>

@protocol IDSAppleIDRegistrationCenterMessageDelivery, FTPasswordManager;
@class NSMutableDictionary, NSMutableArray;

@interface IDSAppleIDRegistrationCenter : NSObject <IMSystemMonitorListener> {

	NSMutableDictionary* _queues;
	NSMutableArray* _handlers;
	id<IDSAppleIDRegistrationCenterMessageDelivery> _messageDelivery;
	id<FTPasswordManager> _passwordManager;

}
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(void)addListener:(id)arg1 ;
-(void)removeListener:(id)arg1 ;
-(char)authenticateRegistration:(id)arg1 requireSilentAuth:(char)arg2 ;
-(void)cancelActionsForRegistrationInfo:(id)arg1 ;
-(char)authenticateRegistration:(id)arg1 forceNewToken:(char)arg2 requireSilentAuth:(char)arg3 ;
-(char)authenticateRegistration:(id)arg1 forceNewToken:(char)arg2 ;
-(char)authenticateRegistration:(id)arg1 forceRenewal:(char)arg2 requireSilentAuth:(char)arg3 ;
-(char)queryInitialInvitationContextForRegistration:(id)arg1 ;
-(char)authenticateRegistration:(id)arg1 ;
-(char)validateRegion:(id)arg1 phoneNumber:(id)arg2 forRegistration:(id)arg3 ;
-(id)initWithMessageDelivery:(id)arg1 passwordManager:(id)arg2 ;
-(id)_queueForKey:(id)arg1 ;
-(void)_setQueue:(id)arg1 forKey:(id)arg2 ;
-(void)_notifyRegionValidationSuccess:(id)arg1 regionID:(id)arg2 phoneNumber:(id)arg3 context:(id)arg4 verified:(char)arg5 ;
-(void)_notifyInitialRegionQuerySuccess:(id)arg1 ;
-(void)_renewTokenForRegistrationInfo:(id)arg1 forceRenewal:(char)arg2 failIfNotSilent:(char)arg3 ;
-(void)_notifyRegionValidationFailure:(id)arg1 responseCode:(long long)arg2 registrationError:(long long)arg3 error:(id)arg4 info:(id)arg5 ;
-(void)_notifyAuthenticationSuccess:(id)arg1 ;
-(void)_serviceQueueForKey:(id)arg1 ;
-(void)_noteSuccessfulToken:(id)arg1 profileID:(id)arg2 selfID:(id)arg3 forRegistrationInfo:(id)arg4 wasFetched:(char)arg5 ;
-(void)_notifyAuthenticationFailure:(id)arg1 responseCode:(long long)arg2 registrationError:(long long)arg3 error:(id)arg4 info:(id)arg5 ;
-(char)_sendAuthenticationRequest:(id)arg1 forceNew:(char)arg2 forceRenewal:(char)arg3 failIfNotSilent:(char)arg4 ;
-(void)_fetchTokenForRegistrationInfo:(id)arg1 failIfNotSilent:(char)arg2 failureBlock:(/*^block*/id)arg3 ;
-(void)_processRegionValidationMessage:(id)arg1 deliveredWithError:(id)arg2 resultCode:(long long)arg3 resultDictionary:(id)arg4 ;
-(char)_registrationNeedsAuthentication:(id)arg1 ;
-(char)_registrationIsAuthenticating:(id)arg1 ;
-(char)_sendAuthenticationRequest:(id)arg1 forceNew:(char)arg2 ;
-(void)_processDefaultInvitationContextMessage:(id)arg1 deliveredWithError:(id)arg2 resultCode:(long long)arg3 resultDictionary:(id)arg4 ;
-(char)_queryInitialInvitationContextForRegistration:(id)arg1 ;
-(char)_validateRegionID:(id)arg1 phoneNumber:(id)arg2 registration:(id)arg3 ;
-(char)_sendAuthenticationRequest:(id)arg1 forceNew:(char)arg2 failIfNotSilent:(char)arg3 ;
-(void)_removeMessageForRegistration:(id)arg1 fromQueueForKey:(id)arg2 ;
-(char)_haveQueuedMessageForRegistration:(id)arg1 inQueueForKey:(id)arg2 ;
-(void)_notifyAuthenticating:(id)arg1 ;
-(void)_postUserNotificationWithTitle:(id)arg1 message:(id)arg2 identifier:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
@end

