/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:22 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IDSAsyncMapper : NSObject
+(void)mapArray:(id)arg1 onQueue:(id)arg2 withBlock:(/*^block*/id)arg3 completion:(/*^block*/id)arg4 onQueue:(id)arg5 ;
+(void)mapDictionary:(id)arg1 onQueue:(id)arg2 withBlock:(/*^block*/id)arg3 completion:(/*^block*/id)arg4 onQueue:(id)arg5 ;
+(void)mapArray:(id)arg1 withBlock:(/*^block*/id)arg2 completion:(/*^block*/id)arg3 onQueue:(id)arg4 ;
+(void)mapDictionary:(id)arg1 withBlock:(/*^block*/id)arg2 completion:(/*^block*/id)arg3 onQueue:(id)arg4 ;
@end

