/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:08 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSActivityPushListenerDelegate.h>

@protocol IDSActivityStateProvider;
@class NSMutableSet, NSMutableDictionary, IDSActivityPushListener, FTMessageDelivery, IDSPeerIDManager, IDSDAccountController, IDSDServiceController, NSString;

@interface IDSActivityMonitorStateManager : NSObject <IDSActivityPushListenerDelegate> {

	NSMutableSet* _listeningOnActivities;
	NSMutableDictionary* _listenersByActivity;
	id<IDSActivityStateProvider> _stateProvider;
	IDSActivityPushListener* _pushListener;
	FTMessageDelivery* _messageDelivery;
	IDSPeerIDManager* _peerIDManager;
	IDSDAccountController* _accountController;
	IDSDServiceController* _serviceController;

}

@property (nonatomic,retain) NSMutableSet * listeningOnActivities;                    //@synthesize listeningOnActivities=_listeningOnActivities - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * listenersByActivity;               //@synthesize listenersByActivity=_listenersByActivity - In the implementation block
@property (nonatomic,retain) id<IDSActivityStateProvider> stateProvider;              //@synthesize stateProvider=_stateProvider - In the implementation block
@property (nonatomic,retain) IDSActivityPushListener * pushListener;                  //@synthesize pushListener=_pushListener - In the implementation block
@property (nonatomic,retain) FTMessageDelivery * messageDelivery;                     //@synthesize messageDelivery=_messageDelivery - In the implementation block
@property (nonatomic,retain) IDSPeerIDManager * peerIDManager;                        //@synthesize peerIDManager=_peerIDManager - In the implementation block
@property (nonatomic,retain) IDSDAccountController * accountController;               //@synthesize accountController=_accountController - In the implementation block
@property (nonatomic,retain) IDSDServiceController * serviceController;               //@synthesize serviceController=_serviceController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(void)setup;
-(NSMutableDictionary *)listenersByActivity;
-(void)setListenersByActivity:(NSMutableDictionary *)arg1 ;
-(IDSDServiceController *)serviceController;
-(IDSDAccountController *)accountController;
-(void)setAccountController:(IDSDAccountController *)arg1 ;
-(id<IDSActivityStateProvider>)stateProvider;
-(void)setStateProvider:(id<IDSActivityStateProvider>)arg1 ;
-(FTMessageDelivery *)messageDelivery;
-(void)setMessageDelivery:(FTMessageDelivery *)arg1 ;
-(void)setServiceController:(IDSDServiceController *)arg1 ;
-(IDSPeerIDManager *)peerIDManager;
-(void)setPeerIDManager:(IDSPeerIDManager *)arg1 ;
-(void)pushListener:(id)arg1 receivedUpdatePush:(id)arg2 ;
-(id)storedUpdatesForActivity:(id)arg1 ;
-(void)storeSubscription:(id)arg1 forActivity:(id)arg2 ;
-(void)removeSubscriptionForActivity:(id)arg1 subActivity:(id)arg2 ;
-(id)initWithStateProvider:(id)arg1 messageDelivery:(id)arg2 peerIDManager:(id)arg3 accountController:(id)arg4 serviceController:(id)arg5 queue:(id)arg6 ;
-(void)_updateListener;
-(void)ackUpdatesForActivity:(id)arg1 ;
-(void)_subscribeForInfo:(id)arg1 withDescription:(id)arg2 resolvedTokens:(id)arg3 withCompletion:(/*^block*/id)arg4 ;
-(char)stopListeningOnActivity:(id)arg1 ;
-(char)startListeningOnActivity:(id)arg1 ;
-(NSMutableSet *)listeningOnActivities;
-(IDSActivityPushListener *)pushListener;
-(id)initWithStateProvider:(id)arg1 messageDelivery:(id)arg2 peerIDManager:(id)arg3 accountController:(id)arg4 serviceController:(id)arg5 pushListener:(id)arg6 ;
-(void)addListener:(id)arg1 forActivity:(id)arg2 ;
-(void)removeListener:(id)arg1 forActivity:(id)arg2 ;
-(char)isListeningOnActivity:(id)arg1 ;
-(id)currentSubscriptionsForActivity:(id)arg1 ;
-(void)subscribeForInfo:(id)arg1 onActivity:(id)arg2 withCompletion:(/*^block*/id)arg3 ;
-(void)unsubscribeForActivity:(id)arg1 subActivity:(id)arg2 withCompletion:(/*^block*/id)arg3 ;
-(void)setListeningOnActivities:(NSMutableSet *)arg1 ;
-(void)setPushListener:(IDSActivityPushListener *)arg1 ;
@end

