/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/IDSUser.h>

@class NSString;

@interface IDSAppleUser : NSObject <IDSUser> {

	NSString* _userName;
	NSString* _DSID;

}

@property (nonatomic,readonly) NSString * userName;                 //@synthesize userName=_userName - In the implementation block
@property (nonatomic,readonly) NSString * DSID;                     //@synthesize DSID=_DSID - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)supportsSecureCoding;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)uniqueIdentifier;
-(NSString *)userName;
-(char)isEqualToUser:(id)arg1 ;
-(long long)realm;
-(NSString *)DSID;
-(id)storageIdentifier;
-(id)unprefixedIdentifier;
-(id)realmPrefixedIdentifier;
-(char)shouldReplace:(id)arg1 ;
-(char)isIdenticalToUser:(id)arg1 ;
-(char)isEqualToAppleUser:(id)arg1 ;
-(id)initWithUserName:(id)arg1 DSID:(id)arg2 ;
@end

