/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:24 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/IDSAccountSigningKeyKeychainAdapter.h>

@protocol IDSAccountSigningKeyKeychainAdapter <NSObject>
@required
-(SecKeyRef)createRandomKeyWithQuery:(const CFDictionaryRef)arg1 error:(*)arg2;
-(int)deleteWithQuery:(const CFDictionaryRef)arg1;
-(int)copyMatchingWithQuery:(const CFDictionaryRef)arg1 outData:(const void*)arg2;
-(id)createSignatureWithKey:(SecKeyRef)arg1 algorithm:(const CFStringRef)arg2 overData:(const CFDataRef)arg3 error:(*)arg4;
-(char)verifySignature:(const CFDataRef)arg1 overData:(const CFDataRef)arg2 withKey:(SecKeyRef)arg3 algorithm:(const CFStringRef)arg4 error:(*)arg5;
-(SecKeyRef)copyPublicKey:(SecKeyRef)arg1;
-(id)externalRepresentation:(SecKeyRef)arg1 error:(*)arg2;
-(int)syncCircleStatusWithError:(id*)arg1;

@end


@class NSString;

@interface IDSAccountSigningKeyKeychainAdapter : NSObject <IDSAccountSigningKeyKeychainAdapter>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(SecKeyRef)createRandomKeyWithQuery:(CFDictionaryRef)arg1 error:(_CFError*)arg2 ;
-(int)deleteWithQuery:(CFDictionaryRef)arg1 ;
-(int)copyMatchingWithQuery:(CFDictionaryRef)arg1 outData:(const void*)arg2 ;
-(id)createSignatureWithKey:(SecKeyRef)arg1 algorithm:(CFStringRef)arg2 overData:(CFDataRef)arg3 error:(_CFError*)arg4 ;
-(char)verifySignature:(CFDataRef)arg1 overData:(CFDataRef)arg2 withKey:(SecKeyRef)arg3 algorithm:(CFStringRef)arg4 error:(_CFError*)arg5 ;
-(SecKeyRef)copyPublicKey:(SecKeyRef)arg1 ;
-(id)externalRepresentation:(SecKeyRef)arg1 error:(_CFError*)arg2 ;
-(int)syncCircleStatusWithError:(id*)arg1 ;
@end

