/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:24 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IMUserDefaults;
@class IDSDAccountController, IDSSystemAccountAdapter, NSTimer;

@interface IDSAccountRepair : NSObject {

	char _shouldSupressRepairLogic;
	char _waitingForMigration;
	IDSDAccountController* _accountController;
	IDSSystemAccountAdapter* _systemAccountAdapter;
	id<IMUserDefaults> _userDefaults;
	NSTimer* _repairTimer;
	double _lastBagRepairInterval;

}

@property (nonatomic,retain) IDSDAccountController * accountController;                   //@synthesize accountController=_accountController - In the implementation block
@property (nonatomic,retain) IDSSystemAccountAdapter * systemAccountAdapter;              //@synthesize systemAccountAdapter=_systemAccountAdapter - In the implementation block
@property (nonatomic,retain) id<IMUserDefaults> userDefaults;                             //@synthesize userDefaults=_userDefaults - In the implementation block
@property (nonatomic,retain) NSTimer * repairTimer;                                       //@synthesize repairTimer=_repairTimer - In the implementation block
@property (assign,nonatomic) double lastBagRepairInterval;                                //@synthesize lastBagRepairInterval=_lastBagRepairInterval - In the implementation block
@property (assign,nonatomic) char waitingForMigration;                                    //@synthesize waitingForMigration=_waitingForMigration - In the implementation block
@property (assign,nonatomic) char shouldSupressRepairLogic;                               //@synthesize shouldSupressRepairLogic=_shouldSupressRepairLogic - In the implementation block
+(double)_phoneNumberRepairInterval;
+(double)_phoneNumberRepairMaxInterval;
+(double)_phoneNumberRepairIntervalForCount:(long long)arg1 ;
-(id<IMUserDefaults>)userDefaults;
-(void)repairAccounts;
-(void)setUserDefaults:(id<IMUserDefaults>)arg1 ;
-(IDSDAccountController *)accountController;
-(void)setAccountController:(IDSDAccountController *)arg1 ;
-(void)_repairTimerHit:(id)arg1 ;
-(NSTimer *)repairTimer;
-(void)setRepairTimer:(NSTimer *)arg1 ;
-(char)shouldSupressRepairLogic;
-(void)setShouldSupressRepairLogic:(char)arg1 ;
-(IDSSystemAccountAdapter *)systemAccountAdapter;
-(void)setSystemAccountAdapter:(IDSSystemAccountAdapter *)arg1 ;
-(id)initWithAccountController:(id)arg1 systemAccountAdapter:(id)arg2 userDefaults:(id)arg3 ;
-(void)repairiCloudBasedAccounts;
-(void)forceRepairAccounts:(id)arg1 ;
-(void)kickRepairForAllRegistrationsSucceeded:(id)arg1 ;
-(void)setupPhoneNumberRepairTimer;
-(void)recalculatePhoneRepairTimer;
-(void)_repairAccountsWithSuccessfulPhoneNumberRegistration;
-(void)_repairAccountsWithSuccessfullAppleIDRegistrationForDSID:(id)arg1 service:(id)arg2 ;
-(char)_shouldBypassRepairLogic;
-(void)_resetPhoneNumberRepairCounter;
-(void)_createAndEnableExistingSystemAccounts;
-(void)_repairiTunesBasedAccounts;
-(char)_hasActiveAppleIDBasedAccountOnService:(id)arg1 ;
-(id)_activeAppleIDAccount;
-(id)_createiTunesAccountFromSystemIfNeeded;
-(void)repairService:(id)arg1 withPrimaryUserName:(id)arg2 ;
-(char)_shouldNotSetupPhoneNumberRepairTimer;
-(id)_lastRepairIntervalFromPrefs;
-(id)_totalRepairCountFromPrefs;
-(void)_phoneNumberRepairTimerHit:(id)arg1 ;
-(char)_repairPhoneNumberAccounts;
-(double)lastBagRepairInterval;
-(void)setLastBagRepairInterval:(double)arg1 ;
-(char)waitingForMigration;
-(void)setWaitingForMigration:(char)arg1 ;
@end

