/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:01 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSData;

@interface IDSActivityUpdatePush : NSObject {

	char _activityStatus;
	NSString* _activityTopic;
	NSData* _token;
	NSString* _activitySubActivity;
	NSData* _metadataBlob;
	long long _activityTimestamp;

}

@property (nonatomic,retain) NSString * activityTopic;                    //@synthesize activityTopic=_activityTopic - In the implementation block
@property (nonatomic,retain) NSData * token;                              //@synthesize token=_token - In the implementation block
@property (nonatomic,retain) NSString * activitySubActivity;              //@synthesize activitySubActivity=_activitySubActivity - In the implementation block
@property (nonatomic,retain) NSData * metadataBlob;                       //@synthesize metadataBlob=_metadataBlob - In the implementation block
@property (assign,nonatomic) char activityStatus;                         //@synthesize activityStatus=_activityStatus - In the implementation block
@property (assign,nonatomic) long long activityTimestamp;                 //@synthesize activityTimestamp=_activityTimestamp - In the implementation block
-(NSData *)token;
-(void)setToken:(NSData *)arg1 ;
-(NSString *)activityTopic;
-(void)setActivityTopic:(NSString *)arg1 ;
-(NSData *)metadataBlob;
-(void)setMetadataBlob:(NSData *)arg1 ;
-(NSString *)activitySubActivity;
-(void)setActivitySubActivity:(NSString *)arg1 ;
-(char)activityStatus;
-(void)setActivityStatus:(char)arg1 ;
-(long long)activityTimestamp;
-(void)setActivityTimestamp:(long long)arg1 ;
@end

