/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:06 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSError;

@interface IDSAckStateMachine : NSObject {

	char _successful;
	long long _state;
	NSError* _error;

}

@property (assign,nonatomic) long long state;              //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) char successful;              //@synthesize successful=_successful - In the implementation block
@property (nonatomic,retain) NSError * error;              //@synthesize error=_error - In the implementation block
-(id)init;
-(long long)state;
-(NSError *)error;
-(void)setError:(NSError *)arg1 ;
-(void)setState:(long long)arg1 ;
-(void)setSuccessful:(char)arg1 ;
-(char)successful;
@end

