/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:57 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject;

@interface IDSBlockRetryHandler : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	/*^block*/id _backoffProvider;
	/*^block*/id _block;
	long long _attempts;
	/*^block*/id _scheduledBlock;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (nonatomic,copy) id backoffProvider;                                //@synthesize backoffProvider=_backoffProvider - In the implementation block
@property (nonatomic,copy) id block;                                          //@synthesize block=_block - In the implementation block
@property (assign,nonatomic) long long attempts;                              //@synthesize attempts=_attempts - In the implementation block
@property (nonatomic,copy) id scheduledBlock;                                 //@synthesize scheduledBlock=_scheduledBlock - In the implementation block
-(void)dealloc;
-(id)block;
-(void)start;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)stop;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setBlock:(id)arg1 ;
-(void)_run;
-(long long)attempts;
-(void)setAttempts:(long long)arg1 ;
-(/*^block*/id)_isFinishedBlock;
-(void)setScheduledBlock:(id)arg1 ;
-(id)backoffProvider;
-(void)_deferToQueue:(id)arg1 after:(double)arg2 block:(/*^block*/id)arg3 ;
-(id)initWithQueue:(id)arg1 backoffProvider:(/*^block*/id)arg2 block:(/*^block*/id)arg3 ;
-(void)setBackoffProvider:(id)arg1 ;
-(id)scheduledBlock;
@end

