/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:00 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface IDSConnectivityMonitorMetricProperties : NSObject {

	char _success;
	char _terminusConnected;
	char _terminusNearby;
	char _terminusRegistered;
	double _timeConnected;
	double _timeDisconnected;
	NSString* _personalCBUUIDString;
	NSString* _pairedDeviceCBUUIDString;

}

@property (assign,nonatomic) char success;                                     //@synthesize success=_success - In the implementation block
@property (assign,nonatomic) char terminusConnected;                           //@synthesize terminusConnected=_terminusConnected - In the implementation block
@property (assign,nonatomic) char terminusNearby;                              //@synthesize terminusNearby=_terminusNearby - In the implementation block
@property (assign,nonatomic) char terminusRegistered;                          //@synthesize terminusRegistered=_terminusRegistered - In the implementation block
@property (assign,nonatomic) double timeConnected;                             //@synthesize timeConnected=_timeConnected - In the implementation block
@property (assign,nonatomic) double timeDisconnected;                          //@synthesize timeDisconnected=_timeDisconnected - In the implementation block
@property (nonatomic,retain) NSString * personalCBUUIDString;                  //@synthesize personalCBUUIDString=_personalCBUUIDString - In the implementation block
@property (nonatomic,retain) NSString * pairedDeviceCBUUIDString;              //@synthesize pairedDeviceCBUUIDString=_pairedDeviceCBUUIDString - In the implementation block
-(char)success;
-(void)setSuccess:(char)arg1 ;
-(char)terminusConnected;
-(char)terminusNearby;
-(char)terminusRegistered;
-(double)timeConnected;
-(double)timeDisconnected;
-(NSString *)personalCBUUIDString;
-(NSString *)pairedDeviceCBUUIDString;
-(void)setTerminusConnected:(char)arg1 ;
-(void)setTerminusNearby:(char)arg1 ;
-(void)setTerminusRegistered:(char)arg1 ;
-(void)setTimeConnected:(double)arg1 ;
-(void)setTimeDisconnected:(double)arg1 ;
-(void)setPersonalCBUUIDString:(NSString *)arg1 ;
-(void)setPairedDeviceCBUUIDString:(NSString *)arg1 ;
@end

