/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:13 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_nw_nexus;
#import <identityservicesd/identityservicesd-Structs.h>
@class NSObject, NSMutableDictionary, IDSNexusAgent, NWNetworkAgentRegistration;

@interface IDSClientChannelManager : NSObject {

	NSObject*<OS_nw_nexus> _nexus;
	NEVirtualInterface_sRef _vifRef;
	NSMutableDictionary* _clientChannelRegistrations;
	NSMutableDictionary* _clientChannels;
	IDSNexusAgent* _agent;
	NWNetworkAgentRegistration* _registration;
	nexus_controllerRef _osNexusController;
	unsigned char _osNexusName[64];
	unsigned char _osNexusUUID[16];
	NSMutableDictionary* _clientUUIDs;

}
+(id)sharedInstance;
-(id)init;
-(char)addClient:(id)arg1 ;
-(void)removeClient:(id)arg1 ;
-(char)registerClientChannelDestination:(id)arg1 connectHandler:(/*^block*/id)arg2 ;
-(char)unregisterClientChannelDestination:(id)arg1 ;
-(char)connectTransportThreadForClient:(id)arg1 ;
-(char)connectProtocolHandlerForClient:(id)arg1 ;
@end

