/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@class NSDate;

@interface IDSCountdown : NSObject {

	NSDate* _startDate;
	opaque_pthread_mutex_t _startDateMutex;
	double _timeInterval;

}

@property (nonatomic,readonly) char isCountingDown; 
-(void)dealloc;
-(id)initWithTimeInterval:(double)arg1 ;
-(char)_criticalIsCountingDown;
-(char)startCountingDown;
-(char)isCountingDown;
@end

