/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:19 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary;

@interface IDSClientDataResult : NSObject {

	NSDictionary* _clientDatasByServiceType;
	NSDictionary* _transparencyLoggableDatasByServiceType;

}

@property (nonatomic,retain) NSDictionary * clientDatasByServiceType;                            //@synthesize clientDatasByServiceType=_clientDatasByServiceType - In the implementation block
@property (nonatomic,retain) NSDictionary * transparencyLoggableDatasByServiceType;              //@synthesize transparencyLoggableDatasByServiceType=_transparencyLoggableDatasByServiceType - In the implementation block
-(NSDictionary *)clientDatasByServiceType;
-(NSDictionary *)transparencyLoggableDatasByServiceType;
-(void)setClientDatasByServiceType:(NSDictionary *)arg1 ;
-(void)setTransparencyLoggableDatasByServiceType:(NSDictionary *)arg1 ;
@end

