/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:13 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData;

@interface IDSCloudKitKeyTransparencyDeviceRecord : NSObject {

	NSData* _deviceData;
	NSData* _deviceMetadata;

}

@property (nonatomic,readonly) NSData * deviceData;                  //@synthesize deviceData=_deviceData - In the implementation block
@property (nonatomic,readonly) NSData * deviceMetadata;              //@synthesize deviceMetadata=_deviceMetadata - In the implementation block
+(id)recordWithDeviceData:(id)arg1 deviceMetadata:(id)arg2 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSData *)deviceMetadata;
-(NSData *)deviceData;
-(id)initWithDeviceData:(id)arg1 deviceMetadata:(id)arg2 ;
-(char)isEqualToCloudKitKeyTransparencyDeviceRecord:(id)arg1 ;
@end

