/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:05 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSCTAdapterListener <NSObject>
@optional
-(void)SIMInformationDidChange;
-(void)SIM:(id)arg1 didUpdateRegistrationState:(char)arg2;
-(void)carrierBundleInformationDidChange;

@end

