/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:05 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSUTunDeliveryControllerConnectivityDelegate.h>

@protocol OS_dispatch_queue, IDSDAccountControllerDeviceSupport, IDSDAccountControllerDelegate;
@class NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSObject, IDSSystemAccountAdapter, IDSDServiceController, IDSRegistrationController, NSArray, NSSet, NSString;

@interface IDSDAccountController : NSObject <IDSUTunDeliveryControllerConnectivityDelegate> {

	NSMutableDictionary* _accountIDMap;
	NSMutableSet* _enabledAccounts;
	NSMutableDictionary* _deviceProperties;
	NSRecursiveLock* _accountIDMapLock;
	char _accountsLoaded;
	char _isLoading;
	char _hasHardDeregistered;
	NSObject*<OS_dispatch_queue> _authkitQueue;
	IDSSystemAccountAdapter* _systemAccountAdapter;
	IDSDServiceController* _serviceController;
	IDSRegistrationController* _registrationController;
	id<IDSDAccountControllerDeviceSupport> _deviceSupport;
	id<IDSDAccountControllerDelegate> _delegate;

}

@property (nonatomic,readonly) NSArray * accounts; 
@property (nonatomic,readonly) NSSet * enabledAccounts; 
@property (nonatomic,readonly) char hasHardDeregistered;                              //@synthesize hasHardDeregistered=_hasHardDeregistered - In the implementation block
@property (nonatomic,retain) id<IDSDAccountControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
+(char)isDefaultPairedDeviceFromID:(id)arg1 accountUniqueID:(id)arg2 serviceName:(id)arg3 ;
-(void)dealloc;
-(id)init;
-(id<IDSDAccountControllerDelegate>)delegate;
-(void)setDelegate:(id<IDSDAccountControllerDelegate>)arg1 ;
-(id)userDefaults;
-(id)daemon;
-(char)hasiCloudAccount;
-(NSArray *)accounts;
-(id)registrationListener;
-(void)startLocalSetup;
-(void)stopLocalSetup;
-(void)_removeAccount:(id)arg1 ;
-(void)forceRemoveAccount:(id)arg1 ;
-(void)hardDeregister;
-(void)triggerFinalDeregister;
-(NSSet *)enabledAccounts;
-(id)accountWithUniqueID:(id)arg1 ;
-(void)addAccount:(id)arg1 ;
-(void)removeAccount:(id)arg1 ;
-(char)isLoading;
-(char)isiCloudSignedIn;
-(char)isiTunesSignedIn;
-(void)delayedSaveSettings;
-(id)deviceNameForDeviceID:(id)arg1 ;
-(id)deviceIDForPushToken:(id)arg1 ;
-(void)loadStoredAccounts;
-(id)accountsOnService:(id)arg1 ;
-(char)isEnabledAccount:(id)arg1 ;
-(id)accountsWithType:(int)arg1 ;
-(id)accountWithServiceName:(id)arg1 aliasURI:(id)arg2 ;
-(void)disableAccountWithUniqueID:(id)arg1 ;
-(void)issueGetDependentRequest;
-(void)updateExpiredDependent;
-(void)issueDependentIDQueriesWithCompletionBlock:(/*^block*/id)arg1 ;
-(id)appleIDAccountOnService:(id)arg1 ;
-(void)_servicesRemoved:(id)arg1 ;
-(void)_servicesChanged;
-(void)_registerForAllRegistrationsSucceeded;
-(void)loadDeviceProperties;
-(id)initWithServiceController:(id)arg1 registrationController:(id)arg2 systemAccountAdapter:(id)arg3 deviceSupport:(id)arg4 ;
-(void)_storeAccounts;
-(void)_disableAccountWithUniqueID:(id)arg1 ;
-(void)_cleanUpAccountCredentialForRemovedAccount:(id)arg1 ;
-(id)_inUseUsernames;
-(id)_inUseProfileIDs;
-(id)existingAccountOnService:(id)arg1 withType:(int)arg2 loginID:(id)arg3 ;
-(void)_addAccount:(id)arg1 ;
-(void)_setupAdHocAccountsForPrimaryAccount:(id)arg1 ;
-(void)addPrimaryAccount:(id)arg1 ;
-(void)_removePrimaryAccount:(id)arg1 ;
-(void)_disablePrimaryAccountWithUniqueID:(id)arg1 userAction:(char)arg2 ;
-(void)_enableAccountWithUniqueID:(id)arg1 ;
-(void)enablePrimaryAccountWithUniqueID:(id)arg1 ;
-(id)accountsOnService:(id)arg1 withType:(int)arg2 ;
-(void)setupLocalAccountForService:(id)arg1 ;
-(void)_setupLocalAccounts;
-(void)_setupUsingRemoteInfo;
-(void)_setupForLocal;
-(void)_setupAdHocAccounts;
-(void)_cleanupLocalAccounts;
-(char)isLocalSetupEnabled;
-(char)isTraditionalLocalSetupEnabled;
-(void)enableAccountWithUniqueID:(id)arg1 ;
-(void)_migrateLegacyAccounts1;
-(void)_migrateLegacyAccounts2;
-(id)_legacyAccountsOnService:(id)arg1 ;
-(void)_persistAccounts:(id)arg1 ;
-(id)_preferencesOnDomain:(id)arg1 ;
-(char)hasForcedReRegistered;
-(void)issueGetDependentRequestForAccount:(id)arg1 ;
-(void)_refreshLocalAccounts;
-(void)_migrateLegacyAccounts;
-(char)_loadAndEnableStoredAccounts;
-(void)_loadAndEnableStoredLegacyAccounts;
-(void)_cleanupLegacyAccounts;
-(void)_cleanupLegacyLocalAccounts;
-(void)_setupLinkedAccounts;
-(void)_cleanUpAccountCredentialStore;
-(void)_resumeGDRReAuthenticateIfNecessary;
-(id)_createAccountWithDictionary:(id)arg1 service:(id)arg2 uniqueID:(id)arg3 ;
-(void)_addAccountDuringInitialSetup:(id)arg1 ;
-(void)_attachOrphanedPhoneAliases:(id)arg1 toRecipientAccounts:(id)arg2 withAccountsToEnable:(id)arg3 ;
-(void)_updateDeviceProperties;
-(void)saveDevicePropertiesWithOldKeys:(id)arg1 ;
-(void)deliveryController:(id)arg1 uniqueID:(id)arg2 isNearby:(char)arg3 ;
-(void)deliveryController:(id)arg1 uniqueID:(id)arg2 isConnected:(char)arg3 ;
-(void)deliveryController:(id)arg1 uniqueID:(id)arg2 isCloudConnected:(char)arg3 ;
-(void)disablePrimaryAccountWithUniqueID:(id)arg1 ;
-(id)accountOnService:(id)arg1 withAliasURI:(id)arg2 ;
-(id)accountOnService:(id)arg1 withLoginID:(id)arg2 ;
-(id)localAccountOnService:(id)arg1 ;
-(id)accountWithServiceName:(id)arg1 loginID:(id)arg2 ;
-(id)accountWithServiceName:(id)arg1 myID:(id)arg2 ;
-(id)accountUniqueIDsWithType:(int)arg1 ;
-(id)primaryAccountForAdHocAccount:(id)arg1 ;
-(id)threadSafeServiceWithAccountUniqueID:(id)arg1 ;
-(id)_strippedAccountInfo:(id)arg1 ;
-(char)_isAccountInfoRegistered:(id)arg1 ;
-(void)__pairedDeviceStateUpdated;
-(char)accountsLoaded;
-(id)enabledAccountsOnService:(id)arg1 ;
-(id)registeredAccountsOnService:(id)arg1 ;
-(id)accountsOfAdHocType:(unsigned)arg1 ;
-(char)hasActiveSMSAccount;
-(void)issueGetDependentAndGetHandlesRequest;
-(id)cloudPairedIDForDeviceID:(id)arg1 ;
-(id)pushTokenForDeviceID:(id)arg1 ;
-(id)publicKeyForDeviceID:(id)arg1 ;
-(void)setNSUUID:(id)arg1 onDeviceWithUniqueID:(id)arg2 ;
-(id)propertiesForDeviceWithUniqueID:(id)arg1 ;
-(void)updateDevicePropertiesWithDevices:(id)arg1 ;
-(char)isiCloudHSA2;
-(void)authKitAccountUpdate:(id)arg1 ;
-(id)deviceCertificateForService:(id)arg1 uri:(id)arg2 ;
-(char)hasHardDeregistered;
@end

