/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:05 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSXPCPairedDeviceManager.h>

@class IDSPairingManager, NSString;

@interface IDSDXPCPairedDeviceManager : NSObject <IDSXPCPairedDeviceManager> {

	IDSPairingManager* _pairingManager;

}

@property (nonatomic,retain) IDSPairingManager * pairingManager;              //@synthesize pairingManager=_pairingManager - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)getLocalDeviceInfoWithCompletion:(/*^block*/id)arg1 ;
-(void)getPairedDeviceInfoWithCompletion:(/*^block*/id)arg1 ;
-(IDSPairingManager *)pairingManager;
-(id)initWithPairingManager:(id)arg1 ;
-(void)setPairingManager:(IDSPairingManager *)arg1 ;
@end

