/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, FTMessageDelivery, IMMultiQueue;

@interface IDSDSessionController : NSObject {

	NSMutableDictionary* _sessions;
	FTMessageDelivery* _messageDelivery;
	IMMultiQueue* _sessionIDMultiQueue;
	char _reportedReceivedMKM;

}

@property (readonly) FTMessageDelivery * messageDelivery;              //@synthesize messageDelivery=_messageDelivery - In the implementation block
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(void)cleanupSession:(id)arg1 ;
-(void)cleanupSessionWithInstanceID:(id)arg1 ;
-(FTMessageDelivery *)messageDelivery;
-(id)sessionWithUniqueID:(id)arg1 ;
-(void)updateCriticalReliabilityState;
-(void)cleanupSessionsForClient:(id)arg1 ;
-(id)sessionWithGroupID:(id)arg1 ;
-(id)groupSessionGroupIDs;
-(id)_specificOriginatorFromID:(id)arg1 senderToken:(id)arg2 accountUniqueID:(id)arg3 ;
-(id)sessionWithGroupUUID:(id)arg1 ;
-(id)setupNewIncomingSessionWithOptions:(id)arg1 ;
-(id)sessionWithInstanceID:(id)arg1 ;
-(id)setupNewOutgoingSessionWithOptions:(id)arg1 ;
-(void)processIncomingInvitationWithPayload:(id)arg1 topic:(id)arg2 fromToken:(id)arg3 fromID:(id)arg4 toID:(id)arg5 shouldFilter:(char)arg6 idsMessageContext:(id)arg7 messageContext:(id)arg8 ;
-(void)processIncomingSessionAcceptMessage:(id)arg1 fromToken:(id)arg2 fromID:(id)arg3 idsMessageContext:(id)arg4 ;
-(void)processIncomingSessionDeclineMessage:(id)arg1 fromToken:(id)arg2 fromID:(id)arg3 idsMessageContext:(id)arg4 ;
-(void)processIncomingSessionCancelMessage:(id)arg1 fromToken:(id)arg2 fromID:(id)arg3 idsMessageContext:(id)arg4 ;
-(void)processIncomingSessionMessage:(id)arg1 fromToken:(id)arg2 fromID:(id)arg3 idsMessageContext:(id)arg4 ;
-(void)processIncomingSessionEndMessage:(id)arg1 fromToken:(id)arg2 fromID:(id)arg3 idsMessageContext:(id)arg4 ;
-(void)processIncomingSessionReinitiateMessage:(id)arg1 fromToken:(id)arg2 fromID:(id)arg3 idsMessageContext:(id)arg4 ;
-(void)processIncomingGroupSessionMessage:(id)arg1 fromToken:(id)arg2 fromID:(id)arg3 toID:(id)arg4 topic:(id)arg5 idsMessageContext:(id)arg6 ;
-(void)cleanupSessionWithChannelDestination:(id)arg1 ;
-(void)_handleClientDeath:(id)arg1 ;
@end

