/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:13 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSDSession;
#import <identityservicesd/identityservicesd-Structs.h>
@class NSString, NSUUID, _IDSSessionConnection, IMTimer, NSSet, NSError, NSData, NSNumber, NSDate, NSArray, IDSMPFullLegacyIdentity, IDSMPPublicLegacyIdentity;

@interface IDSDSessionSharedState : NSObject {

	AB _connectionTimerCleared;
	char _disableEncryption;
	char _disableRemoteDeviceEncryption;
	char _enableQuickRelay;
	char _enableSingleChannelDirectMode;
	char _enableSKE;
	char _encryptionInitialized;
	AB _endSessionTimerCleared;
	char _forceInternetInvitation;
	char _isInitiator;
	char _isScreenSharingSession;
	AB _inviteTimerCleared;
	char _sharedSession;
	char _useBTDatagramPipe;
	char _useSecureQRControlMessage;
	char _useQRDirectly;
	unsigned _invitationRetryCount;
	unsigned _peerProtocolVersion;
	unsigned _seqSend;
	unsigned _state;
	NSString* _accountID;
	long long _clientType;
	NSUUID* _clientUUID;
	_IDSSessionConnection* _connection;
	unsigned long long _connectionCountHint;
	double _connectionTimeout;
	IMTimer* _connectionTimer;
	NSSet* _destinations;
	double _endSessionTimeout;
	IMTimer* _endSessionTimer;
	NSError* _error;
	NSString* _fromID;
	NSString* _groupID;
	double _inviteSentTime;
	double _inviteTimeout;
	IMTimer* _inviteTimer;
	double _lastPacketTime;
	NSData* _localBlob;
	IMTimer* _packetLossTimer;
	NSString* _participantID;
	NSNumber* _remoteUseCloudPairedControlChannel;
	NSNumber* _remoteUsePhoneContinuityLocalMessage;
	NSString* _serviceName;
	NSDate* _startConnectingDate;
	long long _transportType;
	NSString* _uniqueID;
	NSArray* _pluginRequests;
	IDSMPFullLegacyIdentity* _localUnauthenticatedFullIdentity;
	IDSMPPublicLegacyIdentity* _remoteUnauthenticatedPublicIdentity;
	id<IDSDSession> _delegate;
	SCD_Struct_ID23* _encryptionStateStruct;

}

@property (assign,nonatomic) SCD_Struct_ID23* encryptionStateStruct;                                       //@synthesize encryptionStateStruct=_encryptionStateStruct - In the implementation block
@property (nonatomic,retain) NSString * accountID;                                                         //@synthesize accountID=_accountID - In the implementation block
@property (assign,nonatomic) long long clientType;                                                         //@synthesize clientType=_clientType - In the implementation block
@property (nonatomic,retain) NSUUID * clientUUID;                                                          //@synthesize clientUUID=_clientUUID - In the implementation block
@property (nonatomic,retain) _IDSSessionConnection * connection;                                           //@synthesize connection=_connection - In the implementation block
@property (assign,nonatomic) unsigned long long connectionCountHint;                                       //@synthesize connectionCountHint=_connectionCountHint - In the implementation block
@property (assign,nonatomic) double connectionTimeout;                                                     //@synthesize connectionTimeout=_connectionTimeout - In the implementation block
@property (nonatomic,retain) IMTimer * connectionTimer;                                                    //@synthesize connectionTimer=_connectionTimer - In the implementation block
@property (assign,nonatomic) AB connectionTimerCleared;                                                    //@synthesize connectionTimerCleared=_connectionTimerCleared - In the implementation block
@property (nonatomic,retain) NSSet * destinations;                                                         //@synthesize destinations=_destinations - In the implementation block
@property (assign,nonatomic) char disableEncryption;                                                       //@synthesize disableEncryption=_disableEncryption - In the implementation block
@property (assign,nonatomic) char disableRemoteDeviceEncryption;                                           //@synthesize disableRemoteDeviceEncryption=_disableRemoteDeviceEncryption - In the implementation block
@property (assign,nonatomic) char enableQuickRelay;                                                        //@synthesize enableQuickRelay=_enableQuickRelay - In the implementation block
@property (assign,nonatomic) char enableSingleChannelDirectMode;                                           //@synthesize enableSingleChannelDirectMode=_enableSingleChannelDirectMode - In the implementation block
@property (assign,nonatomic) char enableSKE;                                                               //@synthesize enableSKE=_enableSKE - In the implementation block
@property (assign,nonatomic) char encryptionInitialized;                                                   //@synthesize encryptionInitialized=_encryptionInitialized - In the implementation block
@property (nonatomic,readonly) SCD_Struct_ID23* encryptionState; 
@property (assign,nonatomic) double endSessionTimeout;                                                     //@synthesize endSessionTimeout=_endSessionTimeout - In the implementation block
@property (nonatomic,retain) IMTimer * endSessionTimer;                                                    //@synthesize endSessionTimer=_endSessionTimer - In the implementation block
@property (assign,nonatomic) AB endSessionTimerCleared;                                                    //@synthesize endSessionTimerCleared=_endSessionTimerCleared - In the implementation block
@property (nonatomic,retain) NSError * error;                                                              //@synthesize error=_error - In the implementation block
@property (assign,nonatomic) char forceInternetInvitation;                                                 //@synthesize forceInternetInvitation=_forceInternetInvitation - In the implementation block
@property (nonatomic,retain) NSString * fromID;                                                            //@synthesize fromID=_fromID - In the implementation block
@property (nonatomic,retain) NSString * groupID;                                                           //@synthesize groupID=_groupID - In the implementation block
@property (assign,nonatomic) double inviteSentTime;                                                        //@synthesize inviteSentTime=_inviteSentTime - In the implementation block
@property (assign,nonatomic) char isInitiator;                                                             //@synthesize isInitiator=_isInitiator - In the implementation block
@property (assign,nonatomic) char isScreenSharingSession;                                                  //@synthesize isScreenSharingSession=_isScreenSharingSession - In the implementation block
@property (assign,nonatomic) unsigned invitationRetryCount;                                                //@synthesize invitationRetryCount=_invitationRetryCount - In the implementation block
@property (assign,nonatomic) double inviteTimeout;                                                         //@synthesize inviteTimeout=_inviteTimeout - In the implementation block
@property (nonatomic,retain) IMTimer * inviteTimer;                                                        //@synthesize inviteTimer=_inviteTimer - In the implementation block
@property (assign,nonatomic) AB inviteTimerCleared;                                                        //@synthesize inviteTimerCleared=_inviteTimerCleared - In the implementation block
@property (assign,nonatomic) double lastPacketTime;                                                        //@synthesize lastPacketTime=_lastPacketTime - In the implementation block
@property (nonatomic,retain) NSData * localBlob;                                                           //@synthesize localBlob=_localBlob - In the implementation block
@property (nonatomic,retain) IMTimer * packetLossTimer;                                                    //@synthesize packetLossTimer=_packetLossTimer - In the implementation block
@property (nonatomic,retain) NSString * participantID;                                                     //@synthesize participantID=_participantID - In the implementation block
@property (assign,nonatomic) unsigned peerProtocolVersion;                                                 //@synthesize peerProtocolVersion=_peerProtocolVersion - In the implementation block
@property (nonatomic,readonly) NSString * pushTopic; 
@property (nonatomic,retain) NSNumber * remoteUseCloudPairedControlChannel;                                //@synthesize remoteUseCloudPairedControlChannel=_remoteUseCloudPairedControlChannel - In the implementation block
@property (nonatomic,retain) NSNumber * remoteUsePhoneContinuityLocalMessage;                              //@synthesize remoteUsePhoneContinuityLocalMessage=_remoteUsePhoneContinuityLocalMessage - In the implementation block
@property (nonatomic,retain) NSString * serviceName;                                                       //@synthesize serviceName=_serviceName - In the implementation block
@property (assign,nonatomic) unsigned seqSend;                                                             //@synthesize seqSend=_seqSend - In the implementation block
@property (assign,nonatomic) char sharedSession;                                                           //@synthesize sharedSession=_sharedSession - In the implementation block
@property (nonatomic,retain) NSDate * startConnectingDate;                                                 //@synthesize startConnectingDate=_startConnectingDate - In the implementation block
@property (assign,nonatomic) unsigned state;                                                               //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) long long transportType;                                                      //@synthesize transportType=_transportType - In the implementation block
@property (nonatomic,retain) NSString * uniqueID;                                                          //@synthesize uniqueID=_uniqueID - In the implementation block
@property (assign,nonatomic) char useBTDatagramPipe;                                                       //@synthesize useBTDatagramPipe=_useBTDatagramPipe - In the implementation block
@property (assign,nonatomic) char useSecureQRControlMessage;                                               //@synthesize useSecureQRControlMessage=_useSecureQRControlMessage - In the implementation block
@property (assign,nonatomic) char useQRDirectly;                                                           //@synthesize useQRDirectly=_useQRDirectly - In the implementation block
@property (nonatomic,retain) NSArray * pluginRequests;                                                     //@synthesize pluginRequests=_pluginRequests - In the implementation block
@property (nonatomic,retain) IDSMPFullLegacyIdentity * localUnauthenticatedFullIdentity;                   //@synthesize localUnauthenticatedFullIdentity=_localUnauthenticatedFullIdentity - In the implementation block
@property (nonatomic,retain) IDSMPPublicLegacyIdentity * remoteUnauthenticatedPublicIdentity;              //@synthesize remoteUnauthenticatedPublicIdentity=_remoteUnauthenticatedPublicIdentity - In the implementation block
@property (assign,nonatomic,__weak) id<IDSDSession> delegate;                                              //@synthesize delegate=_delegate - In the implementation block
-(id<IDSDSession>)delegate;
-(void)setDelegate:(id<IDSDSession>)arg1 ;
-(_IDSSessionConnection *)connection;
-(unsigned)state;
-(NSError *)error;
-(void)setConnection:(_IDSSessionConnection *)arg1 ;
-(void)setError:(NSError *)arg1 ;
-(void)setState:(unsigned)arg1 ;
-(NSString *)uniqueID;
-(void)setUniqueID:(NSString *)arg1 ;
-(NSString *)serviceName;
-(char)isInitiator;
-(void)setIsInitiator:(char)arg1 ;
-(void)setServiceName:(NSString *)arg1 ;
-(NSString *)groupID;
-(void)setGroupID:(NSString *)arg1 ;
-(long long)transportType;
-(NSString *)accountID;
-(void)setAccountID:(NSString *)arg1 ;
-(NSString *)participantID;
-(void)setParticipantID:(NSString *)arg1 ;
-(void)setTransportType:(long long)arg1 ;
-(NSSet *)destinations;
-(void)setDestinations:(NSSet *)arg1 ;
-(char)sharedSession;
-(void)setFromID:(NSString *)arg1 ;
-(NSString *)pushTopic;
-(void)setInviteTimeout:(double)arg1 ;
-(double)inviteTimeout;
-(NSString *)fromID;
-(long long)clientType;
-(char)enableSKE;
-(SCD_Struct_ID23*)encryptionState;
-(void)setSharedSession:(char)arg1 ;
-(double)connectionTimeout;
-(void)setConnectionTimeout:(double)arg1 ;
-(void)setClientType:(long long)arg1 ;
-(void)_connectionTimedOut;
-(IMTimer *)connectionTimer;
-(void)setConnectionTimer:(IMTimer *)arg1 ;
-(NSUUID *)clientUUID;
-(void)setClientUUID:(NSUUID *)arg1 ;
-(void)setPeerProtocolVersion:(unsigned)arg1 ;
-(unsigned)peerProtocolVersion;
-(char)disableEncryption;
-(void)setDisableEncryption:(char)arg1 ;
-(char)forceInternetInvitation;
-(NSNumber *)remoteUsePhoneContinuityLocalMessage;
-(void)setRemoteUsePhoneContinuityLocalMessage:(NSNumber *)arg1 ;
-(char)isScreenSharingSession;
-(char)destinationIsDefaultPairedDevice:(id)arg1 ;
-(void)setInvitationTimer;
-(char)enableQuickRelay;
-(id)getQuickRelayAllocateOptions:(id)arg1 ;
-(char)enableSingleChannelDirectMode;
-(char)useBTDatagramPipe;
-(IDSMPFullLegacyIdentity *)localUnauthenticatedFullIdentity;
-(unsigned long long)connectionCountHint;
-(void)setSeqSend:(unsigned)arg1 ;
-(double)inviteSentTime;
-(void)setInviteSentTime:(double)arg1 ;
-(void)clearAllTimers;
-(void)setStartConnectingDate:(NSDate *)arg1 ;
-(char)useQRDirectly;
-(void)setConnectionTimer;
-(void)setDisableRemoteDeviceEncryption:(char)arg1 ;
-(NSData *)localBlob;
-(void)setEncryptionInitialized:(char)arg1 ;
-(char)destinationIsGuestDevice:(id)arg1 ;
-(id)publicIdentityFromData:(id)arg1 ;
-(void)setRemoteUnauthenticatedPublicIdentity:(IDSMPPublicLegacyIdentity *)arg1 ;
-(void)setRemoteUseCloudPairedControlChannel:(NSNumber *)arg1 ;
-(void)setUseSecureQRControlMessage:(char)arg1 ;
-(char)disableRemoteDeviceEncryption;
-(char)useSecureQRControlMessage;
-(id)initWithDictionary:(id)arg1 serviceName:(id)arg2 isInitiator:(char)arg3 uniqueID:(id)arg4 accountID:(id)arg5 destinations:(id)arg6 ;
-(void)setIsScreenSharingSession:(char)arg1 ;
-(void)setEndSessionTimeout:(double)arg1 ;
-(void)setUseQRDirectly:(char)arg1 ;
-(void)setConnectionCountHint:(unsigned long long)arg1 ;
-(void)setUseBTDatagramPipe:(char)arg1 ;
-(void)setLocalBlob:(NSData *)arg1 ;
-(void)setLocalUnauthenticatedFullIdentity:(IDSMPFullLegacyIdentity *)arg1 ;
-(void)setEndSessionTimeoutTimer;
-(NSNumber *)remoteUseCloudPairedControlChannel;
-(IDSMPPublicLegacyIdentity *)remoteUnauthenticatedPublicIdentity;
-(NSDate *)startConnectingDate;
-(void)setForceInternetInvitation:(char)arg1 ;
-(char)encryptionInitialized;
-(unsigned)seqSend;
-(void)setLastPacketTime:(double)arg1 ;
-(NSArray *)pluginRequests;
-(char)supportsReinitiate;
-(void)setEnableSKE:(char)arg1 ;
-(void)_clearInvitationTimer;
-(void)_clearConnectionTimer;
-(void)_clearPacketLossTimer;
-(void)_clearEndSessionTimeoutTimer;
-(IMTimer *)inviteTimer;
-(void)setInviteTimer:(IMTimer *)arg1 ;
-(void)_inviteTimedOut;
-(AB)inviteTimerCleared;
-(IMTimer *)packetLossTimer;
-(IMTimer *)endSessionTimer;
-(void)setEndSessionTimer:(IMTimer *)arg1 ;
-(double)endSessionTimeout;
-(void)_endSessionTimedOut;
-(unsigned)invitationRetryCount;
-(AB)connectionTimerCleared;
-(void)setConnectionTimerCleared:(AB)arg1 ;
-(void)setEnableQuickRelay:(char)arg1 ;
-(void)setEnableSingleChannelDirectMode:(char)arg1 ;
-(AB)endSessionTimerCleared;
-(void)setEndSessionTimerCleared:(AB)arg1 ;
-(void)setInvitationRetryCount:(unsigned)arg1 ;
-(void)setInviteTimerCleared:(AB)arg1 ;
-(double)lastPacketTime;
-(void)setPacketLossTimer:(IMTimer *)arg1 ;
-(void)setPluginRequests:(NSArray *)arg1 ;
-(SCD_Struct_ID23*)encryptionStateStruct;
-(void)setEncryptionStateStruct:(SCD_Struct_ID23*)arg1 ;
@end

