/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/ENGroupContextObserverMiddleware.h>

@protocol IDSDGroupContextNotifyingObserverDelegate;
@class NSString;

@interface IDSDGroupContextNotifyingObserver : NSObject <ENGroupContextObserverMiddleware> {

	id<IDSDGroupContextNotifyingObserverDelegate> _delegate;

}

@property (nonatomic,retain) id<IDSDGroupContextNotifyingObserverDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(id<IDSDGroupContextNotifyingObserverDelegate>)delegate;
-(void)setDelegate:(id<IDSDGroupContextNotifyingObserverDelegate>)arg1 ;
-(id)initWithDelegate:(id)arg1 ;
-(void)groupContext:(id)arg1 didCreateGroup:(id)arg2 ;
-(void)groupContext:(id)arg1 didCacheGroup:(id)arg2 ;
-(void)groupContext:(id)arg1 didUpdateGroup:(id)arg2 withNewGroup:(id)arg3 ;
-(void)groupContext:(id)arg1 didReceiveDecryptionFailureForGroup:(id)arg2 ;
-(void)groupContextDidReceiveRegistrationIdentityUpdate:(id)arg1 ;
@end

