/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:00 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSXPCOpportunistic.h>

@class IDSXPCConnection, IDSOpportunisticCache, NSString;

@interface IDSDXPCOpportunistic : NSObject <IDSXPCOpportunistic> {

	IDSXPCConnection* _connection;
	IDSOpportunisticCache* _opportunisticCache;

}

@property (nonatomic,retain) IDSXPCConnection * connection;                           //@synthesize connection=_connection - In the implementation block
@property (nonatomic,retain) IDSOpportunisticCache * opportunisticCache;              //@synthesize opportunisticCache=_opportunisticCache - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(IDSXPCConnection *)connection;
-(void)setConnection:(IDSXPCConnection *)arg1 ;
-(void)copyOpportunisticCacheWithBlock:(/*^block*/id)arg1 ;
-(IDSOpportunisticCache *)opportunisticCache;
-(id)initWithQueue:(id)arg1 connection:(id)arg2 opportunisticCache:(id)arg3 ;
-(void)setOpportunisticCache:(IDSOpportunisticCache *)arg1 ;
@end

