/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:22 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSXPCListenerDelegate.h>
#import <libobjc.A.dylib/IDSDXPCDaemonCollaboratorProvider.h>

@protocol OS_dispatch_queue;
@class NSXPCListener, NSObject, NSMutableArray, IDSDXPCPairing, IDSDXPCPairedDeviceManager, NSString;

@interface IDSDXPCDaemonServer : NSObject <NSXPCListenerDelegate, IDSDXPCDaemonCollaboratorProvider> {

	NSXPCListener* _listener;
	NSObject*<OS_dispatch_queue> _queue;
	NSMutableArray* _daemonClients;
	IDSDXPCPairing* _pairingCollaborator;
	IDSDXPCPairedDeviceManager* _pairedDeviceManagerCollaborator;

}

@property (nonatomic,retain) NSXPCListener * listener;                                                  //@synthesize listener=_listener - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                                        //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSMutableArray * daemonClients;                                            //@synthesize daemonClients=_daemonClients - In the implementation block
@property (nonatomic,retain) IDSDXPCPairing * pairingCollaborator;                                      //@synthesize pairingCollaborator=_pairingCollaborator - In the implementation block
@property (nonatomic,retain) IDSDXPCPairedDeviceManager * pairedDeviceManagerCollaborator;              //@synthesize pairedDeviceManagerCollaborator=_pairedDeviceManagerCollaborator - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(char)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(NSXPCListener *)listener;
-(void)setListener:(NSXPCListener *)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)pairingCollaboratorForXPCDaemon:(id)arg1 ;
-(id)pairedDeviceManagerCollaboratorForXPCDaemon:(id)arg1 ;
-(id)reunionSyncCollaboratorWithClientProcessName:(id)arg1 forXPCDaemon:(id)arg2 ;
-(id)opportunisticCollaboratorForXPCDaemon:(id)arg1 ;
-(id)registrationCollaboratorForXPCDaemon:(id)arg1 ;
-(id)activityMonitorCollaboratorForXPCDaemon:(id)arg1 ;
-(id)internalTestingCollaboratorForXPCDaemon:(id)arg1 ;
-(id)initWithServiceName:(id)arg1 queue:(id)arg2 ;
-(NSMutableArray *)daemonClients;
-(IDSDXPCPairing *)pairingCollaborator;
-(IDSDXPCPairedDeviceManager *)pairedDeviceManagerCollaborator;
-(void)setDaemonClients:(NSMutableArray *)arg1 ;
-(void)setPairingCollaborator:(IDSDXPCPairing *)arg1 ;
-(void)setPairedDeviceManagerCollaborator:(IDSDXPCPairedDeviceManager *)arg1 ;
@end

