/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSCTAdapterListener.h>

@class NSString;

@interface IDSDaemonCapabilities : NSObject <IDSCTAdapterListener> {

	int _supportedServicesToken;

}

@property (assign,nonatomic) int supportedServicesToken;              //@synthesize supportedServicesToken=_supportedServicesToken - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(void)_updateCapabilities;
-(void)setSupportedServicesToken:(int)arg1 ;
-(int)supportedServicesToken;
-(void)carrierBundleInformationDidChange;
-(void)_setupTokens;
-(void)_listenForMGChanges;
-(void)_deferredUpdateCapabilities;
@end

