/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:20 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IDSDAccountMetrics : NSObject
+(char)isiCloudSignedIn;
+(char)isiTunesSignedIn;
+(char)isProductionEnvironment;
+(id)registrationAccountStatusMetricForAccount:(id)arg1 ;
+(id)registrationAccountStatusMetricForNonexistentAccountWithType:(int)arg1 serviceIdentifier:(id)arg2 ;
+(char)isAccountsFrameworkAvailable;
+(double)timeSinceDateOnAccount:(id)arg1 ;
+(char)isiCloudAccountMatchingAccount:(id)arg1 ;
+(double)timeSinceLastRegistrationFailureOnAccount:(id)arg1 ;
+(double)timeSinceLastRegistrationSuccessOnAccount:(id)arg1 ;
+(long long)accountSecurityLevelForAccount:(id)arg1 ;
+(char)areAllAliasesSelectedOnAccount:(id)arg1 ;
+(char)areAllSelectedAliasesRegisteredOnAccount:(id)arg1 ;
@end

