/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:00 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSDSessionIDSDSessionAWDMetrics;
@class NSDictionary, NSData, IDSDSessionMessenger, IDSDSessionSharedState;

@interface IDSDSessionInvitationManager : NSObject {

	unsigned char keyMaterial[60];
	char _remoteAssumeRemoteDeviceEncryption;
	char _useStunMICheck;
	unsigned _seqRecvStart;
	unsigned _SSRCRecv;
	unsigned _seqSendStart;
	unsigned _SSRCSend;
	id<IDSDSession><IDSDSessionAWDMetrics> _delegate;
	NSDictionary* _preferences;
	NSData* _quickRelaySessionToken;
	NSData* _remoteBlob;
	IDSDSessionMessenger* _messenger;
	IDSDSessionSharedState* _sharedState;

}

@property (nonatomic,retain) IDSDSessionMessenger * messenger;                                    //@synthesize messenger=_messenger - In the implementation block
@property (assign,nonatomic) char remoteAssumeRemoteDeviceEncryption;                             //@synthesize remoteAssumeRemoteDeviceEncryption=_remoteAssumeRemoteDeviceEncryption - In the implementation block
@property (assign,nonatomic) unsigned seqSendStart;                                               //@synthesize seqSendStart=_seqSendStart - In the implementation block
@property (nonatomic,retain) IDSDSessionSharedState * sharedState;                                //@synthesize sharedState=_sharedState - In the implementation block
@property (assign,setter=SRCSend,nonatomic) unsigned SSRCSend;                                    //@synthesize SSRCSend=_SSRCSend - In the implementation block
@property (assign,nonatomic) char useStunMICheck;                                                 //@synthesize useStunMICheck=_useStunMICheck - In the implementation block
@property (assign,nonatomic,__weak) id<IDSDSession><IDSDSessionAWDMetrics> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSDictionary * preferences;                                          //@synthesize preferences=_preferences - In the implementation block
@property (nonatomic,retain) NSData * quickRelaySessionToken;                                     //@synthesize quickRelaySessionToken=_quickRelaySessionToken - In the implementation block
@property (nonatomic,retain) NSData * remoteBlob;                                                 //@synthesize remoteBlob=_remoteBlob - In the implementation block
@property (assign,nonatomic) unsigned seqRecvStart;                                               //@synthesize seqRecvStart=_seqRecvStart - In the implementation block
@property (assign,setter=SRCRecv,nonatomic) unsigned SSRCRecv;                                    //@synthesize SSRCRecv=_SSRCRecv - In the implementation block
-(id<IDSDSession><IDSDSessionAWDMetrics>)delegate;
-(void)setDelegate:(id<IDSDSession><IDSDSessionAWDMetrics>)arg1 ;
-(NSDictionary *)preferences;
-(void)setPreferences:(NSDictionary *)arg1 ;
-(void)acceptInvitation;
-(void)cancelInvitation;
-(void)sendInvitationWithData:(id)arg1 declineOnError:(char)arg2 ;
-(void)cancelInvitationWithData:(id)arg1 ;
-(void)cancelInvitationWithRemoteEndedReasonOverride:(unsigned)arg1 ;
-(void)acceptInvitationWithData:(id)arg1 ;
-(void)declineInvitation;
-(void)declineInvitationWithData:(id)arg1 ;
-(char)_isValidDestination:(id)arg1 ;
-(IDSDSessionMessenger *)messenger;
-(void)setMessenger:(IDSDSessionMessenger *)arg1 ;
-(IDSDSessionSharedState *)sharedState;
-(void)setSharedState:(IDSDSessionSharedState *)arg1 ;
-(void)_sendInvitationWithOptions:(id)arg1 data:(id)arg2 declineOnError:(char)arg3 ;
-(void)_sendInvitationMessageToDestinations:(id)arg1 withOptions:(id)arg2 contextData:(id)arg3 declineOnError:(char)arg4 connectionData:(id)arg5 ;
-(void)_setLinkPreferences:(id)arg1 ;
-(NSData *)quickRelaySessionToken;
-(id)publicIdentityDataFromLocalFullIdentity;
-(void)setSSRCSend:(unsigned)arg1 ;
-(unsigned)SSRCSend;
-(void)setSeqSendStart:(unsigned)arg1 ;
-(unsigned)seqSendStart;
-(void)sendCancelInvitationToDestinations:(id)arg1 remoteEndReason:(unsigned)arg2 data:(id)arg3 ;
-(void)_sendCancelInvitationToDestinations:(id)arg1 withData:(id)arg2 ;
-(NSData *)remoteBlob;
-(void)_sendAcceptMessageWithContext:(id)arg1 connectionData:(id)arg2 ;
-(id)_acceptedDeviceUniqueID;
-(char)remoteAssumeRemoteDeviceEncryption;
-(char)useStunMICheck;
-(unsigned)SSRCRecv;
-(unsigned)seqRecvStart;
-(void)declineInvitationWithData:(id)arg1 forceFromID:(id)arg2 additionalMessageAttributes:(id)arg3 ;
-(void)setUseStunMICheck:(char)arg1 ;
-(void)setSSRCRecv:(unsigned)arg1 ;
-(void)setSeqRecvStart:(unsigned)arg1 ;
-(void)setRemoteBlob:(NSData *)arg1 ;
-(char)_isLocalDeviceSafeviewAdviserInitiatorOnLoboMacOrLaterAndRemoteDeviceIsPreTiboAnyPlatform;
-(id)initWithDictionary:(id)arg1 sharedState:(id)arg2 messenger:(id)arg3 ;
-(void)sendInvitationWithOptions:(id)arg1 declineOnError:(char)arg2 ;
-(id)_acceptedDeviceToken;
-(void)receivedAcceptMessage:(id)arg1 fromID:(id)arg2 ;
-(void)receivedDeclineMessage:(id)arg1 fromID:(id)arg2 ;
-(void)receivedCancelMessage:(id)arg1 fromID:(id)arg2 ;
-(void)setQuickRelaySessionToken:(NSData *)arg1 ;
-(void)setRemoteAssumeRemoteDeviceEncryption:(char)arg1 ;
@end

