/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:58 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@class CUTPromise;

@interface IDSDataMigrationTracker : NSObject {

	char _completedMigration;
	os_unfair_lock_s _lock;
	CUTPromise* _currentPromise;

}

@property (assign,nonatomic) char completedMigration;                  //@synthesize completedMigration=_completedMigration - In the implementation block
@property (nonatomic,retain) CUTPromise * currentPromise;              //@synthesize currentPromise=_currentPromise - In the implementation block
@property (assign,nonatomic) os_unfair_lock_s lock;                    //@synthesize lock=_lock - In the implementation block
+(id)sharedInstance;
-(id)init;
-(os_unfair_lock_s)lock;
-(void)setLock:(os_unfair_lock_s)arg1 ;
-(id)performMigrationIfNeeded;
-(char)hasPerformedMigration;
-(char)completedMigration;
-(void)setCompletedMigration:(char)arg1 ;
-(CUTPromise *)currentPromise;
-(void)setCurrentPromise:(CUTPromise *)arg1 ;
@end

