/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:19 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@class NSMutableDictionary, NSArray;

@interface IDSDMessageStoreMap : NSObject {

	opaque_pthread_mutex_t _mutex;
	NSMutableDictionary* _messageStores;

}

@property (copy,readonly) NSArray * messageStores; 
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(id)getOrCreateMessageStoreForDataProtectionClass:(unsigned)arg1 ;
-(NSArray *)messageStores;
@end

