/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/IDSPipelineComponent.h>

@class IDSEncryptionController;

@interface IDSEncryptionComponent : IDSPipelineComponent {

	IDSEncryptionController* _encryptionController;

}
-(id)runIndividuallyWithInput:(id)arg1 ;
-(char)_shouldIgnoreAutoBugCaptureForECFailure:(id)arg1 ;
-(id)initWithEncryptionController:(id)arg1 ;
-(char)shouldForwardErrorForEncryptionType:(long long)arg1 forceECC:(char)arg2 ;
-(char)_shouldAutoBugCaptureForECError:(id)arg1 ;
@end

