/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:03 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSPublicKeyStorage, IDSPeerIDManager, IDSDAccountController, IDSRegistrationKeyManager, IDSRateLimiter, IDSOTRController;

@interface IDSEncrypterBuilder : NSObject {

	char _avoidMainQueue;
	char _forceLegacy;
	IDSPublicKeyStorage* _publicKeyStorage;
	IDSPeerIDManager* _peerIDManager;
	IDSDAccountController* _accountController;
	IDSRegistrationKeyManager* _registrationKeyManager;
	IDSRateLimiter* _rateLimiter;
	IDSOTRController* _OTRController;

}

@property (nonatomic,retain) IDSPublicKeyStorage * publicKeyStorage;                          //@synthesize publicKeyStorage=_publicKeyStorage - In the implementation block
@property (nonatomic,retain) IDSPeerIDManager * peerIDManager;                                //@synthesize peerIDManager=_peerIDManager - In the implementation block
@property (nonatomic,retain) IDSDAccountController * accountController;                       //@synthesize accountController=_accountController - In the implementation block
@property (nonatomic,retain) IDSRegistrationKeyManager * registrationKeyManager;              //@synthesize registrationKeyManager=_registrationKeyManager - In the implementation block
@property (nonatomic,retain) IDSRateLimiter * rateLimiter;                                    //@synthesize rateLimiter=_rateLimiter - In the implementation block
@property (nonatomic,retain) IDSOTRController * OTRController;                                //@synthesize OTRController=_OTRController - In the implementation block
@property (assign,nonatomic) char avoidMainQueue;                                             //@synthesize avoidMainQueue=_avoidMainQueue - In the implementation block
@property (assign,nonatomic) char forceLegacy;                                                //@synthesize forceLegacy=_forceLegacy - In the implementation block
+(id)builderWithPublicKeyStorage:(id)arg1 peerIDManager:(id)arg2 accountController:(id)arg3 registrationKeyManager:(id)arg4 rateLimiter:(id)arg5 OTRController:(id)arg6 avoidMainQueue:(char)arg7 forceLegacy:(char)arg8 ;
-(IDSRateLimiter *)rateLimiter;
-(void)setRateLimiter:(IDSRateLimiter *)arg1 ;
-(IDSOTRController *)OTRController;
-(IDSDAccountController *)accountController;
-(void)setAccountController:(IDSDAccountController *)arg1 ;
-(IDSPeerIDManager *)peerIDManager;
-(void)setPeerIDManager:(IDSPeerIDManager *)arg1 ;
-(IDSRegistrationKeyManager *)registrationKeyManager;
-(id)initWithPublicKeyStorage:(id)arg1 peerIDManager:(id)arg2 accountController:(id)arg3 registrationKeyManager:(id)arg4 rateLimiter:(id)arg5 OTRController:(id)arg6 avoidMainQueue:(char)arg7 forceLegacy:(char)arg8 ;
-(id)_createHashingDeviceIdentityEncrypter;
-(char)forceLegacy;
-(void)setForceLegacy:(char)arg1 ;
-(id)encrypterWithLocalURI:(id)arg1 remoteURI:(id)arg2 pushToken:(id)arg3 service:(id)arg4 cert:(id)arg5 ;
-(id)encrypterWithDeviceID:(id)arg1 ;
-(id)encrypterWithEndpoint:(id)arg1 ;
-(id)encrypterWithOTRToken:(id)arg1 ;
-(IDSPublicKeyStorage *)publicKeyStorage;
-(void)setPublicKeyStorage:(IDSPublicKeyStorage *)arg1 ;
-(void)setRegistrationKeyManager:(IDSRegistrationKeyManager *)arg1 ;
-(void)setOTRController:(IDSOTRController *)arg1 ;
-(char)avoidMainQueue;
-(void)setAvoidMainQueue:(char)arg1 ;
@end

