/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSEncryptionQueue;

@interface IDSEncryptionQueueManager : NSObject {

	IDSEncryptionQueue* _syncQueue;
	IDSEncryptionQueue* _defaultQueue;
	IDSEncryptionQueue* _urgentQueue;

}

@property (nonatomic,retain) IDSEncryptionQueue * syncQueue;                 //@synthesize syncQueue=_syncQueue - In the implementation block
@property (nonatomic,retain) IDSEncryptionQueue * defaultQueue;              //@synthesize defaultQueue=_defaultQueue - In the implementation block
@property (nonatomic,retain) IDSEncryptionQueue * urgentQueue;               //@synthesize urgentQueue=_urgentQueue - In the implementation block
-(id)init;
-(IDSEncryptionQueue *)defaultQueue;
-(IDSEncryptionQueue *)syncQueue;
-(void)setSyncQueue:(IDSEncryptionQueue *)arg1 ;
-(id)_queueForPriority:(long long)arg1 ;
-(id)asyncQueueForPriority:(long long)arg1 ;
-(id)syncQueueForPriority:(long long)arg1 ;
-(void)setDefaultQueue:(IDSEncryptionQueue *)arg1 ;
-(IDSEncryptionQueue *)urgentQueue;
-(void)setUrgentQueue:(IDSEncryptionQueue *)arg1 ;
@end

