/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:22 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@interface IDSEntitlements : NSObject {

	SpecificEntitlement* _specificEntitlements;
	char** _shrunkenServiceIdentifiers;
	unsigned short _serviceIdentifierCount;
	unsigned char _specificEntitlementCount;

}
-(void)dealloc;
-(id)debugDescription;
-(id)dictionaryRepresentation;
-(char)hasEntitlement:(id)arg1 ;
-(id)initWithEntitlements:(id)arg1 ;
-(char)hasAnyEntitlements;
-(char)hasService:(id)arg1 forEntitlement:(id)arg2 ;
-(char)hasAnyEntitlementForService:(id)arg1 ;
@end

