/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:06 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IDSEncryptionHelpers : NSObject
+(void)logEncryptionErrorForToken:(id)arg1 deviceID:(id)arg2 forURI:(id)arg3 fromURI:(id)arg4 forService:(id)arg5 messageData:(id)arg6 type:(long long)arg7 encrypt:(char)arg8 remote:(char)arg9 priority:(long long)arg10 ;
+(id)encryptDataWithAESKey:(id)arg1 data:(id)arg2 ;
+(id)decryptDataWithAESKey:(id)arg1 data:(id)arg2 ;
+(id)encryptLocalDeliveryPayload:(id)arg1 toDevice:(id)arg2 forService:(id)arg3 withDataProtectionClass:(unsigned)arg4 encryptionType:(long long)arg5 priority:(long long)arg6 error:(long long*)arg7 ;
+(id)decryptLocalDeliveryPayload:(id)arg1 forService:(id)arg2 withDataProtectionClass:(unsigned)arg3 fromDevice:(id)arg4 encryptionType:(long long)arg5 priority:(long long)arg6 error:(id*)arg7 ;
+(char)areDataProtectionKeysAvailableForService:(id)arg1 withDataProtectionClass:(unsigned)arg2 fromDevice:(id)arg3 ;
@end

