/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSMutableSet, IDSPushHandler, IMLockdownManager, IDSDeviceHeartbeatCenter, FTNetworkSupport;

@interface IDSGetDependentRegistrationsCenter : NSObject {

	NSMutableDictionary* _currentGetDependentRegistrationBlocks;
	NSMutableSet* _currentGetDependentRegistrations;
	IDSPushHandler* _pushHandler;
	IMLockdownManager* _lockdownManager;
	IDSDeviceHeartbeatCenter* _heartbeatCenter;
	FTNetworkSupport* _ftNetworkSupport;
	/*^block*/id _sendMessageHandler;
	/*^block*/id _messageResponseHandler;

}
-(char)shouldReAuthenticateForGDRResultCode:(long long)arg1 retries:(unsigned)arg2 ;
-(char)getDependentRegistrations:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(id)initWithPushHandler:(id)arg1 lockdownManager:(id)arg2 heartbeatCenter:(id)arg3 ftNetworkSupport:(id)arg4 sendMessageHandlerBlock:(/*^block*/id)arg5 messageResponseHandlerBlock:(/*^block*/id)arg6 ;
-(void)_submitGDRReponseToAWDWithResultCode:(long long)arg1 error:(id)arg2 ;
-(char)_hasReachedMaxNumberOfRetries:(unsigned)arg1 ;
@end

