/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:10 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_nw_connection, OS_nw_service_connector, OS_nw_endpoint;
#import <identityservicesd/identityservicesd-Structs.h>
@class NSString, IDSGenericConnectionID, IDSSockAddrWrapperPair, NSError, IDSHCInfo, NSObject, IDSStallDetector, IDSConnectionContext;

@interface IDSGenericConnection : NSObject {

	NSString* _localConnectionGUID;
	NSString* _remoteConnectionGUID;
	NSString* _clientID;
	IDSGenericConnectionID* _connectionID;
	IDSSockAddrWrapperPair* _addressPair;
	int _protocol;
	int _sd;
	int _sdCopy;
	int _sdOriginal;
	int _sdNumberNoClose;
	NSError* _connectError;
	/*^block*/id _openSocketCompletionHandler;
	unsigned _firstIncomingSYNSequenceNumber;
	unsigned _expectedNextOutgoingSequenceNumber;
	unsigned _expectedNextIncomingSequenceNumber;
	int _stateFlags;
	double _creationTime;
	long long _priority;
	long long _socketTrafficClass;
	char _hasMoreData;
	double _lastSuccessfulSentTime;
	IDSHCInfo* _compressionInfo;
	long long _compressionState;
	char _suspended;
	NSObject*<OS_dispatch_queue> _completionQueue;
	unsigned _uint32Key;
	char _isCloudEnabled;
	char _isControlChannel;
	char _isDefaultPairedDevice;
	char _isRealTime;
	char _sentAWDReport;
	SCD_Struct_ID23* _encryptionState;
	char _encryptionEnabled;
	int _keyMaterialLength;
	char* _localKeyMaterial;
	unsigned _SSRCSend;
	unsigned _SSRCRecv;
	unsigned short _seqSendStart;
	unsigned short _seqRecvStart;
	unsigned short _seqSend;
	int _srtpProtocolVersion;
	unsigned long long _packetsReceived;
	unsigned long long _packetsSent;
	unsigned long long _bytesReceived;
	unsigned long long _bytesSent;
	double _connectionInitTime;
	double _firstPacketReceiveTime;
	double _firstDataPacketReceiveTime;
	NSString* _idsDeviceConnectionUUID;
	NSObject*<OS_nw_connection> _serviceConnection;
	NSObject*<OS_nw_service_connector> _serviceConnector;
	NSObject*<OS_nw_endpoint> _defaultPairedDeviceEndpoint;
	double _lastStallDetectLogTime;
	NSString* _outgoingStallDetectorName;
	IDSStallDetector* _outgoingStallDetector;
	IDSConnectionContext* _connectionContext;
	/*^block*/id _readHandler;
	char _shouldSetWhiteListUUIDForStreamingSocket;
	char _shouldStopBTDatagramLink;
	char _checksumFailed;
	char _didInvalidate;
	double _connectionSetupStartTime;

}

@property (assign,nonatomic) char didInvalidate;                                                 //@synthesize didInvalidate=_didInvalidate - In the implementation block
@property (nonatomic,retain,readonly) NSString * localConnectionGUID;                            //@synthesize localConnectionGUID=_localConnectionGUID - In the implementation block
@property (nonatomic,copy) NSString * remoteConnectionGUID;                                      //@synthesize remoteConnectionGUID=_remoteConnectionGUID - In the implementation block
@property (nonatomic,copy) NSString * clientID;                                                  //@synthesize clientID=_clientID - In the implementation block
@property (nonatomic,retain) IDSGenericConnectionID * connectionID;                              //@synthesize connectionID=_connectionID - In the implementation block
@property (nonatomic,copy) IDSSockAddrWrapperPair * addressPair;                                 //@synthesize addressPair=_addressPair - In the implementation block
@property (nonatomic,readonly) int protocol;                                                     //@synthesize protocol=_protocol - In the implementation block
@property (assign,nonatomic) int sd;                                                             //@synthesize sd=_sd - In the implementation block
@property (assign,nonatomic) int sdCopy;                                                         //@synthesize sdCopy=_sdCopy - In the implementation block
@property (assign,nonatomic) int sdOriginal;                                                     //@synthesize sdOriginal=_sdOriginal - In the implementation block
@property (assign,nonatomic) int sdNumberNoClose;                                                //@synthesize sdNumberNoClose=_sdNumberNoClose - In the implementation block
@property (nonatomic,retain) NSError * connectError;                                             //@synthesize connectError=_connectError - In the implementation block
@property (assign,nonatomic) NSObject*<OS_dispatch_queue> completionQueue; 
@property (nonatomic,copy) id openSocketCompletionHandler;                                       //@synthesize openSocketCompletionHandler=_openSocketCompletionHandler - In the implementation block
@property (assign,nonatomic) unsigned firstIncomingSYNSequenceNumber;                            //@synthesize firstIncomingSYNSequenceNumber=_firstIncomingSYNSequenceNumber - In the implementation block
@property (assign,nonatomic) unsigned expectedNextIncomingSequenceNumber;                        //@synthesize expectedNextIncomingSequenceNumber=_expectedNextIncomingSequenceNumber - In the implementation block
@property (assign,nonatomic) unsigned expectedNextOutgoingSequenceNumber;                        //@synthesize expectedNextOutgoingSequenceNumber=_expectedNextOutgoingSequenceNumber - In the implementation block
@property (assign,nonatomic) int stateFlags;                                                     //@synthesize stateFlags=_stateFlags - In the implementation block
@property (nonatomic,readonly) double creationTime;                                              //@synthesize creationTime=_creationTime - In the implementation block
@property (assign,nonatomic) long long priority;                                                 //@synthesize priority=_priority - In the implementation block
@property (assign,nonatomic) long long socketTrafficClass;                                       //@synthesize socketTrafficClass=_socketTrafficClass - In the implementation block
@property (assign,nonatomic) char hasMoreData;                                                   //@synthesize hasMoreData=_hasMoreData - In the implementation block
@property (assign,nonatomic) double lastSuccessfulSentTime;                                      //@synthesize lastSuccessfulSentTime=_lastSuccessfulSentTime - In the implementation block
@property (nonatomic,retain) IDSHCInfo * compressionInfo;                                        //@synthesize compressionInfo=_compressionInfo - In the implementation block
@property (assign,nonatomic) long long compressionState;                                         //@synthesize compressionState=_compressionState - In the implementation block
@property (assign,nonatomic) char suspended;                                                     //@synthesize suspended=_suspended - In the implementation block
@property (assign,nonatomic) unsigned uint32Key;                                                 //@synthesize uint32Key=_uint32Key - In the implementation block
@property (assign,nonatomic) char isCloudEnabled;                                                //@synthesize isCloudEnabled=_isCloudEnabled - In the implementation block
@property (assign,nonatomic) char isControlChannel;                                              //@synthesize isControlChannel=_isControlChannel - In the implementation block
@property (assign,nonatomic) char isDefaultPairedDevice;                                         //@synthesize isDefaultPairedDevice=_isDefaultPairedDevice - In the implementation block
@property (assign,nonatomic) char isRealTime;                                                    //@synthesize isRealTime=_isRealTime - In the implementation block
@property (assign,nonatomic) char shouldStopBTDatagramLink;                                      //@synthesize shouldStopBTDatagramLink=_shouldStopBTDatagramLink - In the implementation block
@property (assign,nonatomic) char encryptionEnabled;                                             //@synthesize encryptionEnabled=_encryptionEnabled - In the implementation block
@property (assign,nonatomic) int keyMaterialLength;                                              //@synthesize keyMaterialLength=_keyMaterialLength - In the implementation block
@property (assign,nonatomic) char* localKeyMaterial;                                             //@synthesize localKeyMaterial=_localKeyMaterial - In the implementation block
@property (assign,setter=SRCSend,nonatomic) unsigned SSRCSend;                                   //@synthesize SSRCSend=_SSRCSend - In the implementation block
@property (assign,setter=SRCRecv,nonatomic) unsigned SSRCRecv;                                   //@synthesize SSRCRecv=_SSRCRecv - In the implementation block
@property (assign,nonatomic) unsigned short seqSendStart;                                        //@synthesize seqSendStart=_seqSendStart - In the implementation block
@property (assign,nonatomic) unsigned short seqRecvStart;                                        //@synthesize seqRecvStart=_seqRecvStart - In the implementation block
@property (assign,nonatomic) unsigned short seqSend;                                             //@synthesize seqSend=_seqSend - In the implementation block
@property (assign,nonatomic) unsigned long long packetsReceived;                                 //@synthesize packetsReceived=_packetsReceived - In the implementation block
@property (assign,nonatomic) unsigned long long packetsSent;                                     //@synthesize packetsSent=_packetsSent - In the implementation block
@property (assign,nonatomic) unsigned long long bytesReceived;                                   //@synthesize bytesReceived=_bytesReceived - In the implementation block
@property (assign,nonatomic) unsigned long long bytesSent;                                       //@synthesize bytesSent=_bytesSent - In the implementation block
@property (assign,nonatomic) int srtpProtocolVersion;                                            //@synthesize srtpProtocolVersion=_srtpProtocolVersion - In the implementation block
@property (assign,nonatomic) char checksumFailed;                                                //@synthesize checksumFailed=_checksumFailed - In the implementation block
@property (assign,nonatomic) double connectionSetupStartTime;                                    //@synthesize connectionSetupStartTime=_connectionSetupStartTime - In the implementation block
@property (assign,nonatomic) double firstPacketReceiveTime;                                      //@synthesize firstPacketReceiveTime=_firstPacketReceiveTime - In the implementation block
@property (assign,nonatomic) double connectionInitTime;                                          //@synthesize connectionInitTime=_connectionInitTime - In the implementation block
@property (assign,nonatomic) double firstDataPacketReceiveTime;                                  //@synthesize firstDataPacketReceiveTime=_firstDataPacketReceiveTime - In the implementation block
@property (nonatomic,copy) NSString * idsDeviceConnectionUUID;                                   //@synthesize idsDeviceConnectionUUID=_idsDeviceConnectionUUID - In the implementation block
@property (nonatomic,retain) NSObject*<OS_nw_connection> serviceConnection;                      //@synthesize serviceConnection=_serviceConnection - In the implementation block
@property (nonatomic,retain) NSObject*<OS_nw_service_connector> serviceConnector;                //@synthesize serviceConnector=_serviceConnector - In the implementation block
@property (nonatomic,retain) NSObject*<OS_nw_endpoint> defaultPairedDeviceEndpoint;              //@synthesize defaultPairedDeviceEndpoint=_defaultPairedDeviceEndpoint - In the implementation block
@property (nonatomic,copy) NSString * outgoingStallDetectorName;                                 //@synthesize outgoingStallDetectorName=_outgoingStallDetectorName - In the implementation block
@property (nonatomic,retain) IDSStallDetector * outgoingStallDetector;                           //@synthesize outgoingStallDetector=_outgoingStallDetector - In the implementation block
@property (nonatomic,retain) IDSConnectionContext * connectionContext;                           //@synthesize connectionContext=_connectionContext - In the implementation block
@property (nonatomic,copy) id readHandler;                                                       //@synthesize readHandler=_readHandler - In the implementation block
@property (assign,nonatomic) char shouldSetWhiteListUUIDForStreamingSocket;                      //@synthesize shouldSetWhiteListUUIDForStreamingSocket=_shouldSetWhiteListUUIDForStreamingSocket - In the implementation block
-(void)dealloc;
-(id)description;
-(void)invalidate;
-(int)protocol;
-(void)setCompletionQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)completionQueue;
-(void)setSuspended:(char)arg1 ;
-(char)suspended;
-(void)setPriority:(long long)arg1 ;
-(long long)priority;
-(IDSGenericConnectionID *)connectionID;
-(char)hasMoreData;
-(NSString *)clientID;
-(void)setClientID:(NSString *)arg1 ;
-(NSObject*<OS_nw_connection>)serviceConnection;
-(void)setServiceConnection:(NSObject*<OS_nw_connection>)arg1 ;
-(char)isDefaultPairedDevice;
-(unsigned long long)bytesSent;
-(void)setReadHandler:(id)arg1 ;
-(void)setBytesSent:(unsigned long long)arg1 ;
-(unsigned long long)packetsSent;
-(unsigned long long)bytesReceived;
-(unsigned long long)packetsReceived;
-(double)creationTime;
-(SCD_Struct_ID23*)encryptionState;
-(void)setPacketsSent:(unsigned long long)arg1 ;
-(void)setBytesReceived:(unsigned long long)arg1 ;
-(void)setPacketsReceived:(unsigned long long)arg1 ;
-(void)setConnectionID:(IDSGenericConnectionID *)arg1 ;
-(char)didInvalidate;
-(void)setDidInvalidate:(char)arg1 ;
-(IDSConnectionContext *)connectionContext;
-(id)readHandler;
-(void)setEncryptionEnabled:(char)arg1 ;
-(void)setStateFlags:(int)arg1 ;
-(int)stateFlags;
-(void)setSSRCSend:(unsigned)arg1 ;
-(unsigned)SSRCSend;
-(void)setSeqSendStart:(unsigned short)arg1 ;
-(void)setSeqSend:(unsigned short)arg1 ;
-(unsigned short)seqSendStart;
-(unsigned)SSRCRecv;
-(unsigned short)seqRecvStart;
-(void)setSSRCRecv:(unsigned)arg1 ;
-(void)setSeqRecvStart:(unsigned short)arg1 ;
-(unsigned short)seqSend;
-(char)isCloudEnabled;
-(void)setIsDefaultPairedDevice:(char)arg1 ;
-(IDSStallDetector *)outgoingStallDetector;
-(void)setOutgoingStallDetector:(IDSStallDetector *)arg1 ;
-(NSObject*<OS_nw_service_connector>)serviceConnector;
-(void)setServiceConnector:(NSObject*<OS_nw_service_connector>)arg1 ;
-(void)_closeSockets;
-(void)_triggerStallDetectionLogsForDetector:(id)arg1 withEvent:(id)arg2 ;
-(id)initWithConnectionID:(id)arg1 protocol:(int)arg2 isCloudEnabled:(char)arg3 ;
-(id)initWithConnectionID:(id)arg1 protocol:(int)arg2 keyMaterialLength:(int)arg3 isCloudEnabled:(char)arg4 ;
-(id)flagsString;
-(id)initWithAddressPair:(id)arg1 protocol:(int)arg2 ;
-(void)reportToAWD:(unsigned long long)arg1 connectionType:(int)arg2 error:(int)arg3 ;
-(void)_createStallDetectorWithName:(id)arg1 ;
-(NSString *)localConnectionGUID;
-(NSString *)remoteConnectionGUID;
-(void)setRemoteConnectionGUID:(NSString *)arg1 ;
-(IDSSockAddrWrapperPair *)addressPair;
-(void)setAddressPair:(IDSSockAddrWrapperPair *)arg1 ;
-(int)sd;
-(void)setSd:(int)arg1 ;
-(int)sdCopy;
-(void)setSdCopy:(int)arg1 ;
-(int)sdOriginal;
-(void)setSdOriginal:(int)arg1 ;
-(int)sdNumberNoClose;
-(void)setSdNumberNoClose:(int)arg1 ;
-(NSError *)connectError;
-(void)setConnectError:(NSError *)arg1 ;
-(id)openSocketCompletionHandler;
-(void)setOpenSocketCompletionHandler:(id)arg1 ;
-(unsigned)firstIncomingSYNSequenceNumber;
-(void)setFirstIncomingSYNSequenceNumber:(unsigned)arg1 ;
-(unsigned)expectedNextOutgoingSequenceNumber;
-(void)setExpectedNextOutgoingSequenceNumber:(unsigned)arg1 ;
-(unsigned)expectedNextIncomingSequenceNumber;
-(void)setExpectedNextIncomingSequenceNumber:(unsigned)arg1 ;
-(long long)socketTrafficClass;
-(void)setSocketTrafficClass:(long long)arg1 ;
-(void)setHasMoreData:(char)arg1 ;
-(double)lastSuccessfulSentTime;
-(void)setLastSuccessfulSentTime:(double)arg1 ;
-(IDSHCInfo *)compressionInfo;
-(void)setCompressionInfo:(IDSHCInfo *)arg1 ;
-(long long)compressionState;
-(void)setCompressionState:(long long)arg1 ;
-(unsigned)uint32Key;
-(void)setUint32Key:(unsigned)arg1 ;
-(void)setIsCloudEnabled:(char)arg1 ;
-(char)isControlChannel;
-(void)setIsControlChannel:(char)arg1 ;
-(char)isRealTime;
-(void)setIsRealTime:(char)arg1 ;
-(char)shouldStopBTDatagramLink;
-(void)setShouldStopBTDatagramLink:(char)arg1 ;
-(char)encryptionEnabled;
-(int)keyMaterialLength;
-(void)setKeyMaterialLength:(int)arg1 ;
-(char*)localKeyMaterial;
-(void)setLocalKeyMaterial:(char*)arg1 ;
-(int)srtpProtocolVersion;
-(void)setSrtpProtocolVersion:(int)arg1 ;
-(char)checksumFailed;
-(void)setChecksumFailed:(char)arg1 ;
-(double)connectionInitTime;
-(void)setConnectionInitTime:(double)arg1 ;
-(double)firstDataPacketReceiveTime;
-(void)setFirstDataPacketReceiveTime:(double)arg1 ;
-(NSString *)idsDeviceConnectionUUID;
-(void)setIdsDeviceConnectionUUID:(NSString *)arg1 ;
-(double)connectionSetupStartTime;
-(void)setConnectionSetupStartTime:(double)arg1 ;
-(double)firstPacketReceiveTime;
-(void)setFirstPacketReceiveTime:(double)arg1 ;
-(void)setConnectionContext:(IDSConnectionContext *)arg1 ;
-(char)shouldSetWhiteListUUIDForStreamingSocket;
-(void)setShouldSetWhiteListUUIDForStreamingSocket:(char)arg1 ;
-(NSObject*<OS_nw_endpoint>)defaultPairedDeviceEndpoint;
-(void)setDefaultPairedDeviceEndpoint:(NSObject*<OS_nw_endpoint>)arg1 ;
-(NSString *)outgoingStallDetectorName;
-(void)setOutgoingStallDetectorName:(NSString *)arg1 ;
@end

