/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:13 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <FTServices/FTIDSMessage.h>

@class NSString, NSData, NSNumber, NSArray;

@interface IDSGroupGetMessage : FTIDSMessage {

	NSString* _hardwareVersion;
	NSString* _osVersion;
	NSString* _softwareVersion;
	NSString* _deviceName;
	NSData* _engramID;
	NSNumber* _version;
	NSArray* _responseEntries;
	NSNumber* _responseStatus;
	NSString* _responseMessage;

}

@property (copy) NSString * hardwareVersion;              //@synthesize hardwareVersion=_hardwareVersion - In the implementation block
@property (copy) NSString * osVersion;                    //@synthesize osVersion=_osVersion - In the implementation block
@property (copy) NSString * softwareVersion;              //@synthesize softwareVersion=_softwareVersion - In the implementation block
@property (copy) NSString * deviceName;                   //@synthesize deviceName=_deviceName - In the implementation block
@property (copy) NSData * engramID;                       //@synthesize engramID=_engramID - In the implementation block
@property (copy) NSNumber * version;                      //@synthesize version=_version - In the implementation block
@property (copy) NSArray * responseEntries;               //@synthesize responseEntries=_responseEntries - In the implementation block
@property (copy) NSNumber * responseStatus;               //@synthesize responseStatus=_responseStatus - In the implementation block
@property (copy) NSString * responseMessage;              //@synthesize responseMessage=_responseMessage - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSNumber *)version;
-(void)setVersion:(NSNumber *)arg1 ;
-(id)messageBody;
-(NSString *)deviceName;
-(NSString *)hardwareVersion;
-(void)setDeviceName:(NSString *)arg1 ;
-(NSString *)osVersion;
-(id)requiredKeys;
-(id)bagKey;
-(id)additionalMessageHeaders;
-(void)handleResponseDictionary:(id)arg1 ;
-(void)setOsVersion:(NSString *)arg1 ;
-(void)setHardwareVersion:(NSString *)arg1 ;
-(void)setResponseMessage:(NSString *)arg1 ;
-(NSNumber *)responseStatus;
-(void)setResponseStatus:(NSNumber *)arg1 ;
-(NSString *)softwareVersion;
-(void)setSoftwareVersion:(NSString *)arg1 ;
-(NSData *)engramID;
-(void)setEngramID:(NSData *)arg1 ;
-(NSString *)responseMessage;
-(NSArray *)responseEntries;
-(void)setResponseEntries:(NSArray *)arg1 ;
@end

