/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:23 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <IDSFoundation/IDSBaseMessage.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData, NSNumber, NSString;

@interface IDSInitializeValidationMessage : IDSBaseMessage <NSCopying> {

	NSData* _sessionInfoRequest;
	NSData* _responseSessionInfo;
	NSNumber* _responseTTL;
	NSData* _pushToken;
	NSString* _absintheUDID;
	NSData* _absintheHello;
	NSData* _responseAbsintheServKey;
	NSData* _responseAbsintheResponse;
	NSString* _responseDeviceScoreNonce;

}

@property (nonatomic,copy) NSData * pushToken;                               //@synthesize pushToken=_pushToken - In the implementation block
@property (nonatomic,copy) NSData * sessionInfoRequest;                      //@synthesize sessionInfoRequest=_sessionInfoRequest - In the implementation block
@property (nonatomic,copy) NSData * responseSessionInfo;                     //@synthesize responseSessionInfo=_responseSessionInfo - In the implementation block
@property (nonatomic,copy) NSNumber * responseTTL;                           //@synthesize responseTTL=_responseTTL - In the implementation block
@property (nonatomic,copy) NSString * absintheUDID;                          //@synthesize absintheUDID=_absintheUDID - In the implementation block
@property (nonatomic,copy) NSData * absintheHello;                           //@synthesize absintheHello=_absintheHello - In the implementation block
@property (nonatomic,copy) NSData * responseAbsintheServKey;                 //@synthesize responseAbsintheServKey=_responseAbsintheServKey - In the implementation block
@property (nonatomic,copy) NSData * responseAbsintheResponse;                //@synthesize responseAbsintheResponse=_responseAbsintheResponse - In the implementation block
@property (nonatomic,copy) NSString * responseDeviceScoreNonce;              //@synthesize responseDeviceScoreNonce=_responseDeviceScoreNonce - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)init;
-(long long)command;
-(id)messageBody;
-(NSData *)pushToken;
-(long long)responseCommand;
-(id)requiredKeys;
-(char)wantsHTTPHeaders;
-(char)wantsBinaryPush;
-(char)requiresPushTokenKeys;
-(char)wantsCompressedBody;
-(char)wantsBagKey;
-(double)anisetteHeadersTimeout;
-(void)setPushToken:(NSData *)arg1 ;
-(id)bagKey;
-(id)additionalMessageHeaders;
-(void)handleResponseDictionary:(id)arg1 ;
-(NSData *)sessionInfoRequest;
-(void)setSessionInfoRequest:(NSData *)arg1 ;
-(NSData *)responseSessionInfo;
-(NSNumber *)responseTTL;
-(NSData *)responseAbsintheServKey;
-(NSData *)responseAbsintheResponse;
-(NSString *)responseDeviceScoreNonce;
-(void)setAbsintheUDID:(NSString *)arg1 ;
-(void)setAbsintheHello:(NSData *)arg1 ;
-(NSString *)absintheUDID;
-(NSData *)absintheHello;
-(void)setResponseSessionInfo:(NSData *)arg1 ;
-(void)setResponseTTL:(NSNumber *)arg1 ;
-(void)setResponseAbsintheServKey:(NSData *)arg1 ;
-(void)setResponseAbsintheResponse:(NSData *)arg1 ;
-(void)setResponseDeviceScoreNonce:(NSString *)arg1 ;
@end

