/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSIDStatusDependencyProvider.h>

@protocol IDSIDStatusDependencyProvider <NSObject>
@required
-(double)currentTime;
-(id)currentDate;
-(id)newRemoteCredential;

@end


@class NSString;

@interface IDSIDStatusDependencyProvider : NSObject <IDSIDStatusDependencyProvider>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(double)currentTime;
-(id)currentDate;
-(id)newRemoteCredential;
@end

