/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:12 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <FTServices/FTIDSMessage.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSArray, NSString, NSDictionary;

@interface IDSIDQueryMessage : FTIDSMessage <NSCopying> {

	char _resultExpected;
	NSArray* _uris;
	NSString* _weight;
	NSDictionary* _responseIdentities;
	NSString* _requiredForMessaging;

}

@property (setter=setURIs:,copy) NSArray * uris;                 //@synthesize uris=_uris - In the implementation block
@property (copy) NSString * weight;                              //@synthesize weight=_weight - In the implementation block
@property (copy) NSDictionary * responseIdentities;              //@synthesize responseIdentities=_responseIdentities - In the implementation block
@property (copy) NSString * requiredForMessaging;                //@synthesize requiredForMessaging=_requiredForMessaging - In the implementation block
@property (assign) char resultExpected;                          //@synthesize resultExpected=_resultExpected - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)init;
-(NSString *)weight;
-(void)setWeight:(NSString *)arg1 ;
-(id)messageBody;
-(void)setURIs:(id)arg1 ;
-(id)requiredKeys;
-(char)requiresPushTokenKeys;
-(char)wantsHTTPGet;
-(char)allowDualDelivery;
-(char)wantsManagedRetries;
-(double)anisetteHeadersTimeout;
-(char)wantsBodySignature;
-(id)dataUsageBundleIdentifier;
-(char)hasRequiredKeys:(id*)arg1 ;
-(id)bagKey;
-(id)additionalMessageHeaders;
-(id)additionalQueryStringParameters;
-(void)handleResponseHeaders:(id)arg1 ;
-(void)handleResponseDictionary:(id)arg1 ;
-(NSArray *)uris;
-(char)resultExpected;
-(void)setRequiredForMessaging:(NSString *)arg1 ;
-(void)setResultExpected:(char)arg1 ;
-(NSDictionary *)responseIdentities;
-(void)setResponseIdentities:(NSDictionary *)arg1 ;
-(NSString *)requiredForMessaging;
@end

