/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:08 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData, NSString, NSNumber, NSDate, IDSSocketPairMessage, IDSProtobuf, NSDictionary, NSArray;

@interface IDSLocalDeliveryMessage : NSObject {

	NSData* _payload;
	NSString* _fromID;
	NSString* _topic;
	NSString* _awdTopic;
	NSString* _messageUUID;
	NSNumber* _domainHash;
	NSNumber* _command;
	NSString* _toDeviceID;
	NSString* _toURI;
	NSDate* _expirationDate;
	/*^block*/id _completionBlock;
	/*^block*/id _fallbackBlock;
	/*^block*/id _progressBlock;
	unsigned _messageID;
	double _timeEnqueued;
	double _timeSent;
	long long _priority;
	unsigned _dataProtectionClass;
	char _expectsPeerResponse;
	char _wantsAppAck;
	char _nonWaking;
	char _nonCloudWaking;
	char _requireBluetooth;
	char _requireLocalWiFi;
	char _compressPayload;
	char _compressed;
	char _didWakeHint;
	NSString* _peerResponseIdentifier;
	NSString* _queueOneIdentifier;
	IDSSocketPairMessage* _underlyingSocketPairMessage;
	char _isSending;
	char _fullyAckd;
	IDSProtobuf* _protobuf;
	unsigned long long _sentMessageDataSize;
	char _didFallback;
	NSString* _resourcePath;
	NSDictionary* _resourceMetadata;
	char _manualQueueRemoval;
	char _deniedToSend;
	char _shouldEnforceRemoteTimeout;
	NSArray* _duetIdentifiersOverride;
	char _bypassDuet;
	unsigned long long _minCompatibilityVersion;
	long long _messageType;
	long long _messageState;

}

@property (assign,nonatomic) long long priority;                                              //@synthesize priority=_priority - In the implementation block
@property (assign,nonatomic) unsigned dataProtectionClass;                                    //@synthesize dataProtectionClass=_dataProtectionClass - In the implementation block
@property (assign,nonatomic) char expectsPeerResponse;                                        //@synthesize expectsPeerResponse=_expectsPeerResponse - In the implementation block
@property (assign,nonatomic) char wantsAppAck;                                                //@synthesize wantsAppAck=_wantsAppAck - In the implementation block
@property (assign,nonatomic) char compressPayload;                                            //@synthesize compressPayload=_compressPayload - In the implementation block
@property (assign,nonatomic) char compressed;                                                 //@synthesize compressed=_compressed - In the implementation block
@property (assign,nonatomic) char didWakeHint;                                                //@synthesize didWakeHint=_didWakeHint - In the implementation block
@property (assign,nonatomic) char nonWaking;                                                  //@synthesize nonWaking=_nonWaking - In the implementation block
@property (assign,nonatomic) char nonCloudWaking;                                             //@synthesize nonCloudWaking=_nonCloudWaking - In the implementation block
@property (assign,nonatomic) char requireBluetooth;                                           //@synthesize requireBluetooth=_requireBluetooth - In the implementation block
@property (assign,nonatomic) char requireLocalWiFi;                                           //@synthesize requireLocalWiFi=_requireLocalWiFi - In the implementation block
@property (nonatomic,copy) NSString * queueOneIdentifier;                                     //@synthesize queueOneIdentifier=_queueOneIdentifier - In the implementation block
@property (nonatomic,copy) NSString * peerResponseIdentifier;                                 //@synthesize peerResponseIdentifier=_peerResponseIdentifier - In the implementation block
@property (nonatomic,copy) NSData * payload;                                                  //@synthesize payload=_payload - In the implementation block
@property (assign,nonatomic) unsigned messageID;                                              //@synthesize messageID=_messageID - In the implementation block
@property (assign,nonatomic) double timeEnqueued;                                             //@synthesize timeEnqueued=_timeEnqueued - In the implementation block
@property (assign,nonatomic) double timeSent;                                                 //@synthesize timeSent=_timeSent - In the implementation block
@property (nonatomic,copy) NSString * fromID;                                                 //@synthesize fromID=_fromID - In the implementation block
@property (nonatomic,copy) NSString * topic;                                                  //@synthesize topic=_topic - In the implementation block
@property (nonatomic,copy) NSString * awdTopic;                                               //@synthesize awdTopic=_awdTopic - In the implementation block
@property (nonatomic,copy) NSString * messageUUID;                                            //@synthesize messageUUID=_messageUUID - In the implementation block
@property (nonatomic,retain) NSDate * expirationDate;                                         //@synthesize expirationDate=_expirationDate - In the implementation block
@property (nonatomic,retain) NSNumber * domainHash;                                           //@synthesize domainHash=_domainHash - In the implementation block
@property (nonatomic,retain) NSNumber * command;                                              //@synthesize command=_command - In the implementation block
@property (nonatomic,retain) NSString * toDeviceID;                                           //@synthesize toDeviceID=_toDeviceID - In the implementation block
@property (nonatomic,retain) NSString * toURI;                                                //@synthesize toURI=_toURI - In the implementation block
@property (nonatomic,copy) id completionBlock;                                                //@synthesize completionBlock=_completionBlock - In the implementation block
@property (nonatomic,copy) id progressBlock;                                                  //@synthesize progressBlock=_progressBlock - In the implementation block
@property (nonatomic,copy) id fallbackBlock;                                                  //@synthesize fallbackBlock=_fallbackBlock - In the implementation block
@property (assign,nonatomic) char didFallback;                                                //@synthesize didFallback=_didFallback - In the implementation block
@property (assign,nonatomic) char deniedToSend;                                               //@synthesize deniedToSend=_deniedToSend - In the implementation block
@property (assign,nonatomic) char shouldEnforceRemoteTimeout;                                 //@synthesize shouldEnforceRemoteTimeout=_shouldEnforceRemoteTimeout - In the implementation block
@property (assign,nonatomic) unsigned long long sentMessageDataSize;                          //@synthesize sentMessageDataSize=_sentMessageDataSize - In the implementation block
@property (nonatomic,readonly) char isDoneSending;                                            //@synthesize fullyAckd=_fullyAckd - In the implementation block
@property (nonatomic,retain) IDSProtobuf * protobuf;                                          //@synthesize protobuf=_protobuf - In the implementation block
@property (nonatomic,retain) NSString * resourcePath;                                         //@synthesize resourcePath=_resourcePath - In the implementation block
@property (nonatomic,retain) NSDictionary * resourceMetadata;                                 //@synthesize resourceMetadata=_resourceMetadata - In the implementation block
@property (nonatomic,retain) NSArray * duetIdentifiersOverride;                               //@synthesize duetIdentifiersOverride=_duetIdentifiersOverride - In the implementation block
@property (assign,nonatomic) char bypassDuet;                                                 //@synthesize bypassDuet=_bypassDuet - In the implementation block
@property (assign,nonatomic) char manualQueueRemoval;                                         //@synthesize manualQueueRemoval=_manualQueueRemoval - In the implementation block
@property (assign,nonatomic) unsigned long long minCompatibilityVersion;                      //@synthesize minCompatibilityVersion=_minCompatibilityVersion - In the implementation block
@property (assign,nonatomic) long long messageType;                                           //@synthesize messageType=_messageType - In the implementation block
@property (nonatomic,readonly) long long messageState;                                        //@synthesize messageState=_messageState - In the implementation block
@property (nonatomic,retain) IDSSocketPairMessage * underlyingSocketPairMessage;              //@synthesize underlyingSocketPairMessage=_underlyingSocketPairMessage - In the implementation block
+(id)socketPairMessageWithCommand:(long long)arg1 streamID:(unsigned short)arg2 sequenceNumber:(unsigned)arg3 messageID:(unsigned)arg4 expectsPeerResponse:(char)arg5 wantsAppAck:(char)arg6 compressPayload:(char)arg7 compressed:(char)arg8 didWakeHint:(char)arg9 peerResponseIdentifier:(id)arg10 messageUUID:(id)arg11 payload:(id)arg12 protobuf:(id)arg13 resourcePath:(id)arg14 resourceMetadata:(id)arg15 expiryDate:(id)arg16 ;
+(unsigned char)_niceToSocketCommand:(long long)arg1 ;
-(id)init;
-(void)setProgressBlock:(id)arg1 ;
-(id)progressBlock;
-(NSString *)resourcePath;
-(id)completionBlock;
-(void)setCompletionBlock:(id)arg1 ;
-(NSDate *)expirationDate;
-(void)setExpirationDate:(NSDate *)arg1 ;
-(void)setPriority:(long long)arg1 ;
-(long long)priority;
-(NSNumber *)command;
-(NSString *)topic;
-(void)setPayload:(NSData *)arg1 ;
-(NSData *)payload;
-(void)setCommand:(NSNumber *)arg1 ;
-(void)setMessageType:(long long)arg1 ;
-(long long)messageType;
-(NSString *)messageUUID;
-(void)setTopic:(NSString *)arg1 ;
-(unsigned)dataProtectionClass;
-(double)timeSent;
-(void)setFromID:(NSString *)arg1 ;
-(void)setNonWaking:(char)arg1 ;
-(void)setWantsAppAck:(char)arg1 ;
-(void)setMessageUUID:(NSString *)arg1 ;
-(void)setCompressPayload:(char)arg1 ;
-(void)setRequireBluetooth:(char)arg1 ;
-(void)setRequireLocalWiFi:(char)arg1 ;
-(void)setExpectsPeerResponse:(char)arg1 ;
-(void)setPeerResponseIdentifier:(NSString *)arg1 ;
-(void)setBypassDuet:(char)arg1 ;
-(void)setNonCloudWaking:(char)arg1 ;
-(void)setQueueOneIdentifier:(NSString *)arg1 ;
-(void)setDuetIdentifiersOverride:(NSArray *)arg1 ;
-(void)setProtobuf:(IDSProtobuf *)arg1 ;
-(char)wantsAppAck;
-(NSString *)fromID;
-(unsigned long long)minCompatibilityVersion;
-(void)setDataProtectionClass:(unsigned)arg1 ;
-(char)expectsPeerResponse;
-(char)didWakeHint;
-(NSString *)peerResponseIdentifier;
-(char)compressed;
-(void)setCompressed:(char)arg1 ;
-(void)setDidWakeHint:(char)arg1 ;
-(IDSProtobuf *)protobuf;
-(void)setResourcePath:(NSString *)arg1 ;
-(void)setResourceMetadata:(NSDictionary *)arg1 ;
-(NSDictionary *)resourceMetadata;
-(NSString *)queueOneIdentifier;
-(NSArray *)duetIdentifiersOverride;
-(char)compressPayload;
-(char)requireBluetooth;
-(char)requireLocalWiFi;
-(char)bypassDuet;
-(char)nonWaking;
-(char)nonCloudWaking;
-(void)setTimeSent:(double)arg1 ;
-(unsigned)messageID;
-(void)setMessageID:(unsigned)arg1 ;
-(void)setFallbackBlock:(id)arg1 ;
-(id)fallbackBlock;
-(NSString *)toURI;
-(long long)messageState;
-(void)setMinCompatibilityVersion:(unsigned long long)arg1 ;
-(NSString *)toDeviceID;
-(NSNumber *)domainHash;
-(void)kickProgressBlock;
-(void)processAckForSocketPairMessage:(id)arg1 ;
-(id)socketPairMessage;
-(NSString *)awdTopic;
-(void)setAwdTopic:(NSString *)arg1 ;
-(void)setDomainHash:(NSNumber *)arg1 ;
-(void)setToDeviceID:(NSString *)arg1 ;
-(void)setToURI:(NSString *)arg1 ;
-(double)timeEnqueued;
-(void)setTimeEnqueued:(double)arg1 ;
-(char)isDoneSending;
-(unsigned long long)sentMessageDataSize;
-(void)setSentMessageDataSize:(unsigned long long)arg1 ;
-(char)didFallback;
-(void)setDidFallback:(char)arg1 ;
-(char)manualQueueRemoval;
-(void)setManualQueueRemoval:(char)arg1 ;
-(char)deniedToSend;
-(void)setDeniedToSend:(char)arg1 ;
-(char)shouldEnforceRemoteTimeout;
-(void)setShouldEnforceRemoteTimeout:(char)arg1 ;
-(IDSSocketPairMessage *)underlyingSocketPairMessage;
-(void)setUnderlyingSocketPairMessage:(IDSSocketPairMessage *)arg1 ;
@end

