/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:56 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/IDSMultiplexer.h>
#import <libobjc.A.dylib/IDSTransportLevelMultiplexer.h>

@protocol OS_nw_nexus;
@class NSObject, IDSTransportLevelAgent, NSMutableDictionary, NSMutableSet;

@interface IDSLocalMultiplexer : NSObject <IDSMultiplexer, IDSTransportLevelMultiplexer> {

	os_unfair_lock_s _lock;
	NSObject*<OS_nw_nexus> _nexus;
	IDSTransportLevelAgent* _agent;
	nexus_controllerRef _osNexusController;
	unsigned char _osNexusName[64];
	unsigned char _osNexusUUID[16];
	NSMutableDictionary* _clientUUIDs;
	NSMutableDictionary* _connections;
	NSMutableSet* _pendingConnections;
	NSMutableDictionary* _transports;
	NSMutableDictionary* _transportsInstances;
	unsigned char _nexusInstanceUUID[16];

}
+(id)sharedInstance;
-(id)init;
-(char)setupTransportForConnection:(id)arg1 ;
-(char)registerMultiplexerTransport:(id)arg1 ;
-(char)connectionRequest:(id)arg1 ;
-(char)connectionCancel:(id)arg1 ;
-(char)unregisterMultiplexerTransport:(id)arg1 ;
@end

