/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:12 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@class NSMutableDictionary;

@interface IDSLinkPreferencesManager : NSObject {

	opaque_pthread_mutex_t _preferencesLock;
	NSMutableDictionary* _servicesWithPreferences;

}
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(void)updateService:(id)arg1 withPreferences:(id)arg2 ;
-(void)resetPreferencesForAllServices;
-(id)accumulativePreferencesForAllServices;
-(char)_validatePreferences:(id)arg1 forService:(id)arg2 ;
-(id)preferencesForService:(id)arg1 ;
@end

