/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:56 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol IDSLink <NSObject>
@property (retain) NSString * cbuuid; 
@property (retain) NSString * deviceUniqueID; 
@property (getter=linkTypeString,readonly) NSString * linkTypeString; 
@property (readonly) unsigned long long state; 
@property (readonly) unsigned long long headerOverhead; 
@property (__weak) id<IDSLinkDelegate> delegate; 
@property (__weak) id<IDSLinkDelegate> alternateDelegate; 
@optional
-(void)start;

@required
-(id<IDSLinkDelegate>)delegate;
-(void)setDelegate:(id)arg1;
-(unsigned long long)state;
-(NSString *)cbuuid;
-(unsigned long long)headerOverhead;
-(unsigned long long)sendPacketBuffer:(/*function pointer*/void**)arg1 toDeviceUniqueID:(id)arg2 cbuuid:(id)arg3;
-(unsigned long long)sendPacketBufferArray:(*)arg1 arraySize:(int)arg2 toDeviceUniqueID:(id)arg3 cbuuid:(id)arg4;
-(id)generateLinkReport:(double)arg1 isCurrentLink:(char)arg2;
-(id)copyLinkStatsDict;
-(void)setCbuuid:(id)arg1;
-(NSString *)deviceUniqueID;
-(void)setDeviceUniqueID:(id)arg1;
-(NSString *)linkTypeString;
-(id<IDSLinkDelegate>)alternateDelegate;
-(void)setAlternateDelegate:(id)arg1;

@end

