/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:00 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSRegistrationKeyManager, IDSMessageHashStore;

@interface IDSMessageHashChecker : NSObject {

	char _usePairingKey;
	IDSRegistrationKeyManager* _registrationKeyManager;
	IDSMessageHashStore* _messageHashStore;

}

@property (assign,nonatomic) char usePairingKey;                                                //@synthesize usePairingKey=_usePairingKey - In the implementation block
@property (nonatomic,retain) IDSMessageHashStore * messageHashStore;                            //@synthesize messageHashStore=_messageHashStore - In the implementation block
@property (nonatomic,readonly) IDSRegistrationKeyManager * registrationKeyManager;              //@synthesize registrationKeyManager=_registrationKeyManager - In the implementation block
-(id)_legacyIdentity;
-(id)initWithRegistrationKeyManager:(id)arg1 messageHashStore:(id)arg2 usePairingKey:(char)arg3 ;
-(id)initWithRegistrationKeyManager:(id)arg1 ;
-(char)allowMessageData:(id)arg1 ;
-(char)allowMessageData:(id)arg1 withDelayedCommitBlock:(/*^block*/id*)arg2 ;
-(IDSRegistrationKeyManager *)registrationKeyManager;
-(char)usePairingKey;
-(void)setUsePairingKey:(char)arg1 ;
-(IDSMessageHashStore *)messageHashStore;
-(void)setMessageHashStore:(IDSMessageHashStore *)arg1 ;
@end

