/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:03 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSEncryptionController, IDSTransferServicesController;

@interface IDSMMCSUploader : NSObject {

	IDSEncryptionController* _encryptionController;
	IDSTransferServicesController* _transferServicesController;

}
-(id)initWithEncryptionController:(id)arg1 transferServicesController:(id)arg2 ;
-(id)uploadData:(id)arg1 toEndpoint:(id)arg2 onTopic:(id)arg3 forGUID:(id)arg4 encryptionType:(unsigned long long)arg5 ;
@end

