/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:18 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@interface IDSMacOSCertificateHandlers : NSObject
+(void)initialize;
+(id)errorForSecurityResultCode:(int)arg1 ;
+(id)csrForPublicKey:(SecKeyRef)arg1 privateKey:(SecKeyRef)arg2 commonName:(id)arg3 error:(id*)arg4 ;
+(id)generateCSRForPublicKey:(SecKeyRef)arg1 privateKey:(SecKeyRef)arg2 tpHandle:(long long)arg3 clHandle:(long long)arg4 subjectInfo:(id)arg5 error:(id*)arg6 ;
@end

