/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:59 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/IDSPipelineComponent.h>

@interface IDSMadridEndpointFilterComponent : IDSPipelineComponent
-(id)runIndividuallyWithInput:(id)arg1 ;
-(void)addTokenURI:(id)arg1 forProperty:(id)arg2 toRegistrationPropertyToDestinationsMap:(id)arg3 ;
@end

