/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSEncryptedData, NSNumber;

@interface IDSMMCSUploadResult : NSObject {

	IDSEncryptedData* _encryptedResult;
	NSNumber* _dataLength;
	/*^block*/id _fileCleanupBlock;

}

@property (nonatomic,readonly) IDSEncryptedData * encryptedResult;              //@synthesize encryptedResult=_encryptedResult - In the implementation block
@property (nonatomic,readonly) NSNumber * dataLength;                           //@synthesize dataLength=_dataLength - In the implementation block
@property (nonatomic,readonly) id fileCleanupBlock;                             //@synthesize fileCleanupBlock=_fileCleanupBlock - In the implementation block
-(NSNumber *)dataLength;
-(id)initWithEncryptedResult:(id)arg1 dataLength:(id)arg2 fileCleanupBlock:(/*^block*/id)arg3 ;
-(IDSEncryptedData *)encryptedResult;
-(id)fileCleanupBlock;
@end

