/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:22 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSMessageDeliveryFactory.h>

@protocol IDSMessageDeliveryFactory <NSObject>
@required
-(id)createHTTPMessageDelivery;
-(id)createAPNSMessageDelivery;

@end


@class NSString;

@interface IDSMessageDeliveryFactory : NSObject <IDSMessageDeliveryFactory>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedFactory;
-(id)createHTTPMessageDelivery;
-(id)createAPNSMessageDelivery;
@end

