/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:57 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IDSMessageMetricReporter : NSObject
+(id)errorToReportForECError:(id)arg1 ;
+(id)errorToReportForLegacyError:(id)arg1 ;
+(id)_metadataWithEndpoint:(id)arg1 ECSuccess:(id)arg2 legacySuccess:(id)arg3 ECError:(id)arg4 legacyError:(id)arg5 ;
+(char)_shouldIgnoreAutoBugCaptureForECFailure:(id)arg1 ;
+(char)_shouldIgnoreAutoBugCaptureForLegacyFailure:(id)arg1 ;
+(id)messageMetadataWithEndpoint:(id)arg1 ECSuccess:(id)arg2 legacySuccess:(id)arg3 ECError:(id)arg4 legacyError:(id)arg5 ;
+(void)reportEncryptionSideMetricWithEndpoint:(id)arg1 ECSuccess:(id)arg2 legacySuccess:(id)arg3 ECError:(id)arg4 legacyError:(id)arg5 ;
+(void)reportMessageMetricWithMetadata:(id)arg1 ECSuccess:(id)arg2 legacySuccess:(id)arg3 command:(id)arg4 decryptedEqual:(char)arg5 triedLastResort:(char)arg6 ECError:(id)arg7 legacyError:(id)arg8 fromDestination:(id)arg9 ;
+(void)noteKeyGenerationForMetric;
@end

