/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:56 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/IDSMultiplexerTransportClientConnection.h>

@protocol IDSMultiplexerTransport, OS_nw_path, OS_nw_parameters, OS_nw_endpoint;
@class NSArray, NSUUID, NSObject, NSString;

@interface IDSMultiplexerConnection : NSObject <IDSMultiplexerTransportClientConnection> {

	/*^block*/id _readHandler;
	char _invalidated;
	channelRef _osChannel;
	channel_ring_descRef _txRing;
	unsigned char _flowIDBytes[16];
	unsigned portsSignature;
	int _packetizationHeadroom;
	int _pid;
	id localIdentifier;
	id remoteIdentifier;
	id<IDSMultiplexerTransport> transport;
	NSArray* hostComponents;
	unsigned long long context;
	NSUUID* _clientUUID;
	NSObject*<OS_nw_path> _path;
	NSObject*<OS_nw_parameters> _parameters;
	NSObject*<OS_nw_endpoint> _localEndpoint;
	NSObject*<OS_nw_endpoint> _remoteEndpoint;
	NSUUID* _processUUID;

}

@property (assign,nonatomic) channelRef osChannel;                               //@synthesize osChannel=_osChannel - In the implementation block
@property (assign,nonatomic) channel_ring_descRef txRing;                        //@synthesize txRing=_txRing - In the implementation block
@property (assign,nonatomic) char invalidated;                                   //@synthesize invalidated=_invalidated - In the implementation block
@property (assign,nonatomic) int packetizationHeadroom;                          //@synthesize packetizationHeadroom=_packetizationHeadroom - In the implementation block
@property (copy) NSUUID * clientUUID;                                            //@synthesize clientUUID=_clientUUID - In the implementation block
@property (retain) NSObject*<OS_nw_path> path;                                   //@synthesize path=_path - In the implementation block
@property (retain) NSObject*<OS_nw_parameters> parameters;                       //@synthesize parameters=_parameters - In the implementation block
@property (retain) NSObject*<OS_nw_endpoint> localEndpoint;                      //@synthesize localEndpoint=_localEndpoint - In the implementation block
@property (retain) NSObject*<OS_nw_endpoint> remoteEndpoint;                     //@synthesize remoteEndpoint=_remoteEndpoint - In the implementation block
@property (assign) int pid;                                                      //@synthesize pid=_pid - In the implementation block
@property (retain) NSUUID * processUUID;                                         //@synthesize processUUID=_processUUID - In the implementation block
@property (nonatomic,retain) id<IDSMultiplexerTransport> transport; 
@property (nonatomic,retain) id localIdentifier; 
@property (nonatomic,retain) id remoteIdentifier; 
@property (nonatomic,retain) NSArray * hostComponents; 
@property (assign,nonatomic) unsigned portsSignature; 
@property (assign,nonatomic) unsigned long long context; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)multiplexerInstance;
-(NSString *)description;
-(void)invalidate;
-(NSObject*<OS_nw_path>)path;
-(void)setPath:(NSObject*<OS_nw_path>)arg1 ;
-(int)pid;
-(unsigned long long)context;
-(void)setContext:(unsigned long long)arg1 ;
-(NSObject*<OS_nw_parameters>)parameters;
-(void)setParameters:(NSObject*<OS_nw_parameters>)arg1 ;
-(void)setPid:(int)arg1 ;
-(id<IDSMultiplexerTransport>)transport;
-(void)setInvalidated:(char)arg1 ;
-(void)setTransport:(id<IDSMultiplexerTransport>)arg1 ;
-(char)invalidated;
-(NSUUID *)processUUID;
-(id)localIdentifier;
-(NSUUID *)clientUUID;
-(void)setClientUUID:(NSUUID *)arg1 ;
-(NSObject*<OS_nw_endpoint>)remoteEndpoint;
-(void)setRemoteEndpoint:(NSObject*<OS_nw_endpoint>)arg1 ;
-(NSObject*<OS_nw_endpoint>)localEndpoint;
-(void)setLocalEndpoint:(NSObject*<OS_nw_endpoint>)arg1 ;
-(id)remoteIdentifier;
-(void)setLocalIdentifier:(id)arg1 ;
-(channel_ring_descRef)txRing;
-(void)setTxRing:(channel_ring_descRef)arg1 ;
-(int)packetizationHeadroom;
-(void)setPacketBufferReadHandler:(/*^block*/id)arg1 ;
-(void)writePacketBuffer:(SCD_Struct_ID4*)arg1 ;
-(void)startReadOnTransportThread;
-(void)setRemoteIdentifier:(id)arg1 ;
-(NSArray *)hostComponents;
-(void)setHostComponents:(NSArray *)arg1 ;
-(unsigned)portsSignature;
-(void)setPortsSignature:(unsigned)arg1 ;
-(void)setPacketizationHeadroom:(int)arg1 ;
-(void)setProcessUUID:(NSUUID *)arg1 ;
-(channelRef)osChannel;
-(void)setOsChannel:(channelRef)arg1 ;
@end

