/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:22 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData, ENGroupID;

@interface IDSMPConversationGroupEntry : NSObject {

	NSData* _publicKeyData;
	NSData* _data;
	NSData* _signature;
	ENGroupID* _groupID;
	NSData* _forwardingTicket;

}

@property (nonatomic,retain) NSData * publicKeyData;                 //@synthesize publicKeyData=_publicKeyData - In the implementation block
@property (nonatomic,retain) NSData * data;                          //@synthesize data=_data - In the implementation block
@property (nonatomic,retain) NSData * signature;                     //@synthesize signature=_signature - In the implementation block
@property (nonatomic,retain) ENGroupID * groupID;                    //@synthesize groupID=_groupID - In the implementation block
@property (nonatomic,retain) NSData * forwardingTicket;              //@synthesize forwardingTicket=_forwardingTicket - In the implementation block
+(id)entryFromPublicDataRepresentation:(id)arg1 error:(id*)arg2 ;
-(id)description;
-(NSData *)data;
-(void)setData:(NSData *)arg1 ;
-(NSData *)signature;
-(void)setSignature:(NSData *)arg1 ;
-(ENGroupID *)groupID;
-(void)setGroupID:(ENGroupID *)arg1 ;
-(NSData *)publicKeyData;
-(NSData *)forwardingTicket;
-(id)publicDataRepresentationWithError:(id*)arg1 ;
-(void)setForwardingTicket:(NSData *)arg1 ;
-(id)initWithStableGroupID:(id)arg1 groupServerEntry:(id)arg2 ;
-(void)setPublicKeyData:(NSData *)arg1 ;
@end

