/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:19 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IDSNRDeviceManager : NSObject
+(id)copySharedDeviceManager;
-(void)disableDevice:(id)arg1 ;
-(void)registerDevice:(id)arg1 properties:(id)arg2 queue:(id)arg3 completionBlock:(/*^block*/id)arg4 ;
-(void)unregisterDevice:(id)arg1 ;
-(void)enableDevice:(id)arg1 ;
@end

