/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/IDSSocketPairConnectionProtocol.h>

@protocol OS_dispatch_queue, IDSSocketPairConnectionDelegate, OS_nw_connection;
@class NSSet, NSMutableArray, NSObject, NSMutableDictionary, NSString;

@interface IDSNWSocketPairConnection : NSObject <IDSSocketPairConnectionProtocol> {

	unsigned char _connectionID[16];
	double _lastSocketActivityTime;
	unsigned _sendMessageCounter;
	NSMutableArray* _outgoingMessageArray;
	os_unfair_lock_s _outgoingMessageArrayLock;
	unsigned char _loggingSequenceIncoming;
	unsigned char _loggingSequenceOutgoing;
	char _hasEndedSession;
	char _shouldUseCrossLayerLogging;
	unsigned _currentOutgoingFragmentedMessageID;
	unsigned _fragmentationSize;
	NSObject*<OS_dispatch_queue> _priorityQueue;
	id<IDSSocketPairConnectionDelegate> _delegate;
	long long _priority;
	NSObject*<OS_nw_connection> _nwConnection;
	NSMutableDictionary* _incomingDataFragments;
	/*^block*/id _encryptionBlock;
	/*^block*/id _decryptionBlock;
	NSString* _identifier;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> priorityQueue;                       //@synthesize priorityQueue=_priorityQueue - In the implementation block
@property (assign,nonatomic,__weak) id<IDSSocketPairConnectionDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) long long priority;                                               //@synthesize priority=_priority - In the implementation block
@property (nonatomic,retain) NSObject*<OS_nw_connection> nwConnection;                         //@synthesize nwConnection=_nwConnection - In the implementation block
@property (assign,nonatomic) unsigned currentOutgoingFragmentedMessageID;                      //@synthesize currentOutgoingFragmentedMessageID=_currentOutgoingFragmentedMessageID - In the implementation block
@property (assign,nonatomic) unsigned fragmentationSize;                                       //@synthesize fragmentationSize=_fragmentationSize - In the implementation block
@property (assign,nonatomic) unsigned char loggingSequenceIncoming;                            //@synthesize loggingSequenceIncoming=_loggingSequenceIncoming - In the implementation block
@property (assign,nonatomic) unsigned char loggingSequenceOutgoing;                            //@synthesize loggingSequenceOutgoing=_loggingSequenceOutgoing - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * incomingDataFragments;                      //@synthesize incomingDataFragments=_incomingDataFragments - In the implementation block
@property (nonatomic,copy) id encryptionBlock;                                                 //@synthesize encryptionBlock=_encryptionBlock - In the implementation block
@property (nonatomic,copy) id decryptionBlock;                                                 //@synthesize decryptionBlock=_decryptionBlock - In the implementation block
@property (nonatomic,retain) NSString * identifier;                                            //@synthesize identifier=_identifier - In the implementation block
@property (assign,nonatomic) char hasEndedSession;                                             //@synthesize hasEndedSession=_hasEndedSession - In the implementation block
@property (assign,nonatomic) char shouldUseCrossLayerLogging;                                  //@synthesize shouldUseCrossLayerLogging=_shouldUseCrossLayerLogging - In the implementation block
@property (nonatomic,readonly) NSSet * inFlightMessages; 
-(void)dealloc;
-(id<IDSSocketPairConnectionDelegate>)delegate;
-(void)setDelegate:(id<IDSSocketPairConnectionDelegate>)arg1 ;
-(NSString *)identifier;
-(void)start;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)setPriority:(long long)arg1 ;
-(long long)priority;
-(void)endSession;
-(NSObject*<OS_dispatch_queue>)priorityQueue;
-(NSObject*<OS_nw_connection>)nwConnection;
-(NSSet *)inFlightMessages;
-(void)setPriorityQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(double)lastSocketActivityTime;
-(id)initWithSocket:(int)arg1 queue:(id)arg2 delegate:(id)arg3 priority:(long long)arg4 identifier:(id)arg5 ;
-(void)setOTREncryptionBlock:(/*^block*/id)arg1 decryptionBlock:(/*^block*/id)arg2 ;
-(void)setFragmentationSize:(unsigned)arg1 ;
-(char)sendDataMessage:(id)arg1 canFragment:(char)arg2 ;
-(void)processStoredIncomingMessage:(id)arg1 ;
-(void)_notifyDelegateAboutClosedConnection;
-(void)setShouldUseCrossLayerLogging:(char)arg1 ;
-(void)_receiveFromNWConnection:(id)arg1 ;
-(char)hasEndedSession;
-(void)setHasEndedSession:(char)arg1 ;
-(void)_processIncomingRawMessage:(id)arg1 ;
-(char)shouldUseCrossLayerLogging;
-(unsigned char)loggingSequenceIncoming;
-(void)setLoggingSequenceIncoming:(unsigned char)arg1 ;
-(unsigned char)loggingSequenceOutgoing;
-(void)setLoggingSequenceOutgoing:(unsigned char)arg1 ;
-(void)_dequeueNextMessageFromOutgoingQueue;
-(void)_sendDataViaNWConnection:(id)arg1 isLargeTransfer:(char)arg2 ;
-(char)sendDataMessage:(id)arg1 ;
-(void)setNwConnection:(NSObject*<OS_nw_connection>)arg1 ;
-(unsigned)currentOutgoingFragmentedMessageID;
-(void)setCurrentOutgoingFragmentedMessageID:(unsigned)arg1 ;
-(unsigned)fragmentationSize;
-(NSMutableDictionary *)incomingDataFragments;
-(void)setIncomingDataFragments:(NSMutableDictionary *)arg1 ;
-(id)encryptionBlock;
-(void)setEncryptionBlock:(id)arg1 ;
-(id)decryptionBlock;
-(void)setDecryptionBlock:(id)arg1 ;
@end

