/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:19 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSNRDeviceIdentifier;

@interface IDSNRDeviceMonitor : NSObject {

	char _isRegistered;
	char _isEnabled;
	char _isNearby;
	char _isConnected;
	char _isAsleep;
	char _isClassCConnected;
	IDSNRDeviceIdentifier* _deviceIdentifier;

}

@property (nonatomic,readonly) IDSNRDeviceIdentifier * deviceIdentifier;              //@synthesize deviceIdentifier=_deviceIdentifier - In the implementation block
@property (nonatomic,readonly) char isRegistered;                                     //@synthesize isRegistered=_isRegistered - In the implementation block
@property (nonatomic,readonly) char isEnabled;                                        //@synthesize isEnabled=_isEnabled - In the implementation block
@property (nonatomic,readonly) char isNearby;                                         //@synthesize isNearby=_isNearby - In the implementation block
@property (nonatomic,readonly) char isConnected;                                      //@synthesize isConnected=_isConnected - In the implementation block
@property (nonatomic,readonly) char isAsleep;                                         //@synthesize isAsleep=_isAsleep - In the implementation block
@property (nonatomic,readonly) char isClassCConnected;                                //@synthesize isClassCConnected=_isClassCConnected - In the implementation block
-(id)init;
-(char)isEnabled;
-(char)isConnected;
-(IDSNRDeviceIdentifier *)deviceIdentifier;
-(char)isNearby;
-(char)isRegistered;
-(char)isAsleep;
-(char)isClassCConnected;
-(id)initWithDeviceIdentifier:(id)arg1 delegate:(id)arg2 queue:(id)arg3 ;
@end

