/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/CUTRTCMetric.h>

@class IDSNGMKeyLoadingErrorContainer, NSString, NSDictionary;

@interface IDSNGMKeyLoadingMetric : NSObject <CUTRTCMetric> {

	char _missingIdentity;
	char _missingPrekey;
	IDSNGMKeyLoadingErrorContainer* _errorContainer;

}

@property (nonatomic,readonly) char missingIdentity;                                         //@synthesize missingIdentity=_missingIdentity - In the implementation block
@property (nonatomic,readonly) char missingPrekey;                                           //@synthesize missingPrekey=_missingPrekey - In the implementation block
@property (nonatomic,readonly) IDSNGMKeyLoadingErrorContainer * errorContainer;              //@synthesize errorContainer=_errorContainer - In the implementation block
@property (nonatomic,readonly) NSString * name; 
@property (nonatomic,readonly) unsigned short rtcType; 
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)name;
-(NSDictionary *)dictionaryRepresentation;
-(unsigned short)rtcType;
-(id)initWithErrorContainer:(id)arg1 missingIdentity:(char)arg2 missingPrekey:(char)arg3 ;
-(IDSNGMKeyLoadingErrorContainer *)errorContainer;
-(char)missingPrekey;
-(char)missingIdentity;
@end

