/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:57 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, IDSKeychainWrapper, IDSFrequentURISuggester;

@interface IDSOpportunisticCache : NSObject {

	NSMutableDictionary* _keychainCache;
	long long _accessCount;
	IDSKeychainWrapper* _keychainWrapper;
	IDSFrequentURISuggester* _uriSuggester;

}

@property (nonatomic,retain) NSMutableDictionary * keychainCache;                 //@synthesize keychainCache=_keychainCache - In the implementation block
@property (assign,nonatomic) long long accessCount;                               //@synthesize accessCount=_accessCount - In the implementation block
@property (nonatomic,retain) IDSKeychainWrapper * keychainWrapper;                //@synthesize keychainWrapper=_keychainWrapper - In the implementation block
@property (nonatomic,retain) IDSFrequentURISuggester * uriSuggester;              //@synthesize uriSuggester=_uriSuggester - In the implementation block
-(id)description;
-(id)init;
-(long long)accessCount;
-(void)setAccessCount:(long long)arg1 ;
-(IDSKeychainWrapper *)keychainWrapper;
-(id)initWithKeychainWrapper:(id)arg1 uriSuggester:(id)arg2 ;
-(id)fetchOpportunisticCacheWithError:(id*)arg1 ;
-(char)saveOpportunisticCache:(id)arg1 withError:(id*)arg2 ;
-(void)mergeKeychainCacheIntoDictionary:(id)arg1 ;
-(void)limitDataInDictionary:(id)arg1 forService:(id)arg2 ;
-(void)selectServicesForKeychainCacheFromDictionary:(id)arg1 ;
-(void)mergeKeychainCacheDataIntoDictionary:(id)arg1 forService:(id)arg2 ;
-(void)syncCacheWithKeychain;
-(NSMutableDictionary *)keychainCache;
-(void)copyCacheWithBlock:(/*^block*/id)arg1 ;
-(char)clearKeychainWithError:(id*)arg1 ;
-(char)addData:(id)arg1 withError:(id*)arg2 ;
-(char)removeDataWithIdentifier:(id)arg1 serviceName:(id)arg2 withError:(id*)arg3 ;
-(id)selectDataForDestination:(id)arg1 ;
-(id)dataForService:(id)arg1 identifier:(id)arg2 ;
-(void)setKeychainCache:(NSMutableDictionary *)arg1 ;
-(void)setKeychainWrapper:(IDSKeychainWrapper *)arg1 ;
-(IDSFrequentURISuggester *)uriSuggester;
-(void)setUriSuggester:(IDSFrequentURISuggester *)arg1 ;
@end

