/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:18 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@class NSRecursiveLock, NSMutableDictionary;

@interface IDSOTRController : NSObject {

	NSRecursiveLock* _storageLock;
	NSMutableDictionary* _sessionStorage;
	opaque_pthread_mutex_t _lock;
	NSMutableDictionary* _sessionInfoToToken;
	NSMutableDictionary* _priorityToCompletionBlocks;
	NSMutableDictionary* _priorityToTimeoutBlocks;

}
+(id)sharedInstance;
-(id)init;
-(void)resumeSessionNegotiation;
-(id)copySessionObjectForToken:(id)arg1 ;
-(void)resetAllSessions;
-(void)removeAllCachedSessionsFromMainQueue;
-(void)suspendSessionNegotiation:(id)arg1 askedByPairedDevice:(char)arg2 ;
-(void)setSessionReady:(id)arg1 ;
-(void)startOTRNegotiationWithDeviceIfNeeded:(id)arg1 token:(id)arg2 reset:(char)arg3 errorHandler:(/*^block*/id)arg4 ;
-(void)addOTRSessionBlock:(unsigned char)arg1 sessionBlock:(/*^block*/id)arg2 key:(id)arg3 ;
-(char)isSessionReady:(id)arg1 ;
-(char)hasMessagableOTRSessionForToken:(id)arg1 ;
-(void)setOTRTestBlockFromCompletionBlock:(/*^block*/id)arg1 token:(id)arg2 ;
-(void)performOTRSessionBlock:(unsigned char)arg1 token:(id)arg2 ;
-(/*^block*/id)copyOTRTestBlock:(id)arg1 ;
-(void)setSessionNegotiationStart:(id)arg1 ;
-(unsigned)sessionNegotiationCount:(id)arg1 ;
-(void)_onQueueStartOTRNegotiationWithDeviceIfNeeded:(id)arg1 token:(id)arg2 reset:(char)arg3 errorHandler:(/*^block*/id)arg4 ;
-(void)setupNewSessionInfoWithToken:(id)arg1 ;
-(double)sessionStartTimeWithToken:(id)arg1 ;
-(void)setSessionNegotiationComplete:(id)arg1 ;
-(char)isSessionNegotiating:(id)arg1 ;
-(void)_reportOTRTestResult:(id)arg1 setupTime:(double)arg2 result:(unsigned char)arg3 ;
-(void)processNegotiationData:(id)arg1 deviceUniqueID:(id)arg2 token:(id)arg3 negotiationCount:(unsigned)arg4 ;
-(SecMPPublicIdentityRef)copyPairedDevicePublicIdentityWithDataProtectionClass:(unsigned)arg1 ;
-(void)_kickoffOTRNegotiationWithDevice:(id)arg1 token:(id)arg2 negotiationData:(id)arg3 ;
@end

