/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@class IDSPeerIDManager, IDSDAccountController, IDSPublicKeyStorageCache;

@interface IDSPublicKeyStorage : NSObject {

	IDSPeerIDManager* _peerIDManager;
	IDSDAccountController* _accountController;
	IDSPublicKeyStorageCache* _cache;
	opaque_pthread_mutex_t _lock;

}

@property (nonatomic,retain) IDSPeerIDManager * peerIDManager;                       //@synthesize peerIDManager=_peerIDManager - In the implementation block
@property (nonatomic,retain) IDSDAccountController * accountController;              //@synthesize accountController=_accountController - In the implementation block
@property (assign,nonatomic) opaque_pthread_mutex_t lock;                            //@synthesize lock=_lock - In the implementation block
@property (nonatomic,retain) IDSPublicKeyStorageCache * cache;                       //@synthesize cache=_cache - In the implementation block
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(opaque_pthread_mutex_t)lock;
-(IDSPublicKeyStorageCache *)cache;
-(void)setCache:(IDSPublicKeyStorageCache *)arg1 ;
-(void)setLock:(opaque_pthread_mutex_t)arg1 ;
-(void)clearCache;
-(IDSDAccountController *)accountController;
-(void)setAccountController:(IDSDAccountController *)arg1 ;
-(void)logState;
-(IDSPeerIDManager *)peerIDManager;
-(void)setPeerIDManager:(IDSPeerIDManager *)arg1 ;
-(id)publicDeviceIdentityContainerForDeviceID:(id)arg1 ;
-(id)initWithPeerIDManager:(id)arg1 accountController:(id)arg2 ;
-(void)_removeOldPersistence;
@end

