/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, IDSMPPublicDeviceIdentityContainer, NSData;

@interface IDSPublicKeyStorageCache : NSObject {

	NSString* _deviceID;
	IDSMPPublicDeviceIdentityContainer* _identity;
	NSData* _pushToken;

}

@property (nonatomic,retain) NSString * deviceID;                                        //@synthesize deviceID=_deviceID - In the implementation block
@property (nonatomic,retain) IDSMPPublicDeviceIdentityContainer * identity;              //@synthesize identity=_identity - In the implementation block
@property (nonatomic,retain) NSData * pushToken;                                         //@synthesize pushToken=_pushToken - In the implementation block
-(NSString *)deviceID;
-(IDSMPPublicDeviceIdentityContainer *)identity;
-(void)setDeviceID:(NSString *)arg1 ;
-(void)setIdentity:(IDSMPPublicDeviceIdentityContainer *)arg1 ;
-(NSData *)pushToken;
-(void)setPushToken:(NSData *)arg1 ;
-(void)clearCache;
-(void)logState;
-(id)cachedIdentityForDeviceID:(id)arg1 ;
-(void)cacheIdentity:(id)arg1 forDeviceID:(id)arg2 andPushToken:(id)arg3 ;
-(void)removeCachedIdentityForPushToken:(id)arg1 ;
@end

