/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:58 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <IDSFoundation/IDSMessage.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface IDSPendingOfflineMessageResponse : IDSMessage <NSCopying>
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)command;
@end

