/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:22 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSArray;

@interface IDSPreflightStack : NSObject <NSCopying> {

	NSString* _IMSI;
	NSString* _PLMN;
	NSArray* _validationMechanisms;

}

@property (nonatomic,readonly) NSArray * validationMechanisms;              //@synthesize validationMechanisms=_validationMechanisms - In the implementation block
@property (nonatomic,readonly) NSString * IMSI;                             //@synthesize IMSI=_IMSI - In the implementation block
@property (nonatomic,readonly) NSString * PLMN;                             //@synthesize PLMN=_PLMN - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSString *)PLMN;
-(NSString *)IMSI;
-(char)containsMechanisms;
-(char)matchesIMSI:(id)arg1 PLMN:(id)arg2 ;
-(id)topMechanism;
-(id)preflightStackByPoppingMechanism;
-(id)initWithIMSI:(id)arg1 PLMN:(id)arg2 validationMechanisms:(id)arg3 ;
-(NSArray *)validationMechanisms;
@end

