/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:19 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <identityservicesd/IDSPeerMessage.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface IDSPeerAccessoryMessage : IDSPeerMessage <NSCopying> {

	NSData* _accessToken;

}

@property (copy) NSData * accessToken;              //@synthesize accessToken=_accessToken - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)messageBody;
-(void)setAccessToken:(NSData *)arg1 ;
-(id)requiredKeys;
-(NSData *)accessToken;
@end

