/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:23 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData, NSString, NSNumber, NSDate;

@interface IDSPeerAggregatableMessage : NSObject <NSCopying> {

	char _wantsCertifiedDelivery;
	NSData* _targetToken;
	NSData* _targetSessionToken;
	NSString* _targetPeerID;
	NSString* _anonymizedSenderID;
	NSData* _encryptedData;
	NSNumber* _wantsDeliveryStatus;
	/*^block*/id _completionBlock;
	/*^block*/id _ackBlock;
	NSString* _encryptionType;
	NSData* _payloadMetadata;
	NSDate* _expirationDate;
	NSNumber* _dataLength;
	NSNumber* _command;

}

@property (copy) NSData * targetToken;                        //@synthesize targetToken=_targetToken - In the implementation block
@property (copy) NSData * targetSessionToken;                 //@synthesize targetSessionToken=_targetSessionToken - In the implementation block
@property (copy) NSString * targetPeerID;                     //@synthesize targetPeerID=_targetPeerID - In the implementation block
@property (copy) NSString * anonymizedSenderID;               //@synthesize anonymizedSenderID=_anonymizedSenderID - In the implementation block
@property (copy) NSData * encryptedData;                      //@synthesize encryptedData=_encryptedData - In the implementation block
@property (copy) NSNumber * wantsDeliveryStatus;              //@synthesize wantsDeliveryStatus=_wantsDeliveryStatus - In the implementation block
@property (assign) char wantsCertifiedDelivery;               //@synthesize wantsCertifiedDelivery=_wantsCertifiedDelivery - In the implementation block
@property (copy) NSString * encryptionType;                   //@synthesize encryptionType=_encryptionType - In the implementation block
@property (copy) NSData * payloadMetadata;                    //@synthesize payloadMetadata=_payloadMetadata - In the implementation block
@property (copy) NSDate * expirationDate;                     //@synthesize expirationDate=_expirationDate - In the implementation block
@property (copy) NSNumber * dataLength;                       //@synthesize dataLength=_dataLength - In the implementation block
@property (copy) NSNumber * command;                          //@synthesize command=_command - In the implementation block
@property (copy) id completionBlock;                          //@synthesize completionBlock=_completionBlock - In the implementation block
@property (copy) id ackBlock;                                 //@synthesize ackBlock=_ackBlock - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(id)completionBlock;
-(void)setCompletionBlock:(id)arg1 ;
-(NSDate *)expirationDate;
-(void)setExpirationDate:(NSDate *)arg1 ;
-(NSNumber *)command;
-(NSData *)encryptedData;
-(void)setEncryptedData:(NSData *)arg1 ;
-(void)setCommand:(NSNumber *)arg1 ;
-(void)setWantsDeliveryStatus:(NSNumber *)arg1 ;
-(void)setWantsCertifiedDelivery:(char)arg1 ;
-(NSNumber *)wantsDeliveryStatus;
-(char)wantsCertifiedDelivery;
-(void)setEncryptionType:(NSString *)arg1 ;
-(NSString *)encryptionType;
-(NSString *)anonymizedSenderID;
-(NSNumber *)dataLength;
-(void)setDataLength:(NSNumber *)arg1 ;
-(NSData *)targetToken;
-(NSString *)targetPeerID;
-(void)setTargetPeerID:(NSString *)arg1 ;
-(void)setTargetToken:(NSData *)arg1 ;
-(NSData *)targetSessionToken;
-(void)setTargetSessionToken:(NSData *)arg1 ;
-(void)setAckBlock:(id)arg1 ;
-(NSData *)payloadMetadata;
-(unsigned long long)sizeOfKeysWithValues;
-(id)ackBlock;
-(void)setAnonymizedSenderID:(NSString *)arg1 ;
-(void)setPayloadMetadata:(NSData *)arg1 ;
-(id)initWithTargetToken:(id)arg1 sessionToken:(id)arg2 targetPeerID:(id)arg3 encryptedData:(id)arg4 wantsDeliveryStatus:(char)arg5 wantsCertifiedDelivery:(char)arg6 ackBlock:(/*^block*/id)arg7 completionBlock:(/*^block*/id)arg8 ;
@end

