/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSPersistentMapPersister.h>

@protocol IDSPersistentMapPersister, IMUserDefaults;
@class NSString;

@interface IDSPersistentMigratingPersister : NSObject <IDSPersistentMapPersister> {

	char _migrated;
	id<IDSPersistentMapPersister> _originPersister;
	id<IDSPersistentMapPersister> _destinationPersister;
	NSString* _migrationDefaultKey;
	id<IMUserDefaults> _userDefaults;

}

@property (nonatomic,retain) id<IDSPersistentMapPersister> originPersister;                   //@synthesize originPersister=_originPersister - In the implementation block
@property (nonatomic,retain) id<IDSPersistentMapPersister> destinationPersister;              //@synthesize destinationPersister=_destinationPersister - In the implementation block
@property (assign,nonatomic) char migrated;                                                   //@synthesize migrated=_migrated - In the implementation block
@property (nonatomic,retain) NSString * migrationDefaultKey;                                  //@synthesize migrationDefaultKey=_migrationDefaultKey - In the implementation block
@property (nonatomic,retain) id<IMUserDefaults> userDefaults;                                 //@synthesize userDefaults=_userDefaults - In the implementation block
@property (nonatomic,readonly) NSString * identifier; 
@property (nonatomic,readonly) char isAvailable; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)description;
-(id)data;
-(NSString *)identifier;
-(char)isAvailable;
-(id<IMUserDefaults>)userDefaults;
-(void)setUserDefaults:(id<IMUserDefaults>)arg1 ;
-(char)migrated;
-(void)setMigrated:(char)arg1 ;
-(void)saveData:(id)arg1 ;
-(void)purgeData;
-(id)initWithOriginPersister:(id)arg1 destinationPersister:(id)arg2 userDefaults:(id)arg3 ;
-(id)initWithOriginPersister:(id)arg1 destinationPersister:(id)arg2 ;
-(id<IDSPersistentMapPersister>)originPersister;
-(void)setOriginPersister:(id<IDSPersistentMapPersister>)arg1 ;
-(id<IDSPersistentMapPersister>)destinationPersister;
-(void)setDestinationPersister:(id<IDSPersistentMapPersister>)arg1 ;
-(NSString *)migrationDefaultKey;
-(void)setMigrationDefaultKey:(NSString *)arg1 ;
@end

