/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:13 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <IDSFoundation/IDSMessage.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSNumber, NSDate, NSData, NSDictionary, NSMutableSet;

@interface IDSPeerAggregateMessage : IDSMessage <NSCopying> {

	char _fireAndForget;
	char _hasReceivedAPSDAck;
	char _isFinalMessage;
	NSString* _sourcePeerID;
	NSString* _encryptionType;
	NSString* _messageID;
	NSString* _targetService;
	NSNumber* _priority;
	NSDate* _expirationDate;
	NSData* _fromIdentity;
	NSDictionary* _additionalDictionary;
	NSMutableSet* _individualPeerMessages;
	NSMutableSet* _pendingResponseTokens;
	long long _maxSize;
	long long _currentSize;
	NSNumber* _chunkNumber;
	NSData* _groupPayload;
	NSData* _groupIdentifer;

}

@property (copy) NSString * sourcePeerID;                              //@synthesize sourcePeerID=_sourcePeerID - In the implementation block
@property (copy) NSString * encryptionType;                            //@synthesize encryptionType=_encryptionType - In the implementation block
@property (copy) NSString * messageID;                                 //@synthesize messageID=_messageID - In the implementation block
@property (copy) NSString * targetService;                             //@synthesize targetService=_targetService - In the implementation block
@property (copy) NSNumber * priority;                                  //@synthesize priority=_priority - In the implementation block
@property (copy) NSDate * expirationDate;                              //@synthesize expirationDate=_expirationDate - In the implementation block
@property (copy) NSData * fromIdentity;                                //@synthesize fromIdentity=_fromIdentity - In the implementation block
@property (copy) NSDictionary * additionalDictionary;                  //@synthesize additionalDictionary=_additionalDictionary - In the implementation block
@property (retain) NSMutableSet * individualPeerMessages;              //@synthesize individualPeerMessages=_individualPeerMessages - In the implementation block
@property (retain) NSMutableSet * pendingResponseTokens;               //@synthesize pendingResponseTokens=_pendingResponseTokens - In the implementation block
@property (assign) long long maxSize;                                  //@synthesize maxSize=_maxSize - In the implementation block
@property (assign) long long currentSize;                              //@synthesize currentSize=_currentSize - In the implementation block
@property (assign) char fireAndForget;                                 //@synthesize fireAndForget=_fireAndForget - In the implementation block
@property (assign) char hasReceivedAPSDAck;                            //@synthesize hasReceivedAPSDAck=_hasReceivedAPSDAck - In the implementation block
@property (copy) NSNumber * chunkNumber;                               //@synthesize chunkNumber=_chunkNumber - In the implementation block
@property (assign) char isFinalMessage;                                //@synthesize isFinalMessage=_isFinalMessage - In the implementation block
@property (nonatomic,copy) NSData * groupPayload;                      //@synthesize groupPayload=_groupPayload - In the implementation block
@property (nonatomic,copy) NSData * groupIdentifer;                    //@synthesize groupIdentifer=_groupIdentifer - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)init;
-(NSDate *)expirationDate;
-(void)setExpirationDate:(NSDate *)arg1 ;
-(long long)maxSize;
-(void)setPriority:(NSNumber *)arg1 ;
-(NSNumber *)priority;
-(void)setMaxSize:(long long)arg1 ;
-(id)messageBody;
-(void)setFireAndForget:(char)arg1 ;
-(id)requiredKeys;
-(void)setEncryptionType:(NSString *)arg1 ;
-(NSString *)encryptionType;
-(char)fireAndForget;
-(void)logFailureInfo;
-(NSString *)messageID;
-(long long)currentSize;
-(void)setMessageID:(NSString *)arg1 ;
-(void)noteResponseForToken:(id)arg1 ;
-(char)expectingMoreResponses;
-(NSString *)sourcePeerID;
-(void)setSourcePeerID:(NSString *)arg1 ;
-(void)setCurrentSize:(long long)arg1 ;
-(NSData *)fromIdentity;
-(void)setFromIdentity:(NSData *)arg1 ;
-(NSMutableSet *)individualPeerMessages;
-(NSNumber *)chunkNumber;
-(void)callAllIndividualCompletionBlocksWithDeliveryContext:(id)arg1 ;
-(NSDictionary *)additionalDictionary;
-(void)setAdditionalDictionary:(NSDictionary *)arg1 ;
-(id)initWithHighPriority:(char)arg1 ;
-(NSData *)groupPayload;
-(char)isFinalMessage;
-(void)callAllAckBlocks;
-(void)setChunkNumber:(NSNumber *)arg1 ;
-(void)setTargetService:(NSString *)arg1 ;
-(void)setHasReceivedAPSDAck:(char)arg1 ;
-(void)clearAllPendingResponseTokens;
-(char)hasReceivedAPSDAck;
-(NSString *)targetService;
-(id)_processMessageResponseForMessage:(id)arg1 withError:(id)arg2 resultCode:(long long)arg3 toURI:(id)arg4 fromURI:(id)arg5 service:(id)arg6 fromIdentity:(id)arg7 ;
-(void)setIndividualPeerMessages:(NSMutableSet *)arg1 ;
-(NSMutableSet *)pendingResponseTokens;
-(void)setPendingResponseTokens:(NSMutableSet *)arg1 ;
-(void)setIsFinalMessage:(char)arg1 ;
-(void)setGroupPayload:(NSData *)arg1 ;
-(NSData *)groupIdentifer;
-(void)setGroupIdentifer:(NSData *)arg1 ;
-(id)initWithPeerMessage:(id)arg1 service:(id)arg2 fromIdentity:(id)arg3 maxSize:(unsigned long long)arg4 ;
-(char)hasSpaceForAggregatableMessage:(id)arg1 ;
-(char)addAggregatableMessage:(id)arg1 ;
-(char)removeAllAggregatableMessages;
@end

