/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSPersistentMapPersister.h>

@class NSString, IDSKeychainWrapper, IMSystemMonitor;

@interface IDSPersistentMapKeychainPersister : NSObject <IDSPersistentMapPersister> {

	NSString* _identifier;
	IDSKeychainWrapper* _keychainWrapper;
	IMSystemMonitor* _systemMonitor;

}

@property (nonatomic,retain) NSString * identifier;                               //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,readonly) IDSKeychainWrapper * keychainWrapper;              //@synthesize keychainWrapper=_keychainWrapper - In the implementation block
@property (nonatomic,readonly) IMSystemMonitor * systemMonitor;                   //@synthesize systemMonitor=_systemMonitor - In the implementation block
@property (nonatomic,readonly) char isAvailable; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)data;
-(NSString *)identifier;
-(void)setIdentifier:(NSString *)arg1 ;
-(char)isAvailable;
-(IMSystemMonitor *)systemMonitor;
-(IDSKeychainWrapper *)keychainWrapper;
-(void)saveData:(id)arg1 ;
-(void)purgeData;
-(id)initWithIdentifier:(id)arg1 keychainWrapper:(id)arg2 systemMonitor:(id)arg3 ;
@end

