/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IDSPersistentMapMergePolicy : NSObject {

	/*^block*/id _block;
	unsigned long long _policy;

}

@property (nonatomic,copy) id block;                                 //@synthesize block=_block - In the implementation block
@property (assign,nonatomic) unsigned long long policy;              //@synthesize policy=_policy - In the implementation block
+(id)ditchMemoryPolicy;
+(id)prioritizeMemoryPolicy;
-(id)block;
-(unsigned long long)policy;
-(void)setPolicy:(unsigned long long)arg1 ;
-(void)setBlock:(id)arg1 ;
-(id)initWithStandardPolicy:(unsigned long long)arg1 ;
-(id)initWithPolicyBlock:(/*^block*/id)arg1 ;
-(id)processedDictionaryForDisk:(id)arg1 andMemory:(id)arg2 ;
@end

