/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:08 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSPipelineComponent.h>

@protocol IDSPipelineComponent
@required
-(id)runIndividuallyWithInput:(id)arg1;
-(id)runWithInput:(id)arg1;
-(id)bindTo:(id)arg1;

@end


@protocol IDSPipelineComponent;
@interface IDSPipelineComponent : NSObject <IDSPipelineComponent> {

	id<IDSPipelineComponent> _nextComponent;

}

@property (nonatomic,retain) id<IDSPipelineComponent> nextComponent;              //@synthesize nextComponent=_nextComponent - In the implementation block
+(id)pipelineFromComponents:(id)arg1 ;
-(id)runIndividuallyWithInput:(id)arg1 ;
-(id)runWithInput:(id)arg1 ;
-(id<IDSPipelineComponent>)nextComponent;
-(id)bindTo:(id)arg1 ;
-(void)setNextComponent:(id<IDSPipelineComponent>)arg1 ;
@end

