/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:06 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/IDSUser.h>

@class NSString;

@interface IDSPhoneUser : NSObject <NSCopying, IDSUser> {

	char _isDefaultUser;
	NSString* _phoneNumber;
	NSString* _phoneBookNumber;
	NSString* _labelID;
	NSString* _countryCode;
	NSString* _networkCode;

}

@property (nonatomic,retain) NSString * phoneNumber;                  //@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (nonatomic,retain) NSString * phoneBookNumber;              //@synthesize phoneBookNumber=_phoneBookNumber - In the implementation block
@property (assign,nonatomic) char isDefaultUser;                      //@synthesize isDefaultUser=_isDefaultUser - In the implementation block
@property (nonatomic,retain) NSString * countryCode;                  //@synthesize countryCode=_countryCode - In the implementation block
@property (nonatomic,retain) NSString * networkCode;                  //@synthesize networkCode=_networkCode - In the implementation block
@property (nonatomic,readonly) NSString * labelID;                    //@synthesize labelID=_labelID - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)supportsSecureCoding;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)countryCode;
-(id)uniqueIdentifier;
-(NSString *)phoneNumber;
-(char)isEqualToUser:(id)arg1 ;
-(void)setPhoneNumber:(NSString *)arg1 ;
-(long long)realm;
-(void)setCountryCode:(NSString *)arg1 ;
-(NSString *)phoneBookNumber;
-(NSString *)labelID;
-(id)storageIdentifier;
-(char)isDefaultUser;
-(id)unprefixedIdentifier;
-(id)realmPrefixedIdentifier;
-(void)setPhoneBookNumber:(NSString *)arg1 ;
-(void)setIsDefaultUser:(char)arg1 ;
-(void)setNetworkCode:(NSString *)arg1 ;
-(char)isEqualToPhoneUser:(id)arg1 ;
-(NSString *)networkCode;
-(id)initWithLabelID:(id)arg1 ;
-(id)initWithLabelID:(id)arg1 phoneBookNumber:(id)arg2 ;
-(char)shouldReplace:(id)arg1 ;
-(char)isIdenticalToUser:(id)arg1 ;
-(id)initWithLabelID:(id)arg1 phoneBookNumber:(id)arg2 isDefaultUser:(char)arg3 countryCode:(id)arg4 networkCode:(id)arg5 ;
-(id)phoneUserWithUpdatedPhoneNumber:(id)arg1 phoneBookNumber:(id)arg2 ;
-(id)phoneUserWithUpdatedPhoneNumber:(id)arg1 ;
-(id)phoneUserWithUpdatedDefaultUser:(char)arg1 countryCode:(id)arg2 networkCode:(id)arg3 ;
-(char)differsFromPhoneNumber:(id)arg1 ;
@end

