/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:02 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class IDSProtoKeyTransparencyLoggableData, NSString, NSMutableArray;

@interface IDSProtoKeyTransparencyTrustedService : PBCodable <NSCopying> {

	IDSProtoKeyTransparencyLoggableData* _ktLoggableData;
	NSString* _serviceIdentifier;
	NSMutableArray* _uris;

}

@property (nonatomic,readonly) char hasServiceIdentifier; 
@property (nonatomic,retain) NSString * serviceIdentifier;                                      //@synthesize serviceIdentifier=_serviceIdentifier - In the implementation block
@property (nonatomic,retain) NSMutableArray * uris;                                             //@synthesize uris=_uris - In the implementation block
@property (nonatomic,readonly) char hasKtLoggableData; 
@property (nonatomic,retain) IDSProtoKeyTransparencyLoggableData * ktLoggableData;              //@synthesize ktLoggableData=_ktLoggableData - In the implementation block
+(Class)urisType;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(NSString *)serviceIdentifier;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setServiceIdentifier:(NSString *)arg1 ;
-(char)hasServiceIdentifier;
-(NSMutableArray *)uris;
-(void)setUris:(NSMutableArray *)arg1 ;
-(void)addUris:(id)arg1 ;
-(unsigned long long)urisCount;
-(void)clearUris;
-(id)urisAtIndex:(unsigned long long)arg1 ;
-(void)setKtLoggableData:(IDSProtoKeyTransparencyLoggableData *)arg1 ;
-(char)hasKtLoggableData;
-(IDSProtoKeyTransparencyLoggableData *)ktLoggableData;
@end

