/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSUser;
@class IDSAuthenticationCertificate;

@interface IDSPhoneUserAuthenticationCertificate : NSObject {

	id<IDSUser> _phoneUser;
	IDSAuthenticationCertificate* _authenticationCertificate;

}

@property (nonatomic,readonly) id<IDSUser> phoneUser;                                                 //@synthesize phoneUser=_phoneUser - In the implementation block
@property (nonatomic,readonly) IDSAuthenticationCertificate * authenticationCertificate;              //@synthesize authenticationCertificate=_authenticationCertificate - In the implementation block
-(id)description;
-(IDSAuthenticationCertificate *)authenticationCertificate;
-(id<IDSUser>)phoneUser;
-(id)initWithPhoneUser:(id)arg1 authenticationCertificate:(id)arg2 ;
@end

