/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/IDSPhoneNumberValidationRequestor.h>

@protocol OS_dispatch_queue, IDSPhoneUserRegistryDeviceSupport;
@class NSObject, IDSUserStore, IDSServer, IDSPhoneNumberValidationStateMachine, NSString;

@interface IDSPhoneUserRegistry : NSObject <IDSPhoneNumberValidationRequestor> {

	NSObject*<OS_dispatch_queue> _queue;
	IDSUserStore* _userStore;
	IDSServer* _server;
	IDSPhoneNumberValidationStateMachine* _phoneNumberValidator;
	id<IDSPhoneUserRegistryDeviceSupport> _deviceSupport;

}

@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> queue;                                       //@synthesize queue=_queue - In the implementation block
@property (nonatomic,readonly) IDSUserStore * userStore;                                                 //@synthesize userStore=_userStore - In the implementation block
@property (nonatomic,readonly) IDSServer * server;                                                       //@synthesize server=_server - In the implementation block
@property (nonatomic,readonly) IDSPhoneNumberValidationStateMachine * phoneNumberValidator;              //@synthesize phoneNumberValidator=_phoneNumberValidator - In the implementation block
@property (nonatomic,readonly) id<IDSPhoneUserRegistryDeviceSupport> deviceSupport;                      //@synthesize deviceSupport=_deviceSupport - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSObject*<OS_dispatch_queue>)queue;
-(IDSServer *)server;
-(id<IDSPhoneUserRegistryDeviceSupport>)deviceSupport;
-(IDSUserStore *)userStore;
-(id)authenticatePhoneUser;
-(id)localPhoneAuthenticationCertificates;
-(SecKeyRef)phoneAuthenticationCertificatePublicKey;
-(SecKeyRef)phoneAuthenticationCertificatePrivateKey;
-(id)initWithQueue:(id)arg1 userStore:(id)arg2 ;
-(void)requestUserConsentToValidatePhoneNumberForCTPNR:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)initWithQueue:(id)arg1 userStore:(id)arg2 server:(id)arg3 phoneNumberValidator:(id)arg4 deviceSupport:(id)arg5 ;
-(id)initWithQueue:(id)arg1 userStore:(id)arg2 deviceSupport:(id)arg3 ;
-(id)phoneAuthenticationCertificateSigningRequestForUser:(id)arg1 ;
-(IDSPhoneNumberValidationStateMachine *)phoneNumberValidator;
@end

