/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:12 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSKVStore;

@interface IDSPublicIdentityCache : NSObject {

	IDSKVStore* _kvStore;

}
+(id)sharedInstance;
-(id)init;
-(id)initWithPath:(id)arg1 ;
-(char)cleanupWithError:(id*)arg1 ;
-(void)deleteCache;
-(char)addIdentity:(id)arg1 forToken:(id)arg2 uri:(id)arg3 service:(id)arg4 error:(id*)arg5 ;
-(id)identityForToken:(id)arg1 uri:(id)arg2 service:(id)arg3 error:(id*)arg4 ;
-(id)keyForToken:(id)arg1 uri:(id)arg2 service:(id)arg3 ;
-(char)addIdentityData:(id)arg1 forToken:(id)arg2 uri:(id)arg3 service:(id)arg4 error:(id*)arg5 ;
-(id)identityDataForToken:(id)arg1 uri:(id)arg2 service:(id)arg3 error:(id*)arg4 ;
@end

