/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:20 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject;

@interface IDSPeerIDManagerEndpointQueryListener : NSObject {

	/*^block*/id _queryCompletionBlock;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,readonly) id queryCompletionBlock;                         //@synthesize queryCompletionBlock=_queryCompletionBlock - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
-(NSObject*<OS_dispatch_queue>)queue;
-(id)queryCompletionBlock;
-(id)initWithQueryCompletionBlock:(/*^block*/id)arg1 queue:(id)arg2 ;
@end

