/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:59 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <FTServices/FTIDSMessage.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSNumber, NSArray;

@interface IDSPreflightMessage : FTIDSMessage <NSCopying> {

	NSString* _protocolVersion;
	NSNumber* _phoneNumberValidationRetryCount;
	NSString* _hardwareVersion;
	NSString* _osVersion;
	NSString* _softwareVersion;
	NSString* _deviceName;
	NSString* _IMSI;
	NSString* _PLMN;
	NSString* _testData;
	NSNumber* _pnrReason;
	NSNumber* _responseStatus;
	NSArray* _responseMechanisms;

}

@property (nonatomic,copy) NSString * protocolVersion;                              //@synthesize protocolVersion=_protocolVersion - In the implementation block
@property (nonatomic,copy) NSNumber * phoneNumberValidationRetryCount;              //@synthesize phoneNumberValidationRetryCount=_phoneNumberValidationRetryCount - In the implementation block
@property (nonatomic,copy) NSString * hardwareVersion;                              //@synthesize hardwareVersion=_hardwareVersion - In the implementation block
@property (nonatomic,copy) NSString * osVersion;                                    //@synthesize osVersion=_osVersion - In the implementation block
@property (nonatomic,copy) NSString * softwareVersion;                              //@synthesize softwareVersion=_softwareVersion - In the implementation block
@property (nonatomic,copy) NSString * deviceName;                                   //@synthesize deviceName=_deviceName - In the implementation block
@property (nonatomic,copy) NSString * IMSI;                                         //@synthesize IMSI=_IMSI - In the implementation block
@property (nonatomic,copy) NSString * PLMN;                                         //@synthesize PLMN=_PLMN - In the implementation block
@property (nonatomic,copy) NSString * testData;                                     //@synthesize testData=_testData - In the implementation block
@property (nonatomic,copy) NSNumber * pnrReason;                                    //@synthesize pnrReason=_pnrReason - In the implementation block
@property (nonatomic,copy) NSNumber * responseStatus;                               //@synthesize responseStatus=_responseStatus - In the implementation block
@property (nonatomic,copy) NSArray * responseMechanisms;                            //@synthesize responseMechanisms=_responseMechanisms - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)messageBody;
-(NSString *)deviceName;
-(NSString *)hardwareVersion;
-(void)setDeviceName:(NSString *)arg1 ;
-(NSString *)osVersion;
-(id)requiredKeys;
-(NSNumber *)pnrReason;
-(void)setPnrReason:(NSNumber *)arg1 ;
-(NSString *)PLMN;
-(NSString *)IMSI;
-(NSString *)protocolVersion;
-(char)requiresPushTokenKeys;
-(id)bagKey;
-(id)additionalMessageHeaders;
-(void)handleResponseDictionary:(id)arg1 ;
-(void)setProtocolVersion:(NSString *)arg1 ;
-(void)setOsVersion:(NSString *)arg1 ;
-(void)setIMSI:(NSString *)arg1 ;
-(void)setHardwareVersion:(NSString *)arg1 ;
-(NSNumber *)responseStatus;
-(void)setResponseStatus:(NSNumber *)arg1 ;
-(NSString *)softwareVersion;
-(void)setSoftwareVersion:(NSString *)arg1 ;
-(NSString *)testData;
-(void)setTestData:(NSString *)arg1 ;
-(void)setPLMN:(NSString *)arg1 ;
-(NSArray *)responseMechanisms;
-(void)setResponseMechanisms:(NSArray *)arg1 ;
-(NSNumber *)phoneNumberValidationRetryCount;
-(void)setPhoneNumberValidationRetryCount:(NSNumber *)arg1 ;
@end

