/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:18 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData, NSNumber;

@interface IDSPublicIdentityData : NSObject {

	NSData* _publicLegacyIdentityData;
	NSData* _publicNGMIdentityData;
	NSData* _publicNGMPrekeyData;
	NSNumber* _NGMVersion;

}

@property (nonatomic,readonly) NSData * publicLegacyIdentityData;              //@synthesize publicLegacyIdentityData=_publicLegacyIdentityData - In the implementation block
@property (nonatomic,readonly) NSData * publicNGMIdentityData;                 //@synthesize publicNGMIdentityData=_publicNGMIdentityData - In the implementation block
@property (nonatomic,readonly) NSData * publicNGMPrekeyData;                   //@synthesize publicNGMPrekeyData=_publicNGMPrekeyData - In the implementation block
@property (nonatomic,readonly) NSNumber * NGMVersion;                          //@synthesize NGMVersion=_NGMVersion - In the implementation block
-(id)initWithPublicLegacyIdentityData:(id)arg1 publicNGMIdentityData:(id)arg2 publicNGMPrekeyData:(id)arg3 NGMVersion:(id)arg4 ;
-(NSData *)publicLegacyIdentityData;
-(NSData *)publicNGMIdentityData;
-(NSData *)publicNGMPrekeyData;
-(NSNumber *)NGMVersion;
@end

