/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:24 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSServerBag;

@interface IDSQuickRelayAllocatorQueryPolicy : NSObject {

	IDSServerBag* _serverBag;

}

@property (nonatomic,readonly) IDSServerBag * serverBag;              //@synthesize serverBag=_serverBag - In the implementation block
-(IDSServerBag *)serverBag;
-(id)initWithServerBag:(id)arg1 ;
-(char)shouldQueryOnEveryQRAllocationForServiceIdentifier:(id)arg1 ;
-(char)_serverBagBoolForKey:(id)arg1 withDefaultValue:(char)arg2 ;
@end

