/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:21 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@interface IDSQuickSwitchHelper : NSObject {

	char _isQuickSwitchingToAnotherDevice;
	opaque_pthread_mutex_t _isQuickSwitchingMutex;

}
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(void)initiateQuickSwitchToDeviceWithCBUUID:(id)arg1 force:(char)arg2 completionBlock:(/*^block*/id)arg3 ;
-(void)resetCommunicationStateBeforeQuickSwitchWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)_setIsQuickSwitchingToAnotherDevice:(char)arg1 ;
-(void)_resetCommunicationStateBeforeQuickSwitchDeactivatePairedDevices:(char)arg1 withCompletionBlock:(/*^block*/id)arg2 ;
-(char)isQuickSwitchingToAnotherDevice;
@end

