/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSDAccountControllerDelegate.h>
#import <libobjc.A.dylib/IDSRegistrationControllerListener.h>
#import <libobjc.A.dylib/IDSDeviceCertificationRepairDelegate.h>
#import <libobjc.A.dylib/IDSCTAdapterListener.h>

@protocol OS_dispatch_queue;
@class IDSUserStore, NSObject, IDSRestoreMonitor, IDSSystemAccountAdapter, IDSCTAdapter, IDSDAccountController, IDSDServiceController, IDSRegistrationController, IDSSIMPhoneUserSynchronizer, IDSSystemAccountUserSynchronizer, IDSTemporaryPhoneUserSynchronizer, IDSUserAccountSynchronizer, IDSHeartbeatCenter, IDSRestrictions, IDSAccountSync, IDSAccountRepair, IDSDeviceCertificationRepair, IDSSIMResponder, NSString;

@interface IDSRegistrationConductor : NSObject <IDSDAccountControllerDelegate, IDSRegistrationControllerListener, IDSDeviceCertificationRepairDelegate, IDSCTAdapterListener> {

	IDSUserStore* _userStore;
	NSObject*<OS_dispatch_queue> _registrationQueue;
	IDSRestoreMonitor* _restoreMonitor;
	IDSSystemAccountAdapter* _systemAccountAdapter;
	IDSCTAdapter* _CTAdapter;
	IDSDAccountController* _accountController;
	IDSDServiceController* _serviceController;
	IDSRegistrationController* _registrationController;
	IDSSIMPhoneUserSynchronizer* _SIMPhoneUserSynchronizer;
	IDSSystemAccountUserSynchronizer* _systemAccountUserSynchronizer;
	IDSTemporaryPhoneUserSynchronizer* _temporaryPhoneUserSynchronizer;
	IDSUserAccountSynchronizer* _userAccountSynchronizer;
	IDSHeartbeatCenter* _heartbeatCenter;
	IDSRestrictions* _restrictions;
	IDSAccountSync* _accountSync;
	IDSAccountRepair* _accountRepair;
	IDSDeviceCertificationRepair* _deviceCertificationRepair;
	IDSSIMResponder* _SIMResponder;

}

@property (assign,nonatomic) char shouldSupressRepairLogic; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> registrationQueue;                                                     //@synthesize registrationQueue=_registrationQueue - In the implementation block
@property (nonatomic,retain) IDSRestoreMonitor * restoreMonitor;                                                                 //@synthesize restoreMonitor=_restoreMonitor - In the implementation block
@property (nonatomic,retain) IDSSystemAccountAdapter * systemAccountAdapter;                                                     //@synthesize systemAccountAdapter=_systemAccountAdapter - In the implementation block
@property (nonatomic,retain) IDSCTAdapter * CTAdapter;                                                                           //@synthesize CTAdapter=_CTAdapter - In the implementation block
@property (nonatomic,retain) IDSDAccountController * accountController;                                                          //@synthesize accountController=_accountController - In the implementation block
@property (nonatomic,retain) IDSDServiceController * serviceController;                                                          //@synthesize serviceController=_serviceController - In the implementation block
@property (nonatomic,retain) IDSRegistrationController * registrationController;                                                 //@synthesize registrationController=_registrationController - In the implementation block
@property (nonatomic,retain) IDSUserStore * userStore;                                                                           //@synthesize userStore=_userStore - In the implementation block
@property (setter=IMPhoneUserSynchronizer,nonatomic,retain) IDSSIMPhoneUserSynchronizer * SIMPhoneUserSynchronizer;              //@synthesize SIMPhoneUserSynchronizer=_SIMPhoneUserSynchronizer - In the implementation block
@property (nonatomic,retain) IDSSystemAccountUserSynchronizer * systemAccountUserSynchronizer;                                   //@synthesize systemAccountUserSynchronizer=_systemAccountUserSynchronizer - In the implementation block
@property (nonatomic,retain) IDSTemporaryPhoneUserSynchronizer * temporaryPhoneUserSynchronizer;                                 //@synthesize temporaryPhoneUserSynchronizer=_temporaryPhoneUserSynchronizer - In the implementation block
@property (nonatomic,retain) IDSUserAccountSynchronizer * userAccountSynchronizer;                                               //@synthesize userAccountSynchronizer=_userAccountSynchronizer - In the implementation block
@property (nonatomic,retain) IDSHeartbeatCenter * heartbeatCenter;                                                               //@synthesize heartbeatCenter=_heartbeatCenter - In the implementation block
@property (nonatomic,retain) IDSRestrictions * restrictions;                                                                     //@synthesize restrictions=_restrictions - In the implementation block
@property (nonatomic,retain) IDSAccountSync * accountSync;                                                                       //@synthesize accountSync=_accountSync - In the implementation block
@property (nonatomic,retain) IDSAccountRepair * accountRepair;                                                                   //@synthesize accountRepair=_accountRepair - In the implementation block
@property (nonatomic,retain) IDSDeviceCertificationRepair * deviceCertificationRepair;                                           //@synthesize deviceCertificationRepair=_deviceCertificationRepair - In the implementation block
@property (setter=IMResponder,nonatomic,retain) IDSSIMResponder * SIMResponder;                                                  //@synthesize SIMResponder=_SIMResponder - In the implementation block
+(char)enableHomeNumber;
+(char)shouldEnableHomeNumber;
-(id)init;
-(void)systemDidUnlock;
-(void)systemDidLeaveFirstDataProtectionLock;
-(IDSAccountSync *)accountSync;
-(void)setup;
-(IDSCTAdapter *)CTAdapter;
-(void)setCTAdapter:(IDSCTAdapter *)arg1 ;
-(void)setRestrictions:(IDSRestrictions *)arg1 ;
-(IDSRestrictions *)restrictions;
-(NSObject*<OS_dispatch_queue>)registrationQueue;
-(IDSDServiceController *)serviceController;
-(IDSDAccountController *)accountController;
-(void)setAccountController:(IDSDAccountController *)arg1 ;
-(IDSRegistrationController *)registrationController;
-(void)setServiceController:(IDSDServiceController *)arg1 ;
-(IDSUserStore *)userStore;
-(void)setUserStore:(IDSUserStore *)arg1 ;
-(void)setRegistrationQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)preferredAccountChanged:(id)arg1 ;
-(void)registrationController:(id)arg1 allRegistrationsSucceeded:(id)arg2 ;
-(char)shouldSupressRepairLogic;
-(void)registrationControllerNeedsNewRegistration:(id)arg1 ;
-(void)registrationController:(id)arg1 registrationUpdated:(id)arg2 ;
-(void)registrationController:(id)arg1 registrationWillStart:(id)arg2 ;
-(void)registrationController:(id)arg1 registrationFailed:(id)arg2 error:(long long)arg3 info:(id)arg4 ;
-(void)registrationController:(id)arg1 registrationSucceeded:(id)arg2 ;
-(void)registrationController:(id)arg1 deregistrationWillStart:(id)arg2 ;
-(void)setShouldSupressRepairLogic:(char)arg1 ;
-(void)kickiCloudRepair;
-(void)SIM:(id)arg1 didUpdateRegistrationState:(char)arg2 ;
-(void)carrierBundleInformationDidChange;
-(void)setRegistrationController:(IDSRegistrationController *)arg1 ;
-(void)accountControllerDidFinishLoadingAccounts:(id)arg1 ;
-(void)kickRepair;
-(IDSSystemAccountAdapter *)systemAccountAdapter;
-(void)setSystemAccountAdapter:(IDSSystemAccountAdapter *)arg1 ;
-(void)bagReloaded:(id)arg1 ;
-(void)serviceRestrictionsChanged:(id)arg1 ;
-(IDSAccountRepair *)accountRepair;
-(IDSDeviceCertificationRepair *)deviceCertificationRepair;
-(void)kickMissedTemporaryAlerts;
-(void)checkRestorationState;
-(IDSRestoreMonitor *)restoreMonitor;
-(void)setRestoreMonitor:(IDSRestoreMonitor *)arg1 ;
-(IDSSIMPhoneUserSynchronizer *)SIMPhoneUserSynchronizer;
-(void)setSIMPhoneUserSynchronizer:(IDSSIMPhoneUserSynchronizer *)arg1 ;
-(IDSSystemAccountUserSynchronizer *)systemAccountUserSynchronizer;
-(void)setSystemAccountUserSynchronizer:(IDSSystemAccountUserSynchronizer *)arg1 ;
-(IDSTemporaryPhoneUserSynchronizer *)temporaryPhoneUserSynchronizer;
-(void)setTemporaryPhoneUserSynchronizer:(IDSTemporaryPhoneUserSynchronizer *)arg1 ;
-(IDSUserAccountSynchronizer *)userAccountSynchronizer;
-(void)setUserAccountSynchronizer:(IDSUserAccountSynchronizer *)arg1 ;
-(IDSHeartbeatCenter *)heartbeatCenter;
-(void)setHeartbeatCenter:(IDSHeartbeatCenter *)arg1 ;
-(void)setAccountSync:(IDSAccountSync *)arg1 ;
-(void)setAccountRepair:(IDSAccountRepair *)arg1 ;
-(void)setDeviceCertificationRepair:(IDSDeviceCertificationRepair *)arg1 ;
-(IDSSIMResponder *)SIMResponder;
-(void)setSIMResponder:(IDSSIMResponder *)arg1 ;
-(void)forceRepairAccounts:(id)arg1 ;
-(void)deviceRecertificationCompleted:(id)arg1 ;
-(void)_setupRestoreTimer;
@end

