/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <FTServices/FTIDSMessage.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData, NSArray, NSString, NSDictionary, NSNumber;

@interface IDSRegistrationMessage : FTIDSMessage <NSCopying> {

	NSData* _validationData;
	NSArray* _responseServices;
	NSString* _language;
	NSArray* _services;
	NSString* _hardwareVersion;
	NSString* _osVersion;
	NSString* _softwareVersion;
	NSDictionary* _privateDeviceData;
	NSString* _deviceName;
	NSNumber* _responseHBI;
	NSData* _deviceScore;
	NSString* _deviceScoreNonce;

}

@property (copy) NSString * deviceName;                         //@synthesize deviceName=_deviceName - In the implementation block
@property (copy) NSString * language;                           //@synthesize language=_language - In the implementation block
@property (copy) NSString * hardwareVersion;                    //@synthesize hardwareVersion=_hardwareVersion - In the implementation block
@property (copy) NSString * osVersion;                          //@synthesize osVersion=_osVersion - In the implementation block
@property (copy) NSString * softwareVersion;                    //@synthesize softwareVersion=_softwareVersion - In the implementation block
@property (copy) NSDictionary * privateDeviceData;              //@synthesize privateDeviceData=_privateDeviceData - In the implementation block
@property (copy) NSArray * services;                            //@synthesize services=_services - In the implementation block
@property (copy) NSData * validationData;                       //@synthesize validationData=_validationData - In the implementation block
@property (copy) NSData * deviceScore;                          //@synthesize deviceScore=_deviceScore - In the implementation block
@property (copy) NSString * deviceScoreNonce;                   //@synthesize deviceScoreNonce=_deviceScoreNonce - In the implementation block
@property (copy) NSArray * responseServices;                    //@synthesize responseServices=_responseServices - In the implementation block
@property (copy) NSNumber * responseHBI;                        //@synthesize responseHBI=_responseHBI - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSArray *)services;
-(NSString *)language;
-(void)setLanguage:(NSString *)arg1 ;
-(id)messageBody;
-(NSString *)deviceName;
-(NSString *)hardwareVersion;
-(void)setDeviceName:(NSString *)arg1 ;
-(NSString *)osVersion;
-(void)setServices:(NSArray *)arg1 ;
-(id)requiredKeys;
-(char)requiresPushTokenKeys;
-(double)anisetteHeadersTimeout;
-(char)isMultipleAuthCertCapable;
-(char)hasRequiredKeys:(id*)arg1 ;
-(id)bagKey;
-(id)nonStandardMessageHeadersForOutgoingPush;
-(void)handleResponseDictionary:(id)arg1 ;
-(void)setOsVersion:(NSString *)arg1 ;
-(NSData *)validationData;
-(void)setValidationData:(NSData *)arg1 ;
-(void)setHardwareVersion:(NSString *)arg1 ;
-(NSString *)softwareVersion;
-(void)setSoftwareVersion:(NSString *)arg1 ;
-(NSDictionary *)privateDeviceData;
-(void)setPrivateDeviceData:(NSDictionary *)arg1 ;
-(NSData *)deviceScore;
-(void)setDeviceScore:(NSData *)arg1 ;
-(NSString *)deviceScoreNonce;
-(void)setDeviceScoreNonce:(NSString *)arg1 ;
-(NSArray *)responseServices;
-(void)setResponseServices:(NSArray *)arg1 ;
-(NSNumber *)responseHBI;
-(void)setResponseHBI:(NSNumber *)arg1 ;
@end

