/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSRapportDeliveryControllerRapportClient.h>
#import <libobjc.A.dylib/IDSTTLCacheDelegate.h>

@class RPCompanionLinkClient, NSMutableSet, NSHashTable, NSRecursiveLock, IDSTTLCache, IMMultiQueue, NSString;

@interface IDSRapportClient : NSObject <IDSRapportDeliveryControllerRapportClient, IDSTTLCacheDelegate> {

	RPCompanionLinkClient* _companionLinkClient;
	NSMutableSet* _discoveredDevices;
	NSHashTable* _delegateMap;
	NSRecursiveLock* _lock;
	IDSTTLCache* _ttlCache;
	IMMultiQueue* _multiQueue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) RPCompanionLinkClient * companionLinkClient;              //@synthesize companionLinkClient=_companionLinkClient - In the implementation block
@property (nonatomic,retain) IMMultiQueue * multiQueue;                                  //@synthesize multiQueue=_multiQueue - In the implementation block
@property (nonatomic,retain) IDSTTLCache * ttlCache;                                     //@synthesize ttlCache=_ttlCache - In the implementation block
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(void)removeDelegate:(id)arg1 ;
-(void)addDelegate:(id)arg1 ;
-(RPCompanionLinkClient *)companionLinkClient;
-(char)isDeviceDiscovered:(id)arg1 ;
-(void)sendMessage:(id)arg1 toDeviceIdentifier:(id)arg2 completionBlock:(/*^block*/id)arg3 ;
-(void)_notifyDelegatesWithBlock:(/*^block*/id)arg1 ;
-(IMMultiQueue *)multiQueue;
-(void)ttlCache:(id)arg1 willReturnCachedObject:(id)arg2 forKey:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)setMultiQueue:(IMMultiQueue *)arg1 ;
-(id)_newCompanionLinkClient;
-(void)_handleDiscoveredDevice:(id)arg1 ;
-(void)_handleLostDevice:(id)arg1 ;
-(void)_handleIncomingIDSMessageEvent:(id)arg1 options:(id)arg2 ;
-(void)_companionLinkClientForDeviceIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)_deviceWithIdentifier:(id)arg1 error:(id*)arg2 ;
-(char)_isDiscoveredOverWiFi:(id)arg1 ;
-(IDSTTLCache *)ttlCache;
-(void)setTtlCache:(IDSTTLCache *)arg1 ;
@end

