/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:01 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSRegistrationCenterListener
@optional
-(void)center:(id)arg1 succeededIDSAuthentication:(id)arg2;
-(void)center:(id)arg1 failedIDSAuthentication:(id)arg2 error:(long long)arg3 info:(id)arg4;
-(void)center:(id)arg1 succeededRegistration:(id)arg2;
-(void)center:(id)arg1 failedRegistration:(id)arg2 error:(long long)arg3 info:(id)arg4;
-(void)center:(id)arg1 allSucceededRegistrations:(id)arg2;
-(void)center:(id)arg1 succeededCurrentEmailsRequest:(id)arg2 emailInfo:(id)arg3;
-(void)center:(id)arg1 failedCurrentEmailsRequest:(id)arg2 error:(long long)arg3 info:(id)arg4;
-(void)centerUpdatedRegistrationIdentities:(id)arg1;

@end

