/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSRegistrationControllerListener
@required
-(void)registrationController:(id)arg1 allRegistrationsSucceeded:(id)arg2;
-(void)registrationControllerNeedsNewRegistration:(id)arg1;
-(void)registrationController:(id)arg1 registrationUpdated:(id)arg2;
-(void)registrationController:(id)arg1 registrationWillStart:(id)arg2;
-(void)registrationController:(id)arg1 registrationFailed:(id)arg2 error:(long long)arg3 info:(id)arg4;
-(void)registrationController:(id)arg1 registrationSucceeded:(id)arg2;
-(void)registrationController:(id)arg1 deregistrationWillStart:(id)arg2;

@end

