/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:02 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSRapportDeliveryControllerDelegate <NSObject>
@optional
-(void)deliveryController:(id)arg1 didReceiveMessage:(id)arg2 topic:(id)arg3 command:(id)arg4 deviceID:(id)arg5 messageID:(id)arg6;

@end

