/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:10 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/IDSRapportClientDelegate.h>

@protocol IDSRapportDeliveryControllerDelegate;
@class IDSRapportClient, NSString;

@interface IDSRapportDeliveryController : NSObject <IDSRapportClientDelegate> {

	opaque_pthread_mutex_t _discoveredDeviceIDsLock;
	unsigned _messageID;
	id<IDSRapportDeliveryControllerDelegate> _delegate;
	IDSRapportClient* _rapportClient;

}

@property (nonatomic,retain) id<IDSRapportDeliveryControllerRapportClient> rapportClient;              //@synthesize rapportClient=_rapportClient - In the implementation block
@property (assign,nonatomic,__weak) id<IDSRapportDeliveryControllerDelegate> delegate;                 //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(id<IDSRapportDeliveryControllerDelegate>)delegate;
-(void)setDelegate:(id<IDSRapportDeliveryControllerDelegate>)arg1 ;
-(id<IDSRapportDeliveryControllerRapportClient>)rapportClient;
-(unsigned)_nextMessageID;
-(void)rapportClient:(id)arg1 didReceiveMessage:(id)arg2 fromID:(id)arg3 ;
-(id)initWithRapportClient:(id)arg1 ;
-(void)sendMessage:(id)arg1 messageID:(id)arg2 topic:(id)arg3 command:(id)arg4 destinationIDs:(id)arg5 completionBlock:(/*^block*/id)arg6 ;
-(void)setRapportClient:(id<IDSRapportDeliveryControllerRapportClient>)arg1 ;
@end

