/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:21 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol FTPasswordManager;
@class NSArray, NSString, NSNumber, NSDate, NSData, NSDictionary, NSMutableArray;

@interface IDSRegistration : NSObject <NSCopying> {

	char _needsMigration;
	char _needsProvisioning;
	char _needsRenewal;
	char _runningSimpleAuthentication;
	char _isDisabled;
	char _shouldRegisterUsingDSHandle;
	char _shouldAutoRegisterAllHandles;
	int _registrationType;
	int _retries;
	int _absintheRetries;
	NSArray* _vettedEmails;
	NSString* _dsHandle;
	NSString* _profileID;
	NSNumber* _IDSVersion;
	NSNumber* _applicationVersion;
	NSString* _environment;
	NSDate* _registrationDate;
	NSDate* _nextRegistrationDate;
	NSData* _pushToken;
	NSNumber* _isC2K;
	long long _registrationStatus;
	NSString* _mainID;
	NSArray* _dependentRegistrations;
	NSString* _regionID;
	NSString* _deviceName;
	NSString* _regionBasePhoneNumber;
	NSDictionary* _regionServerContext;
	NSData* _registrationCert;
	NSString* _serviceType;
	NSString* _guid;
	NSMutableArray* _candidateEmails;
	NSDictionary* _migrationContext;
	NSNumber* _identityVersion;
	NSString* _keyPairSignature;
	NSString* _idsUserID;
	NSString* _serviceIdentifier;
	NSArray* _uris;
	NSArray* _adHocServiceNames;
	NSString* _temporaryPhoneEmail;
	NSDate* _dependentRegistrationsTTL;
	NSNumber* _dependentRegistrationResponseCode;
	NSNumber* _dependentRegistrationAuthRetries;
	NSArray* _keyTransparencyEnrolledURIs;
	NSString* _userUniqueIdentifier;
	id<FTPasswordManager> _passwordManager;

}

@property (nonatomic,retain) id<FTPasswordManager> passwordManager;                   //@synthesize passwordManager=_passwordManager - In the implementation block
@property (nonatomic,retain) NSMutableArray * _candidateEmails;                       //@synthesize candidateEmails=_candidateEmails - In the implementation block
@property (nonatomic,retain) NSString * temporaryPhoneEmail;                          //@synthesize temporaryPhoneEmail=_temporaryPhoneEmail - In the implementation block
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
@property (nonatomic,retain) NSDictionary * migrationContext;                         //@synthesize migrationContext=_migrationContext - In the implementation block
@property (assign,nonatomic) long long registrationStatus;                            //@synthesize registrationStatus=_registrationStatus - In the implementation block
@property (assign,nonatomic) int registrationType;                                    //@synthesize registrationType=_registrationType - In the implementation block
@property (nonatomic,retain) NSString * serviceType;                                  //@synthesize serviceType=_serviceType - In the implementation block
@property (nonatomic,retain) NSString * serviceIdentifier;                            //@synthesize serviceIdentifier=_serviceIdentifier - In the implementation block
@property (assign,nonatomic) int retries;                                             //@synthesize retries=_retries - In the implementation block
@property (assign,nonatomic) int absintheRetries;                                     //@synthesize absintheRetries=_absintheRetries - In the implementation block
@property (assign,nonatomic) char needsMigration;                                     //@synthesize needsMigration=_needsMigration - In the implementation block
@property (assign,nonatomic) char needsProvisioning;                                  //@synthesize needsProvisioning=_needsProvisioning - In the implementation block
@property (assign,nonatomic) char needsRenewal;                                       //@synthesize needsRenewal=_needsRenewal - In the implementation block
@property (assign,nonatomic) char runningSimpleAuthentication;                        //@synthesize runningSimpleAuthentication=_runningSimpleAuthentication - In the implementation block
@property (assign,nonatomic) char isDisabled;                                         //@synthesize isDisabled=_isDisabled - In the implementation block
@property (nonatomic,readonly) NSString * userID; 
@property (nonatomic,copy) NSString * mainID;                                         //@synthesize mainID=_mainID - In the implementation block
@property (nonatomic,readonly) NSString * guid;                                       //@synthesize guid=_guid - In the implementation block
@property (nonatomic,copy) NSString * deviceName;                                     //@synthesize deviceName=_deviceName - In the implementation block
@property (nonatomic,copy) NSDate * registrationDate;                                 //@synthesize registrationDate=_registrationDate - In the implementation block
@property (nonatomic,copy) NSDate * nextRegistrationDate;                             //@synthesize nextRegistrationDate=_nextRegistrationDate - In the implementation block
@property (nonatomic,copy) NSData * pushToken;                                        //@synthesize pushToken=_pushToken - In the implementation block
@property (nonatomic,copy) NSString * phoneNumber; 
@property (nonatomic,copy) NSString * email; 
@property (nonatomic,readonly) NSArray * confirmedEmails; 
@property (nonatomic,retain) NSArray * vettedEmails;                                  //@synthesize vettedEmails=_vettedEmails - In the implementation block
@property (setter=setDSHandle:,nonatomic,retain) NSString * dsHandle;                 //@synthesize dsHandle=_dsHandle - In the implementation block
@property (nonatomic,readonly) NSArray * candidateEmails; 
@property (nonatomic,copy) NSString * environment;                                    //@synthesize environment=_environment - In the implementation block
@property (nonatomic,copy) NSString * keyPairSignature;                               //@synthesize keyPairSignature=_keyPairSignature - In the implementation block
@property (nonatomic,copy) NSNumber * isCDMA;                                         //@synthesize isC2K=_isC2K - In the implementation block
@property (nonatomic,copy) NSNumber * IDSVersion;                                     //@synthesize IDSVersion=_IDSVersion - In the implementation block
@property (nonatomic,copy) NSNumber * applicationVersion;                             //@synthesize applicationVersion=_applicationVersion - In the implementation block
@property (nonatomic,copy) NSNumber * identityVersion;                                //@synthesize identityVersion=_identityVersion - In the implementation block
@property (nonatomic,copy) NSString * profileID;                                      //@synthesize profileID=_profileID - In the implementation block
@property (nonatomic,copy) NSString * authenticationToken; 
@property (nonatomic,copy) NSString * regionID;                                       //@synthesize regionID=_regionID - In the implementation block
@property (nonatomic,copy) NSString * regionBasePhoneNumber;                          //@synthesize regionBasePhoneNumber=_regionBasePhoneNumber - In the implementation block
@property (nonatomic,copy) NSDictionary * regionServerContext;                        //@synthesize regionServerContext=_regionServerContext - In the implementation block
@property (nonatomic,copy) NSArray * dependentRegistrations;                          //@synthesize dependentRegistrations=_dependentRegistrations - In the implementation block
@property (nonatomic,copy) NSDate * dependentRegistrationsTTL;                        //@synthesize dependentRegistrationsTTL=_dependentRegistrationsTTL - In the implementation block
@property (nonatomic,copy) NSNumber * dependentRegistrationResponseCode;              //@synthesize dependentRegistrationResponseCode=_dependentRegistrationResponseCode - In the implementation block
@property (nonatomic,copy) NSNumber * dependentRegistrationAuthRetries;               //@synthesize dependentRegistrationAuthRetries=_dependentRegistrationAuthRetries - In the implementation block
@property (nonatomic,copy) NSString * idsUserID;                                      //@synthesize idsUserID=_idsUserID - In the implementation block
@property (nonatomic,copy) NSArray * uris;                                            //@synthesize uris=_uris - In the implementation block
@property (nonatomic,copy) NSArray * keyTransparencyEnrolledURIs;                     //@synthesize keyTransparencyEnrolledURIs=_keyTransparencyEnrolledURIs - In the implementation block
@property (nonatomic,copy) NSData * authenticationCert; 
@property (nonatomic,copy) NSData * registrationCert;                                 //@synthesize registrationCert=_registrationCert - In the implementation block
@property (assign,nonatomic) char shouldAutoRegisterAllHandles;                       //@synthesize shouldAutoRegisterAllHandles=_shouldAutoRegisterAllHandles - In the implementation block
@property (assign,nonatomic) char shouldRegisterUsingDSHandle;                        //@synthesize shouldRegisterUsingDSHandle=_shouldRegisterUsingDSHandle - In the implementation block
@property (nonatomic,readonly) NSArray * emailsToRegister; 
@property (nonatomic,readonly) char hasSentinel; 
@property (nonatomic,readonly) char canRegister; 
@property (nonatomic,readonly) char canSendRegistration; 
@property (nonatomic,retain) NSArray * adHocServiceNames;                             //@synthesize adHocServiceNames=_adHocServiceNames - In the implementation block
@property (nonatomic,retain) NSString * userUniqueIdentifier;                         //@synthesize userUniqueIdentifier=_userUniqueIdentifier - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(id)description;
-(id)debugDescription;
-(id)init;
-(id)initWithDictionary:(id)arg1 ;
-(int)retries;
-(void)setRetries:(int)arg1 ;
-(NSDate *)registrationDate;
-(void)setEnvironment:(NSString *)arg1 ;
-(NSString *)userID;
-(NSDictionary *)dictionaryRepresentation;
-(NSString *)environment;
-(NSString *)phoneNumber;
-(NSString *)serviceIdentifier;
-(NSString *)regionID;
-(NSString *)deviceName;
-(NSString *)serviceType;
-(id)_userID;
-(void)setIsDisabled:(char)arg1 ;
-(char)isDisabled;
-(NSString *)email;
-(void)setPhoneNumber:(NSString *)arg1 ;
-(void)setDeviceName:(NSString *)arg1 ;
-(void)setServiceType:(NSString *)arg1 ;
-(id)_user;
-(NSData *)pushToken;
-(void)setServiceIdentifier:(NSString *)arg1 ;
-(NSString *)userUniqueIdentifier;
-(long long)registrationStatus;
-(id<FTPasswordManager>)passwordManager;
-(void)setPasswordManager:(id<FTPasswordManager>)arg1 ;
-(NSDate *)nextRegistrationDate;
-(NSDictionary *)regionServerContext;
-(NSString *)profileID;
-(void)setRegionID:(NSString *)arg1 ;
-(NSString *)regionBasePhoneNumber;
-(void)setRegionBasePhoneNumber:(NSString *)arg1 ;
-(NSString *)guid;
-(char)shouldAutoRegisterAllHandles;
-(char)shouldRegisterUsingDSHandle;
-(int)registrationType;
-(void)setRegistrationType:(int)arg1 ;
-(void)setPushToken:(NSData *)arg1 ;
-(NSNumber *)applicationVersion;
-(void)setApplicationVersion:(NSNumber *)arg1 ;
-(char)canRegister;
-(void)setEmail:(NSString *)arg1 ;
-(void)setRegistrationDate:(NSDate *)arg1 ;
-(void)setAuthenticationToken:(NSString *)arg1 ;
-(NSString *)authenticationToken;
-(void)setRegistrationStatus:(long long)arg1 ;
-(void)setProfileID:(NSString *)arg1 ;
-(NSArray *)uris;
-(void)setUris:(NSArray *)arg1 ;
-(NSDictionary *)migrationContext;
-(char)saveToKeychain;
-(char)removeFromKeychain;
-(id)_userStore;
-(char)needsRenewal;
-(char)needsMigration;
-(NSString *)keyPairSignature;
-(char)canSendRegistration;
-(void)setRunningSimpleAuthentication:(char)arg1 ;
-(NSString *)mainID;
-(NSData *)authenticationCert;
-(void)setRegistrationCert:(NSData *)arg1 ;
-(void)setAuthenticationCert:(NSData *)arg1 ;
-(void)setNeedsRenewal:(char)arg1 ;
-(NSArray *)vettedEmails;
-(NSString *)dsHandle;
-(void)setMainID:(NSString *)arg1 ;
-(NSArray *)confirmedEmails;
-(void)addCandidateEmail:(id)arg1 ;
-(char)runningSimpleAuthentication;
-(void)setVettedEmails:(NSArray *)arg1 ;
-(NSArray *)dependentRegistrations;
-(NSString *)idsUserID;
-(NSDate *)dependentRegistrationsTTL;
-(NSNumber *)dependentRegistrationResponseCode;
-(NSArray *)adHocServiceNames;
-(NSData *)registrationCert;
-(void)setUserUniqueIdentifier:(NSString *)arg1 ;
-(NSArray *)candidateEmails;
-(void)setShouldAutoRegisterAllHandles:(char)arg1 ;
-(void)setShouldRegisterUsingDSHandle:(char)arg1 ;
-(void)setIdsUserID:(NSString *)arg1 ;
-(void)setIsCDMA:(NSNumber *)arg1 ;
-(void)setKeyPairSignature:(NSString *)arg1 ;
-(void)setRegionServerContext:(NSDictionary *)arg1 ;
-(void)setAdHocServiceNames:(NSArray *)arg1 ;
-(NSNumber *)IDSVersion;
-(NSNumber *)identityVersion;
-(void)setMigrationContext:(NSDictionary *)arg1 ;
-(void)setNeedsMigration:(char)arg1 ;
-(void)setDependentRegistrationsTTL:(NSDate *)arg1 ;
-(void)setDependentRegistrationAuthRetries:(NSNumber *)arg1 ;
-(void)setDependentRegistrationResponseCode:(NSNumber *)arg1 ;
-(NSNumber *)dependentRegistrationAuthRetries;
-(void)setDependentRegistrations:(NSArray *)arg1 ;
-(void)removeCandidateEmail:(id)arg1 ;
-(NSNumber *)isCDMA;
-(id)_keychain_comparisonValue;
-(char)_keychain_isEqual:(id)arg1 ;
-(int)absintheRetries;
-(void)setAbsintheRetries:(int)arg1 ;
-(void)setNextRegistrationDate:(NSDate *)arg1 ;
-(void)setIdentityVersion:(NSNumber *)arg1 ;
-(void)setIDSVersion:(NSNumber *)arg1 ;
-(void)setKeyTransparencyEnrolledURIs:(NSArray *)arg1 ;
-(NSArray *)emailsToRegister;
-(char)hasSentinel;
-(void)setDSHandle:(id)arg1 ;
-(void)voidPassword;
-(void)voidAuthenticationTokenAllowingGracePeriod;
-(id)initWithPasswordManager:(id)arg1 ;
-(void)setTemporaryPhoneEmail:(NSString *)arg1 ;
-(char)needsProvisioning;
-(void)setNeedsProvisioning:(char)arg1 ;
-(NSMutableArray *)_candidateEmails;
-(void)set_candidateEmails:(NSMutableArray *)arg1 ;
-(NSString *)temporaryPhoneEmail;
-(NSArray *)keyTransparencyEnrolledURIs;
@end

