/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSRapportDeliveryControllerRapportClient <NSObject>
@required
-(void)removeDelegate:(id)arg1;
-(void)addDelegate:(id)arg1;
-(void)sendMessage:(id)arg1 toDeviceIdentifier:(id)arg2 completionBlock:(/*^block*/id)arg3;

@end

