/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@class NSString, NSData, NSDate;

@interface IDSRealTimeEncryptionIdentity : NSObject {

	NSString* _groupID;
	NSString* _sessionID;
	NSString* _participantID;
	NSString* _fromID;
	NSData* _pushToken;
	NSDate* _expirationDate;
	char _isPublicKeyDistributed;
	SecKeyRef _fullIdentity;
	SecKeyRef _publicIdentity;
	NSData* _publicIdentityData;
	char _isTestRunning;

}

@property (nonatomic,copy) NSString * groupID;                         //@synthesize groupID=_groupID - In the implementation block
@property (nonatomic,copy) NSString * sessionID;                       //@synthesize sessionID=_sessionID - In the implementation block
@property (nonatomic,copy) NSString * participantID;                   //@synthesize participantID=_participantID - In the implementation block
@property (nonatomic,copy) NSString * fromID;                          //@synthesize fromID=_fromID - In the implementation block
@property (nonatomic,copy) NSData * pushToken;                         //@synthesize pushToken=_pushToken - In the implementation block
@property (nonatomic,copy) NSDate * expirationDate;                    //@synthesize expirationDate=_expirationDate - In the implementation block
@property (assign,nonatomic) char isPublicKeyDistributed;              //@synthesize isPublicKeyDistributed=_isPublicKeyDistributed - In the implementation block
@property (nonatomic,readonly) char isExpired; 
@property (assign,nonatomic) SecKeyRef fullIdentity;                   //@synthesize fullIdentity=_fullIdentity - In the implementation block
@property (assign,nonatomic) SecKeyRef publicIdentity;                 //@synthesize publicIdentity=_publicIdentity - In the implementation block
@property (nonatomic,copy) NSData * publicIdentityData;                //@synthesize publicIdentityData=_publicIdentityData - In the implementation block
@property (nonatomic,readonly) NSData * publicKeyData; 
@property (assign,nonatomic) char isTestRunning;                       //@synthesize isTestRunning=_isTestRunning - In the implementation block
-(void)dealloc;
-(NSDate *)expirationDate;
-(void)setExpirationDate:(NSDate *)arg1 ;
-(NSString *)groupID;
-(void)setGroupID:(NSString *)arg1 ;
-(NSString *)sessionID;
-(void)setSessionID:(NSString *)arg1 ;
-(NSString *)participantID;
-(void)setParticipantID:(NSString *)arg1 ;
-(char)isExpired;
-(NSData *)pushToken;
-(void)setFromID:(NSString *)arg1 ;
-(NSString *)fromID;
-(NSData *)publicKeyData;
-(SecKeyRef)publicIdentity;
-(void)setPushToken:(NSData *)arg1 ;
-(SecKeyRef)fullIdentity;
-(char)isTestRunning;
-(void)setIsTestRunning:(char)arg1 ;
-(void)setFullIdentity:(SecKeyRef)arg1 ;
-(void)setPublicIdentity:(SecKeyRef)arg1 ;
-(void)setPublicIdentityData:(NSData *)arg1 ;
-(NSData *)publicIdentityData;
-(char)isPublicKeyDistributed;
-(void)setIsPublicKeyDistributed:(char)arg1 ;
@end

