/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSUUID, NSData, NSDate, NSMutableSet, NSString;

@interface IDSRealTimeEncryptionKeyMaterial : NSObject {

	NSUUID* _MKI;
	NSData* _MKS;
	NSData* _MKM;
	NSDate* _createdAt;
	char _isSentToClient;
	char _isGeneratedLocally;
	NSMutableSet* _devicesToBeSent;
	NSString* _groupID;

}

@property (nonatomic,readonly) NSUUID * MKI;                       //@synthesize MKI=_MKI - In the implementation block
@property (nonatomic,readonly) NSData * MKS;                       //@synthesize MKS=_MKS - In the implementation block
@property (nonatomic,readonly) NSData * MKM;                       //@synthesize MKM=_MKM - In the implementation block
@property (nonatomic,readonly) NSDate * createdAt;                 //@synthesize createdAt=_createdAt - In the implementation block
@property (assign,nonatomic) char isSentToClient;                  //@synthesize isSentToClient=_isSentToClient - In the implementation block
@property (assign,nonatomic) char isGeneratedLocally;              //@synthesize isGeneratedLocally=_isGeneratedLocally - In the implementation block
@property (nonatomic,readonly) NSString * groupID;                 //@synthesize groupID=_groupID - In the implementation block
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)debugDescription;
-(NSString *)groupID;
-(NSDate *)createdAt;
-(NSUUID *)MKI;
-(char)isGeneratedLocally;
-(NSData *)MKM;
-(NSData *)MKS;
-(id)initWithMKM:(id)arg1 MKS:(id)arg2 MKI:(id)arg3 groupID:(id)arg4 ;
-(id)initWithIndex:(id)arg1 groupID:(id)arg2 ;
-(char)isSentToClient;
-(void)setIsSentToClient:(char)arg1 ;
-(void)sentToDevice:(id)arg1 ;
-(char)isEqualToRealTimeEncryptionKeyMaterial:(id)arg1 ;
-(void)_changeCreatedAt:(id)arg1 ;
-(void)removeDeviceFromSentToDevice:(id)arg1 ;
-(void)setIsGeneratedLocally:(char)arg1 ;
@end

