/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:08 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSRapportClientDelegate <NSObject>
@optional
-(void)rapportClient:(id)arg1 didDiscoverDevice:(id)arg2;
-(void)rapportClient:(id)arg1 didLoseDevice:(id)arg2;
-(void)rapportClient:(id)arg1 didReceiveMessage:(id)arg2 fromID:(id)arg3;

@end

