/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:00 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSSocketPairConnectionDelegate <NSObject>
@optional
-(void)connectionDidClose:(id)arg1;
-(void)connectionDidClose;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 withIdentifier:(unsigned)arg3;
-(void)connection:(id)arg1 didReceiveDataMessage:(id)arg2;
-(void)connectionDidReachInFlightMessageLowWaterMark:(id)arg1;
-(void)connectionBecameEmpty:(id)arg1;
-(void)connectionDidReceiveBytes:(id)arg1;
-(void)didReceiveDataMessage:(id)arg1;
-(void)connectionBecameEmpty;

@end

