/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:05 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSCTAdapterListener.h>
#import <libobjc.A.dylib/IDSPairingManagerDelegate.h>
#import <libobjc.A.dylib/IDSUserStoreListener.h>
#import <libobjc.A.dylib/IDSUserStoreProvider.h>

@class IDSUserStore, IDSCTAdapter, IMLockdownManager, IMSystemMonitor, IDSRegistrationController, FTUserConfiguration, IDSPairingManager, NSMutableDictionary, NSString;

@interface IDSSIMPhoneUserSynchronizer : NSObject <IDSCTAdapterListener, IDSPairingManagerDelegate, IDSUserStoreListener, IDSUserStoreProvider> {

	IDSUserStore* _userStore;
	IDSCTAdapter* _CTAdapter;
	IMLockdownManager* _lockdownManager;
	IMSystemMonitor* _systemMonitor;
	IDSRegistrationController* _registrationController;
	FTUserConfiguration* _userConfiguration;
	IDSPairingManager* _pairingManager;
	NSMutableDictionary* _cachedIsSameSIM;

}

@property (nonatomic,retain) IDSUserStore * userStore;                                        //@synthesize userStore=_userStore - In the implementation block
@property (nonatomic,retain) IDSCTAdapter * CTAdapter;                                        //@synthesize CTAdapter=_CTAdapter - In the implementation block
@property (nonatomic,retain) IMLockdownManager * lockdownManager;                             //@synthesize lockdownManager=_lockdownManager - In the implementation block
@property (nonatomic,retain) IMSystemMonitor * systemMonitor;                                 //@synthesize systemMonitor=_systemMonitor - In the implementation block
@property (nonatomic,retain) IDSRegistrationController * registrationController;              //@synthesize registrationController=_registrationController - In the implementation block
@property (nonatomic,retain) FTUserConfiguration * userConfiguration;                         //@synthesize userConfiguration=_userConfiguration - In the implementation block
@property (nonatomic,retain) IDSPairingManager * pairingManager;                              //@synthesize pairingManager=_pairingManager - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * cachedIsSameSIM;                           //@synthesize cachedIsSameSIM=_cachedIsSameSIM - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(IDSCTAdapter *)CTAdapter;
-(void)setCTAdapter:(IDSCTAdapter *)arg1 ;
-(IDSPairingManager *)pairingManager;
-(IMLockdownManager *)lockdownManager;
-(void)setLockdownManager:(IMLockdownManager *)arg1 ;
-(IMSystemMonitor *)systemMonitor;
-(IDSRegistrationController *)registrationController;
-(IDSUserStore *)userStore;
-(void)setUserStore:(IDSUserStore *)arg1 ;
-(void)setSystemMonitor:(IMSystemMonitor *)arg1 ;
-(void)userStore:(id)arg1 didRemoveUser:(id)arg2 withAuthenticationCertificate:(id)arg3 ;
-(void)userStore:(id)arg1 didAddUser:(id)arg2 ;
-(void)userStore:(id)arg1 didUpdateUser:(id)arg2 ;
-(void)userStore:(id)arg1 didRemoveAuthenticationCertificateForUser:(id)arg2 ;
-(void)didUpdatePairedDevice:(id)arg1 ;
-(void)setPairingManager:(IDSPairingManager *)arg1 ;
-(void)selectedSubscriptionLabelDidChange:(id)arg1 ;
-(void)_setupForCurrentSubscriptionState;
-(void)_checkRegistrationStatus;
-(void)SIMInformationDidChange;
-(id)updatedUserSetForRealm:(long long)arg1 currentUsers:(id)arg2 ;
-(void)forceRemoveUser:(id)arg1 silently:(char)arg2 ;
-(id)initWithUserStore:(id)arg1 queue:(id)arg2 lockdownManager:(id)arg3 systemMonitor:(id)arg4 CTAdapter:(id)arg5 userConfiguration:(id)arg6 registrationController:(id)arg7 pairingManager:(id)arg8 ;
-(void)verifyState;
-(char)_isInDualPhoneIdentityModeForSims:(id)arg1 ;
-(void)setRegistrationController:(IDSRegistrationController *)arg1 ;
-(FTUserConfiguration *)userConfiguration;
-(void)setUserConfiguration:(FTUserConfiguration *)arg1 ;
-(NSMutableDictionary *)cachedIsSameSIM;
-(void)setCachedIsSameSIM:(NSMutableDictionary *)arg1 ;
@end

