/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:57 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject;

@interface IDSSystemAccountAdapter : NSObject {

	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
-(id)initWithQueue:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)_systemAccountWithIdentifier:(id)arg1 DSIDKey:(id)arg2 criteria:(/*^block*/id)arg3 completion:(/*^block*/id)arg4 ;
-(id)_systemAccountWithIdentifier:(id)arg1 DSIDKey:(id)arg2 criteria:(/*^block*/id)arg3 error:(id*)arg4 ;
-(id)_systemAccountRepresentationOfACAccount:(id)arg1 DSIDKey:(id)arg2 ;
-(void)_ACAccountWithTypeIdentifier:(id)arg1 matchingCriteria:(/*^block*/id)arg2 completion:(/*^block*/id)arg3 ;
-(id)_firstAccountInStore:(id)arg1 withType:(id)arg2 matchingCriteria:(/*^block*/id)arg3 ;
-(id)_ACAccountWithTypeIdentifier:(id)arg1 matchingCriteria:(/*^block*/id)arg2 error:(id*)arg3 ;
-(void)iCloudSystemAccountWithCompletion:(/*^block*/id)arg1 ;
-(void)iTunesSystemAccountWithCompletion:(/*^block*/id)arg1 ;
-(id)iCloudSystemAccountWithError:(id*)arg1 ;
-(id)iTunesSystemAccountWithError:(id*)arg1 ;
@end

