/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:01 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, FTMessageDelivery;

@interface IDSServer : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	FTMessageDelivery* _messageDelivery;

}

@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> queue;               //@synthesize queue=_queue - In the implementation block
@property (nonatomic,readonly) FTMessageDelivery * messageDelivery;              //@synthesize messageDelivery=_messageDelivery - In the implementation block
-(id)initWithQueue:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(FTMessageDelivery *)messageDelivery;
-(id)initWithQueue:(id)arg1 messageDelivery:(id)arg2 ;
-(id)_stringRepresentationForRealm:(long long)arg1 ;
-(id)_DSAuthIDForPushToken:(id)arg1 ;
-(id)authenticatePhoneUserWithRequest:(id)arg1 ;
-(id)_authenticateMessageForRequest:(id)arg1 ;
@end

