/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSSet;


@protocol IDSSocketPairConnectionProtocol
@property (nonatomic,readonly) NSSet * inFlightMessages; 
@required
-(void)start;
-(void)endSession;
-(NSSet *)inFlightMessages;
-(double)lastSocketActivityTime;
-(void)setOTREncryptionBlock:(/*^block*/id)arg1 decryptionBlock:(/*^block*/id)arg2;
-(char)sendDataMessage:(id)arg1 canFragment:(char)arg2;
-(void)processStoredIncomingMessage:(id)arg1;
-(char)sendDataMessage:(id)arg1;

@end

