/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:59 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSMutableSet, IDSDeliveryController, IMUserDefaults, IDSServerBag;

@interface IDSServerStorageStateMachine : NSObject {

	NSMutableDictionary* _currentStorageRetriesPerTopic;
	NSMutableDictionary* _deathTimerToTopicMap;
	NSMutableDictionary* _lastReceivedMessageTimePerTopic;
	NSMutableSet* _inflightStorageRequests;
	NSMutableSet* _pendingStorageRequests;
	NSMutableDictionary* _metricCollectors;
	IDSDeliveryController* _deliveryController;
	IMUserDefaults* _userDefaults;
	IDSServerBag* _idsServerBag;

}

@property (nonatomic,retain) IDSDeliveryController * deliveryController;              //@synthesize deliveryController=_deliveryController - In the implementation block
@property (nonatomic,retain) IMUserDefaults * userDefaults;                           //@synthesize userDefaults=_userDefaults - In the implementation block
@property (nonatomic,retain) IDSServerBag * idsServerBag;                             //@synthesize idsServerBag=_idsServerBag - In the implementation block
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(IMUserDefaults *)userDefaults;
-(IDSDeliveryController *)deliveryController;
-(void)setUserDefaults:(IMUserDefaults *)arg1 ;
-(id)initWithDeliveryController:(id)arg1 userDefaults:(id)arg2 idsServerBag:(id)arg3 ;
-(void)setDeliveryController:(IDSDeliveryController *)arg1 ;
-(void)setIdsServerBag:(IDSServerBag *)arg1 ;
-(void)_persistTopic:(id)arg1 ;
-(void)startCollectingMetricsForServerStorageStateMachineFor:(id)arg1 isPrimary:(char)arg2 ;
-(void)_sendServerStorageMessageForTopic:(id)arg1 retryCount:(int)arg2 ;
-(void)terminateStateMachineForTopic:(id)arg1 ;
-(void)_incrementMessagesFromStorageForTopic:(id)arg1 ;
-(IDSServerBag *)idsServerBag;
-(void)_stateMachineTimedOut:(id)arg1 ;
-(void)_startExtendedTimeoutTimerForTopic:(id)arg1 ;
-(void)_submitNoLastFromStorageMetricForService:(id)arg1 ;
-(void)_startTimeoutTimerForTopic:(id)arg1 ;
-(void)stopCollectingMetricsForServerStorageStateMachineFor:(id)arg1 ;
-(void)incomingStorageRequestForTopic:(id)arg1 primary:(char)arg2 messageContext:(id)arg3 ;
-(void)_unpersistTopic:(id)arg1 ;
-(id)_persistedTopics;
-(void)recievedNoStorageResponseForTopic:(id)arg1 messageContext:(id)arg2 ;
-(void)recievedLastMessageFromStorageForTopic:(id)arg1 ;
-(void)recievedMessageFromStorageForTopic:(id)arg1 ;
-(char)inflightServerStorageStateMachineForTopic:(id)arg1 ;
-(id)currentMetricCollectorForTopic:(id)arg1 ;
-(void)reissuePersistedRequests;
-(id)metricCollectors;
@end

