/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSDAccountController, IDSDServiceController, IDSRegistrationController, IDSRestrictions, NSDate;

@interface IDSSIMResponder : NSObject {

	IDSDAccountController* _accountController;
	IDSDServiceController* _serviceController;
	IDSRegistrationController* _registrationController;
	IDSRestrictions* _restrictions;
	NSDate* _registrationStateChangedDate;
	long long _registrationStateChangedCounter;

}

@property (nonatomic,retain) IDSDAccountController * accountController;                       //@synthesize accountController=_accountController - In the implementation block
@property (nonatomic,retain) IDSDServiceController * serviceController;                       //@synthesize serviceController=_serviceController - In the implementation block
@property (nonatomic,retain) IDSRegistrationController * registrationController;              //@synthesize registrationController=_registrationController - In the implementation block
@property (nonatomic,retain) IDSRestrictions * restrictions;                                  //@synthesize restrictions=_restrictions - In the implementation block
@property (nonatomic,retain) NSDate * registrationStateChangedDate;                           //@synthesize registrationStateChangedDate=_registrationStateChangedDate - In the implementation block
@property (assign,nonatomic) long long registrationStateChangedCounter;                       //@synthesize registrationStateChangedCounter=_registrationStateChangedCounter - In the implementation block
-(void)setRestrictions:(IDSRestrictions *)arg1 ;
-(IDSRestrictions *)restrictions;
-(IDSDServiceController *)serviceController;
-(IDSDAccountController *)accountController;
-(void)setAccountController:(IDSDAccountController *)arg1 ;
-(IDSRegistrationController *)registrationController;
-(void)setServiceController:(IDSDServiceController *)arg1 ;
-(void)setRegistrationController:(IDSRegistrationController *)arg1 ;
-(void)_enumeratePrimaryAccountsOfType:(int)arg1 block:(/*^block*/id)arg2 ;
-(void)_checkTechChange;
-(id)initWithAccountController:(id)arg1 serviceController:(id)arg2 restrictions:(id)arg3 registrationController:(id)arg4 ;
-(void)handleSIMInserted;
-(void)handleRegistrationStateChanged:(char)arg1 ;
-(void)handleSIMRemoved;
-(NSDate *)registrationStateChangedDate;
-(void)setRegistrationStateChangedDate:(NSDate *)arg1 ;
-(long long)registrationStateChangedCounter;
-(void)setRegistrationStateChangedCounter:(long long)arg1 ;
@end

