/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSTTLCacheDelegate <NSObject>
@optional
-(void)ttlCache:(id)arg1 didCacheObject:(id)arg2 forKey:(id)arg3;
-(void)ttlCache:(id)arg1 willReturnCachedObject:(id)arg2 forKey:(id)arg3 completion:(/*^block*/id)arg4;
-(char)ttlCache:(id)arg1 shouldEvictObject:(id)arg2 forKey:(id)arg3;
-(void)ttlCache:(id)arg1 didEvictObject:(id)arg2 forKey:(id)arg3;
-(char)shouldTTLCacheEvictExpiredItems:(id)arg1;

@end

