/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:02 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/IDSUserStoreListener.h>

@protocol IDSTemporaryPhoneUserExpirationManagerDelegate;
@class NSMutableDictionary, NSString;

@interface IDSTemporaryPhoneUserExpirationManager : NSObject <IDSUserStoreListener> {

	os_unfair_lock_s _usersToTimersLock;
	id<IDSTemporaryPhoneUserExpirationManagerDelegate> _delegate;
	NSMutableDictionary* _usersToTimers;

}

@property (assign,nonatomic,__weak) id<IDSTemporaryPhoneUserExpirationManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) os_unfair_lock_s usersToTimersLock;                                              //@synthesize usersToTimersLock=_usersToTimersLock - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * usersToTimers;                                             //@synthesize usersToTimers=_usersToTimers - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id<IDSTemporaryPhoneUserExpirationManagerDelegate>)delegate;
-(void)setDelegate:(id<IDSTemporaryPhoneUserExpirationManagerDelegate>)arg1 ;
-(void)_attemptToKickoffExpirationTimerForUser:(id)arg1 ;
-(void)_kickoffExpirationTimerForInfo:(id)arg1 ;
-(NSMutableDictionary *)usersToTimers;
-(void)_expireTimer:(id)arg1 ;
-(void)_cancelExpirationTimerForUser:(id)arg1 ;
-(void)userStore:(id)arg1 didRemoveUser:(id)arg2 withAuthenticationCertificate:(id)arg3 ;
-(void)userStore:(id)arg1 didAddUser:(id)arg2 ;
-(void)userStore:(id)arg1 didUpdateUser:(id)arg2 ;
-(void)userStore:(id)arg1 didRemoveAuthenticationCertificateForUser:(id)arg2 ;
-(id)initWithUserStore:(id)arg1 delegate:(id)arg2 ;
-(os_unfair_lock_s)usersToTimersLock;
-(void)setUsersToTimersLock:(os_unfair_lock_s)arg1 ;
-(void)setUsersToTimers:(NSMutableDictionary *)arg1 ;
@end

