/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:10 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <identityservicesd/identityservicesd-Structs.h>
#import <libobjc.A.dylib/NWNetworkAgent.h>

@class NSString, NSUUID, NSMutableDictionary, NWNetworkAgentRegistration, NEPolicySession;

@interface IDSTransportLevelAgent : NSObject <NWNetworkAgent> {

	NSMutableDictionary* _multiplexers;
	NSMutableDictionary* _clientMultiplexer;
	char active;
	NSUUID* agentUUID;
	NWNetworkAgentRegistration* _registration;
	NEPolicySession* _session;
	NEVirtualInterface_sRef _interface;

}

@property (nonatomic,retain) NWNetworkAgentRegistration * registration;                  //@synthesize registration=_registration - In the implementation block
@property (nonatomic,retain) NEPolicySession * session;                                  //@synthesize session=_session - In the implementation block
@property (assign) NEVirtualInterface_sRef interface;                                    //@synthesize interface=_interface - In the implementation block
@property (nonatomic,copy) NSString * agentDescription; 
@property (nonatomic,copy) NSUUID * agentUUID; 
@property (assign,getter=isActive,nonatomic) char active; 
@property (assign,getter=isKernelActivated,nonatomic) char kernelActivated; 
@property (assign,getter=isUserActivated,nonatomic) char userActivated; 
@property (assign,getter=isVoluntary,nonatomic) char voluntary; 
@property (assign,getter=isSpecificUseOnly,nonatomic) char specificUseOnly; 
@property (assign,getter=isNetworkProvider,nonatomic) char networkProvider; 
@property (assign,getter=isNexusProvider,nonatomic) char nexusProvider; 
@property (assign,nonatomic) char supportsListenRequests; 
@property (assign,nonatomic) char supportsBrowseRequests; 
@property (assign,nonatomic) char supportsResolveRequests; 
@property (assign,nonatomic) char requiresAssert; 
@property (assign,nonatomic) char updateClientsImmediately; 
+(id)sharedInstance;
+(id)agentDomain;
+(id)agentType;
+(id)agentFromData:(id)arg1 ;
-(id)init;
-(char)isActive;
-(void)setActive:(char)arg1 ;
-(NEPolicySession *)session;
-(NEVirtualInterface_sRef)interface;
-(void)setSession:(NEPolicySession *)arg1 ;
-(NWNetworkAgentRegistration *)registration;
-(void)setInterface:(NEVirtualInterface_sRef)arg1 ;
-(void)setRegistration:(NWNetworkAgentRegistration *)arg1 ;
-(id)copyAgentData;
-(void)setKernelActivated:(char)arg1 ;
-(void)setUserActivated:(char)arg1 ;
-(void)setVoluntary:(char)arg1 ;
-(NSString *)agentDescription;
-(void)setAgentDescription:(NSString *)arg1 ;
-(NSUUID *)agentUUID;
-(void)setAgentUUID:(NSUUID *)arg1 ;
-(char)isKernelActivated;
-(char)isUserActivated;
-(char)isVoluntary;
-(char)startAgentWithOptions:(id)arg1 ;
-(char)assertAgentWithOptions:(id)arg1 ;
-(void)unassertAgentWithOptions:(id)arg1 ;
-(char)requestNexusWithOptions:(id)arg1 ;
-(void)closeNexusWithOptions:(id)arg1 ;
-(char)isSpecificUseOnly;
-(void)setSpecificUseOnly:(char)arg1 ;
-(char)isNetworkProvider;
-(void)setNetworkProvider:(char)arg1 ;
-(char)isNexusProvider;
-(void)setNexusProvider:(char)arg1 ;
-(void)registerMultiplexer:(id)arg1 forIdentifier:(id)arg2 ;
-(id)multiplexerForIdentifier:(id)arg1 ;
-(void)unregisterMultiplexerForIdentifier:(id)arg1 ;
@end

