/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:02 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSTemporaryPhoneUser;

@interface IDSTemporaryPhoneUserExpirationTimerInfo : NSObject {

	IDSTemporaryPhoneUser* _user;
	long long _expirationPhase;

}

@property (readonly) IDSTemporaryPhoneUser * user;              //@synthesize user=_user - In the implementation block
@property (readonly) long long expirationPhase;                 //@synthesize expirationPhase=_expirationPhase - In the implementation block
@property (readonly) double expirationInterval; 
+(long long)phaseForExpirationDate:(id)arg1 ;
-(IDSTemporaryPhoneUser *)user;
-(id)initWithUser:(id)arg1 ;
-(double)expirationInterval;
-(id)initWithUser:(id)arg1 expirationPhase:(long long)arg2 ;
-(long long)expirationPhase;
@end

