/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:00 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IDSTransparentEndpointViewer : NSObject
-(void)performOutstandingKeyTransparencyVerificationWithCompletion:(/*^block*/id)arg1 ;
-(id)_cloudKitContainer;
-(id)_verifier;
-(id)_peerIDManager;
-(id)_keyTransparencyEntriesForEndpoints:(id)arg1 ;
-(id)_registrationKeyManager;
-(void)schedulePeriodicKeyTransparencyVerificationActivity;
-(void)internal_fetchEndpointCacheStateForServiceIdentifier:(id)arg1 localURI:(id)arg2 remoteURI:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)internal_fetchTransparentEndpointsForServiceIdentifier:(id)arg1 localURI:(id)arg2 remoteURI:(id)arg3 verifyAgainstTrustCircle:(char)arg4 completion:(/*^block*/id)arg5 ;
-(void)internal_kickVerificationForServiceIdentifier:(id)arg1 localURI:(id)arg2 remoteURI:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)internal_fetchVerifierTrustedDevicesWithCompletion:(/*^block*/id)arg1 ;
-(void)internal_fetchVerifierCloudKitTrustedDevicesWithCompletion:(/*^block*/id)arg1 ;
-(void)internal_fetchVerifierAccountKeyTrustedDevicesWithCompletion:(/*^block*/id)arg1 ;
-(void)internal_fetchVerifierAccountKeyPublicDataWithCompletion:(/*^block*/id)arg1 ;
-(void)internal_fetchCloudKitTransparencyStateWithCompletion:(/*^block*/id)arg1 ;
-(void)internal_nukeCloudKitTransparencyStateWithCompletion:(/*^block*/id)arg1 ;
-(void)internal_nukeTransparencyState:(/*^block*/id)arg1 ;
@end

