/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSTemporaryPhoneUserTransaction.h>

@class IDSTemporaryPhoneUser, IDSTemporaryPhoneUserCredential, NSString;

@interface IDSTemporaryPhoneUserAddTransaction : NSObject <IDSTemporaryPhoneUserTransaction> {

	IDSTemporaryPhoneUser* _user;
	IDSTemporaryPhoneUserCredential* _credential;

}

@property (nonatomic,retain) IDSTemporaryPhoneUser * user;                              //@synthesize user=_user - In the implementation block
@property (nonatomic,retain) IDSTemporaryPhoneUserCredential * credential;              //@synthesize credential=_credential - In the implementation block
@property (nonatomic,readonly) long long type; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)description;
-(long long)type;
-(IDSTemporaryPhoneUser *)user;
-(void)setUser:(IDSTemporaryPhoneUser *)arg1 ;
-(IDSTemporaryPhoneUserCredential *)credential;
-(void)setCredential:(IDSTemporaryPhoneUserCredential *)arg1 ;
-(id)initWithUser:(id)arg1 credential:(id)arg2 ;
@end

