/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:23 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSUserCredential.h>

@class IDSAuthenticationCertificate, NSData, NSString;

@interface IDSTemporaryPhoneUserCredential : NSObject <IDSUserCredential> {

	IDSAuthenticationCertificate* _phoneAuthenticationCertificate;

}

@property (nonatomic,readonly) NSData * dataRepresentation; 
@property (nonatomic,readonly) IDSAuthenticationCertificate * phoneAuthenticationCertificate;              //@synthesize phoneAuthenticationCertificate=_phoneAuthenticationCertificate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)description;
-(NSData *)dataRepresentation;
-(id)initWithDataRepresentation:(id)arg1 ;
-(long long)realm;
-(IDSAuthenticationCertificate *)phoneAuthenticationCertificate;
-(id)initWithPhoneAuthenticationCertificate:(id)arg1 ;
@end

