/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:05 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IDSMPFullLegacyIdentity, IDSMPPublicLegacyIdentity;

@interface IDSUTunControlChannelIdentityPair : NSObject {

	IDSMPFullLegacyIdentity* _localFullIdentity;
	IDSMPPublicLegacyIdentity* _remotePublicIdentity;

}

@property (nonatomic,readonly) IDSMPFullLegacyIdentity * localFullIdentity;                   //@synthesize localFullIdentity=_localFullIdentity - In the implementation block
@property (nonatomic,readonly) IDSMPPublicLegacyIdentity * remotePublicIdentity;              //@synthesize remotePublicIdentity=_remotePublicIdentity - In the implementation block
-(id)description;
-(id)initWithLocalFullIdentity:(id)arg1 remotePublicIdentity:(id)arg2 ;
-(IDSMPFullLegacyIdentity *)localFullIdentity;
-(IDSMPPublicLegacyIdentity *)remotePublicIdentity;
@end

