/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSMutableArray;

@interface IDSUTunTimingLogger : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	NSMutableArray* _timingEvents;
	double _lastPrintTime;

}
+(id)outgoingEventWithTimestamp:(double)arg1 duration:(double)arg2 processTime:(double)arg3 compressionTime:(double)arg4 sendTime:(double)arg5 bytes:(long long)arg6 ;
+(id)incomingEventWithTimestamp:(double)arg1 duration:(double)arg2 processTime:(double)arg3 compressionTime:(double)arg4 kernelTime:(double)arg5 bytes:(long long)arg6 ;
+(id)kernelTestEventWithTimestamp:(double)arg1 kernelTime:(double)arg2 bytes:(long long)arg3 ;
-(id)init;
-(void)addEvent:(id)arg1 ;
-(void)printCurrent;
@end

