/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:47:58 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <identityservicesd/identityservicesd-Structs.h>
@class NSString, NSMapTable;

@interface IDSUTunPeerServiceMap : NSObject {

	NSString* _name;
	os_unfair_lock_s _lock;
	unsigned char _remoteInstanceID[16];
	NSMapTable* _serviceNameToStreamIDMap;
	NSMapTable* _streamIDToServiceNameMap;
	unsigned short _nextStreamID;
	unsigned char _previousRemoteInstanceIDs[8][16];
	int _nextRemoteInstanceIDIndex;

}

@property (readonly) unsigned long long count; 
-(id)description;
-(unsigned long long)count;
-(id)initWithName:(id)arg1 ;
-(void)_simulateCrashWithErrorString:(id)arg1 ;
-(void)_dumpServiceMap;
-(char)setRemoteInstanceID:(unsigned char*)arg1 ;
-(char)associateServiceName:(id)arg1 withStreamID:(unsigned short)arg2 remoteInstanceID:(unsigned char*)arg3 remoteInstanceIDChanged:(char*)arg4 ;
-(char)translateStreamID:(unsigned short)arg1 toServiceName:(id*)arg2 remoteInstanceID:(unsigned char*)arg3 remoteInstanceIDChanged:(char*)arg4 ;
-(char)translateServiceName:(id)arg1 toStreamID:(unsigned short*)arg2 createIfNotFound:(char)arg3 mappingCreated:(char*)arg4 remoteInstanceID:(unsigned char*)arg5 remoteInstanceIDChanged:(char*)arg6 ;
-(void)dumpServiceMap;
@end

