/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:18 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@protocol IDSUser;
@class IDSUserProperties;

@interface IDSUserDescription : NSObject <NSSecureCoding> {

	id<IDSUser> _user;
	IDSUserProperties* _properties;

}

@property (nonatomic,retain) id<IDSUser> user;                            //@synthesize user=_user - In the implementation block
@property (nonatomic,retain) IDSUserProperties * properties;              //@synthesize properties=_properties - In the implementation block
+(char)supportsSecureCoding;
-(id)description;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id<IDSUser>)user;
-(void)setUser:(id<IDSUser>)arg1 ;
-(IDSUserProperties *)properties;
-(void)setProperties:(IDSUserProperties *)arg1 ;
-(id)initWithUser:(id)arg1 properties:(id)arg2 ;
@end

