/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:02 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSUserStoreListener <NSObject>
@required
-(void)userStore:(id)arg1 didRemoveUser:(id)arg2 withAuthenticationCertificate:(id)arg3;
-(void)userStore:(id)arg1 didAddUser:(id)arg2;
-(void)userStore:(id)arg1 didUpdateUser:(id)arg2;
-(void)userStore:(id)arg1 didRemoveAuthenticationCertificateForUser:(id)arg2;

@end

