/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:00 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/IDSBaseMessageSigningSession.h>

@protocol OS_dispatch_queue;
@class NSData, NSString, NSObject;

@interface IDSValidationSession : NSObject <IDSBaseMessageSigningSession> {

	NSData* _helloMessage;
	NSString* _UDID;
	NSString* _serialNumber;
	NSString* _IMEI;
	NSString* _MEID;
	NSData* _scoringNonce;
	NSObject*<OS_dispatch_queue> _queue;
	long long _stateFlags;
	NSData* _BAACert;
	NSData* _intermediateRootCert;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) long long stateFlags;                            //@synthesize stateFlags=_stateFlags - In the implementation block
@property (nonatomic,copy) NSData * helloMessage;                             //@synthesize helloMessage=_helloMessage - In the implementation block
@property (nonatomic,copy) NSString * UDID;                                   //@synthesize UDID=_UDID - In the implementation block
@property (nonatomic,copy) NSString * serialNumber;                           //@synthesize serialNumber=_serialNumber - In the implementation block
@property (nonatomic,copy) NSString * IMEI;                                   //@synthesize IMEI=_IMEI - In the implementation block
@property (nonatomic,copy) NSString * MEID;                                   //@synthesize MEID=_MEID - In the implementation block
@property (nonatomic,copy) NSData * scoringNonce;                             //@synthesize scoringNonce=_scoringNonce - In the implementation block
@property (nonatomic,copy) NSData * BAACert;                                  //@synthesize BAACert=_BAACert - In the implementation block
@property (nonatomic,copy) NSData * intermediateRootCert;                     //@synthesize intermediateRootCert=_intermediateRootCert - In the implementation block
@property (nonatomic,readonly) char isUsingAbsintheV3; 
@property (nonatomic,readonly) char isUsingAbsintheV4; 
@property (nonatomic,readonly) char isUsingBAA; 
@property (nonatomic,readonly) char isInitializedForSigning; 
@property (nonatomic,readonly) char isInitializedForScoring; 
+(char)_isBAAOptionEnabledByServerBag;
+(char)isSigningSupported;
+(char)isScoringSupported;
+(char)_isAbsintheV3EnabledByServerBag;
+(id)_BAAFetchTimeoutFromServerBag;
+(id)_BAACertTTLInMinutesFromServerBag;
-(void)dealloc;
-(id)description;
-(void)invalidate;
-(id)initWithQueue:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSString *)serialNumber;
-(void)setSerialNumber:(NSString *)arg1 ;
-(NSString *)IMEI;
-(NSString *)MEID;
-(void)setIMEI:(NSString *)arg1 ;
-(void)setMEID:(NSString *)arg1 ;
-(NSData *)BAACert;
-(void)setBAACert:(NSData *)arg1 ;
-(void)setIntermediateRootCert:(NSData *)arg1 ;
-(NSString *)UDID;
-(char)isInitializedForSigning;
-(id)headersBySigningData:(id)arg1 error:(id*)arg2 ;
-(void)initializeWithCompletion:(/*^block*/id)arg1 ;
-(void)setUDID:(NSString *)arg1 ;
-(char)isInitializedForScoring;
-(void)setHelloMessage:(NSData *)arg1 ;
-(id)signData:(id)arg1 ;
-(char)isUsingAbsintheV4;
-(char)isUsingBAA;
-(void)setStateFlags:(long long)arg1 ;
-(void)setScoringNonce:(NSData *)arg1 ;
-(long long)stateFlags;
-(char)_shouldUseAbsinthe;
-(id)activateWithValidationData:(id)arg1 serverKey:(id)arg2 scoringNonce:(id)arg3 ;
-(void)deviceScoreWithCompletion:(/*^block*/id)arg1 ;
-(char)isUsingAbsintheV3;
-(char)_shouldUseAbsintheV4;
-(char)_shouldUseBAAOnly;
-(char)_shouldUseBAACertOption;
-(char)_shouldUseDebugPiscoLogging;
-(id)_deviceAbsintheUDID;
-(id)_deviceAbsintheSerialNumber;
-(id)_deviceAbsintheIMEI;
-(id)_deviceAbsintheMEID;
-(NSData *)helloMessage;
-(NSData *)scoringNonce;
-(NSData *)intermediateRootCert;
@end

