/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSWPLinkManagerConnectivityDelegate <NSObject>
@required
-(void)manager:(id)arg1 cbuuidDidConnect:(id)arg2 isAlwaysConnected:(char)arg3;
-(void)manager:(id)arg1 cbuuidDidDisconnect:(id)arg2;
-(char)manager:(id)arg1 cbuuidDidDiscover:(id)arg2;
-(void)manager:(id)arg1 cbuuidDidFailToConnect:(id)arg2 withReason:(id)arg3;

@end

