/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSXPCActivityMonitor <NSObject>
@required
-(void)unsubscribeActivity:(id)arg1 andSubActivity:(id)arg2 withCompletion:(/*^block*/id)arg3;
-(void)checkIfListeningForActivity:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setShouldListen:(char)arg1 forActivity:(id)arg2 completion:(/*^block*/id)arg3;
-(void)currentSubscriptionsForActivity:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setupActivityMonitorClient:(id)arg1 forActivity:(id)arg2;
-(void)subscribeInfo:(id)arg1 forActivity:(id)arg2 withCompletion:(/*^block*/id)arg3;

@end

