/*
* This header is generated by classdump-dyld 1.0
* on Thursday, March 2, 2023 at 12:48:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IDSXPCPairing
@required
-(void)addPairedDevice:(id)arg1 completion:(/*^block*/id)arg2;
-(void)addPairedDeviceWithInfo:(id)arg1 completion:(/*^block*/id)arg2;
-(void)updatePairedDevice:(id)arg1 pairingType:(long long)arg2 completion:(/*^block*/id)arg3;
-(void)connectPairedDeviceWithID:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setupCompletedForPairedDeviceWithID:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getPairingDevicesWithCompletion:(/*^block*/id)arg1;
-(void)getPairedDevicesWithCompletion:(/*^block*/id)arg1;
-(void)getPairingRecordsWithCompletion:(/*^block*/id)arg1;
-(void)updatePairedDeviceWithID:(id)arg1 supportIPsec:(char)arg2 completion:(/*^block*/id)arg3;
-(void)deletePairedDeviceWithID:(id)arg1 completion:(/*^block*/id)arg2;
-(void)unpairStartForDeviceWithID:(id)arg1 completion:(/*^block*/id)arg2;
-(void)stopLocalPairingForDeviceWithID:(id)arg1 completion:(/*^block*/id)arg2;
-(void)unpairDeviceWithID:(id)arg1 completion:(/*^block*/id)arg2;
-(void)forgetDeviceWithID:(id)arg1 completion:(/*^block*/id)arg2;
-(void)switchActivePairedDeviceWithID:(id)arg1 completion:(/*^block*/id)arg2;
-(void)disconnectActivePairedDevice:(/*^block*/id)arg1;
-(void)redeliverMessagesForDevice:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setAllowedTrafficClassifiersForDevice:(id)arg1 classifiers:(id)arg2 completion:(/*^block*/id)arg3;
-(void)dropAllMessagesWithoutAnyAllowedClassifierForDevice:(id)arg1 completion:(/*^block*/id)arg2;
-(void)pairedDevicesInfo:(/*^block*/id)arg1;

@end

